- src/components/GameList/GameList.styl
- src/components/GameList/GameList.tsx
- src/components/GobanLineSummary/GobanLineSummary.styl
- src/global_styl/font-awesome-hacks.styl
- src/views/ObserveGames/ObserveGames.tsx
> Add sort capability to game lists, with default sort order being by time left

- src/views/Play/Play.tsx
This PR fixes a minor issue where the SeekGraph isn't displayed due to its container div sometimes having no size when first mounted.
> Ensure graph is drawn on Play page

- src/views/Puzzle/Puzzle.styl
Didn't realize this style would be duplicated somewhere else. I did a search and didn't find anywhere else this fix was necessary so I think this should do it.
> flex grow fix for goban applied to puzzle styl as well

- src/views/docs/GoResources.tsx
> Fix interoduced bug that breaks the build

- src/views/Settings/Settings.tsx
Adds an **Autoplay delay (in seconds)** option on Settings.
> Make autoplay delay configurable

- src/components/NavBar/NavBar.tsx
> Whitespace in the search box

- src/components/GameList/GameList.tsx
- src/components/GobanLineSummary/GobanLineSummary.tsx
- src/lib/data.ts
- src/views/ObserveGames/ObserveGames.tsx
- src/views/Overview/Overview.tsx
- src/views/User/User.tsx
The game list now displays the player's opponents correctly.
> Fix for bug #64

- src/components/GameAcceptModal/GameAcceptModal.tsx
This PR is a very small change to let the accept modal be closed easily.
> Allow fast dismiss for game accept modal

- src/components/Chat/Chat.styl
- src/components/Chat/Chat.tsx
- src/lib/preferences.ts
Separate group channels, tournament channels and global channels so to be able to choose which to maximize and which to minimize.
Fixes #65.
> Expand channel classes separately

- src/components/Chat/Chat.styl
> Hide scrollbar when not needed

- src/views/Puzzle/Puzzle.tsx
Puzzle.getBounds can return null. Puzzle.fetchPuzzle failed to account for this. Added a check for the null return value.
> Fix bug #199

- src/views/Play/Play.tsx
New <Rules> column and small refactoring in Play.tsx.
> #208: header <Rules> added to game list page

- src/views/Game/Game.tsx
This applies to game pages, implements #271
> Play a stone sound every time we change the volume

- src/components/NavBar/NavBar.tsx
> Show "Games" in both top bar and side menu for consistency

- src/components/Chat/Chat.tsx
- Type "issue N" in chat to link an issue
- Type "pr N" in chat to link a pull request
> Link Github issues and PRs in chat

- src/components/Player/Player.tsx
I missed a rather embarrassing and crucial part out from my previous PR.
> Add missing part to Player component.

- README.md
Update the build instructions to use Yarn for module installation instead of npm. Fix broken image.
> Update the build instructions

- src/components/NavBar/NavBar.tsx
Requested from:
https://forums.online-go.com/t/putting-profile-button-on-top-menu-bar/12711
> Added profile button to Navigation Bar

- src/components/Player/Player.tsx
- src/lib/player_cache.ts
- src/views/Game/Game.tsx
- src/views/Group/Group.tsx
This PR fixes a number of bugs that have been causing way more player cache misses than intended.
CC @BarneyStratford - most of the fixes are outside of the player cache system, but there were a couple of tweaks inside as well that you might want to be aware of if you're still planning on making changes to that system
> Excess player cache hit fixes

- Gulpfile.js
- src/lib/ogs-goban/Goban.ts
- src/lib/ogs-goban/MoveTree.ts
- src/views/Puzzle/Puzzle.styl
- src/views/Puzzle/Puzzle.tsx
- src/views/Puzzle/PuzzleEditing.ts
- src/views/Puzzle/PuzzleNavigation.ts
- src/views/Puzzle/PuzzleSettingsModal.tsx
- src/views/Puzzle/PuzzleTransform.ts
- webpack.config.js
- Refactoring in Puzzle.tsx
- Add Hint button for showing one of the correct moves.
> Hint button in Puzzle screen

- src/components/AutomatchSettings/AutomatchSettings.tsx
- src/components/ChallengeModal/ChallengeModal.tsx
- src/components/Chat/Chat.tsx
- src/components/ChatPresenceIndicator/ChatPresenceIndicator.tsx
- src/components/ChatUserList/ChatUserList.tsx
- src/components/GameList/GameList.tsx
- src/components/GobanThemePicker/GobanThemePicker.tsx
- src/components/LanguagePicker/LanguagePicker.tsx
- src/components/MiniGoban/MiniGoban.tsx
- src/components/NewGameModal/NewGameModal.tsx
- src/components/Notifications/Notifications.tsx
- src/lib/debug.ts
- src/lib/goban.ts
- src/lib/player_cache.ts
- src/lib/preferences.ts
- src/lib/profanity_filter.ts
- src/lib/sockets.ts
- src/main.tsx
- src/views/Game/Game.tsx
- src/views/ObserveGames/ObserveGames.tsx
- src/views/Puzzle/Puzzle.tsx
- src/views/Puzzle/PuzzleEditing.ts
- src/views/Puzzle/PuzzleSettingsModal.tsx
- src/views/Settings/Settings.tsx
- src/views/TournamentList/TournamentList.tsx
… allowing us to enable per-module debugging as the need arises. Remove a bunch of assignments to global properties into the debugging module, where they belong.
> Introduce a debugging module

- src/views/User/User.tsx
> Trim whitespace from usernames.

- src/views/Game/Game.styl
- src/views/Game/Players.styl
> Make width of game container 100%

- src/components/ChallengeModal/ChallengeModal.tsx
This small change fixes the issue in #434. The change doesn't really address why user.ranking is wrong in the first place though.
> Fixed range of ranks in Restrict Rank, see issue #434

- src/views/User/User.styl
For consistency, the title "Ratings" should be left aligned like the titles of other sections (Active Games, Activity, Game History...) on the page.
> Ratings title should be left aligned like other sections.

- src/views/Developer/Developer.styl
- src/views/Developer/Developer.tsx
In the Developers page, added GitHub stars & forks below the project link (using http://ghbtns.com).
> Added GitHub stats (stars & forks) below project link.

- src/views/Game/Game.tsx
I was motivated to do this when I saw Dwyrin go "Argh! I hate that!"  as he slid the volume control while playing on OGS in one of this videos, and it went "clickclickclickclickclick".
I thought "we can't have Dwyrin hating OGS!!"
Now it just goes "click" when you arrive at the target volume.
> Debounce playing sounds on the volume control slider.

- src/views/LadderList/LadderList.styl
> Ladder page: Space b/w buttons.

- src/views/User/User.styl
- src/views/User/User.tsx
People (including me :) ) hadn't realised that you can search for a player in the Game History.
So this puts a little search icon to make it clear.
https://forums.online-go.com/t/you-can-find-your-games-vs-a-specified-player/14241
> Search icon for search input on game history

- src/components/PaginatedTable/PaginatedTable.styl
- src/global_styl/global.styl
- src/views/GroupList/GroupList.styl
- src/views/GroupList/GroupList.tsx
- src/views/LadderList/LadderList.styl
- src/views/LadderList/LadderList.tsx
- src/views/LeaderBoard/LeaderBoard.styl
- src/views/LeaderBoard/LeaderBoard.tsx
- src/views/Overview/Overview.tsx
- src/views/Play/Play.styl
- src/views/PuzzleList/PuzzleList.styl
- src/views/PuzzleList/PuzzleList.tsx
- src/views/Tournament/Tournament.tsx
- src/views/TournamentList/TournamentList.styl
- src/views/TournamentList/TournamentList.tsx
Made pages look more consistent:
- title (w/ icon) and actions on top.
- same maximum width for pages.
- no "card" on list pages.
- horizontal lines b/w table rows.
New puzzle page:
> Pages title and width

- src/views/PuzzleList/PuzzleList.styl
> Puzzle List: rating stars in light orange + number of ratings in grey.

- src/views/Settings/Settings.styl
- src/views/Settings/Settings.tsx
I think it is an improvement but it could be subjective...
Current:
Proposed:
> Settings: rearranged page.

- src/components/Chat/Chat.styl
- src/components/Chat/Chat.tsx
- src/views/Game/Game.tsx
- src/views/Group/Group.styl
- src/views/Group/Group.tsx
- src/views/LadderList/LadderList.styl
- src/views/Overview/Overview.styl
- src/views/Overview/Overview.tsx
- src/views/User/User.styl
- src/views/User/User.tsx
Resolve issue #468. Hover text with the full date was added for timestamp in the chat.
> Resolve issue #468 ; add date hover text in chat backlog

- src/views/LibraryPlayer/LibraryPlayer.styl
- src/views/LibraryPlayer/LibraryPlayer.tsx
> SGF Library: Text edit + lock icon for "private collection".

- src/components/NavBar/NavBar.styl
- src/components/NavBar/NavBar.tsx
... as requested: https://forums.online-go.com/t/how-do-i-search-for-a-player-name/12254
> Search icon for OmniSearch

- src/views/Overview/Overview.tsx
This is supposed to resolve #422, I also was looking for that feature so I picked it up, please give me some feedback :+1:
> Display number of waiting games in Home title

- src/global_styl/global.styl
- src/views/Settings/Settings.tsx
Added "Settings" title w/ icon on top of the page.
> Added page title to "Settings".

- src/views/docs/Team.tsx
> Team page: page title + standard page width + 2 columns.

- src/components/PrivateChat/PrivateChat.styl
fixes https://github.com/online-go/online-go.com/issues/509
> Prevent long words overflow in private chat

- src/views/Group/Group.styl
> Group: added margins between admins.

- src/components/KBShortcut/KBShortcut.tsx
- src/views/Game/Chat.styl
- src/views/Game/Game.tsx
Add a toggle beside the chat input which shows/hides a list of editable
messages which can be sent with one click.
> Add "quick chat" feature to in-game chat box

- src/views/Play/Play.styl
- src/views/Play/Play.tsx
(apologies some spurious formatting changes got included in the source code, my editor auto format went nuts)
> Filter challenges #601

- src/lib/translate.ts
I put Esperantujo in as a way to get the Esperanto flag as a user country.
> Let Esperanto speakers pretend they come from Esperantujo (implements #609)

- src/components/Dock/Dock.styl
- src/components/Dock/Dock.tsx
- src/lib/preferences.ts
- src/views/Settings/Settings.tsx
> Made dock delay configurable by preferences

- src/global_styl/misc-ui.styl
I put this into a separate branch, so we can have it even if we don't move forwards with the waiting dialog fix for a while.
> Themed colour of double bounce spinner, so it's visible in dark.

- README.md
> Fixing minor errors in README.

- src/views/User/User.tsx
> Fixed typo.

- CONTRIBUTING.md
- README.md
To make the project more accessible to new contributors, I added documentation to the README and CONTRIBUTING files.
Readme: Added license and website up/down shields.  Added section for locating resources for people to use the project in their own project, as well as a small social media section.
Contributing: Added getting started, how to make changes, how to submit changes sections, and a technologies used section.  Allows newer contributors an easier avenue towards a successful contribution to the project.
> Updated README and Contributing Guide.

- src/components/Player/Player.tsx
- src/components/Player/PlayerDetails.tsx
- src/components/RatingsChart/RatingsChart.tsx
- src/components/SeekGraph/SeekGraph.tsx
- src/index.html
- src/lib/rank_utils.ts
- src/views/Overview/Overview.tsx
- src/views/Play/Play.tsx
- src/views/User/User.tsx
This patch set will include all the UI work needed to implement the
humble rating feature.
Closes #570
> Humble rating implementation

- src/components/IncidentReportTracker/IncidentReportTracker.styl
- src/components/IncidentReportTracker/IncidentReportTracker.tsx
- src/views/docs/Team.tsx
- yarn.lock
Just call me Eugene :)
Plus:
- Tweak layout so it doesn't change when you click buttons
- Add the content of the Note as the default value when editing it
> Team member update plus incident report layout tweaks

- src/views/Play/Play.tsx
> Put Rank column header back into Correspondence Automatch table

- src/components/IncidentReportTracker/IncidentReportTracker.styl
- src/components/IncidentReportTracker/IncidentReportTracker.tsx
> Give report header a number, for reference in chat

- src/components/GameAcceptModal/GameAcceptModal.styl
- src/components/GameAcceptModal/GameAcceptModal.tsx
- src/components/TimeControl/util.ts
- src/views/Play/Play.styl
- src/views/Play/Play.tsx
> Added basic warning for the time settings used by cheats

- src/components/GameAcceptModal/GameAcceptModal.tsx
- src/views/Game/Game.styl
- src/views/Play/Play.tsx
As per moderators discussion, it seems like it would be helpful to warn players when there is custom komi.
> Added a warning about custom komi.

- src/components/IncidentReportTracker/IncidentReportTracker.tsx
Teeny tweak, for ease of moderator chat.
(Was heading in the direction of making magic links, like the games and players etc, but that requires more work in terms of how to display the linked report... so ...later!)
> Improve visible report number.

- src/global_styl/flags16.styl
- src/global_styl/flags32.styl
- src/lib/translate.ts
Adds Lord Howe Island to the list of extended countries
> Issue #743: add Lord Howe Island to list of extended countries

- src/ogs.styl
> Issue #730: move PlayerAutocomplete behind model z-index

- src/views/ObserveGames/ObserveGames.tsx
> observe games: changing page length resets page to 1

- src/views/Game/Game.tsx
To save dummies like me after accidentally clicking the wrong button  😮
> Put what's about to happen on the moderator notes dialog

- src/components/Dock/Dock.styl
- src/views/Game/Game.tsx
The "This game was already annulled" dialog has become bit much :)
> Indicate to moderator if the game is not actually annulable.

- src/views/Play/Play.tsx
Actually, here they are, in case you want them now.
> Rogue logs

- src/views/Game/Game.tsx
I think this fixes #630 without breaking anything.
> Fix variation viewing

- src/views/Play/Play.styl
- src/views/Play/Play.tsx
Clarifies that a correspondence game request has been initiated by showing a loading spinner in the UI for five seconds and directing the user to the panel below to view their automatch requests.
> implemented UI changes to fix forum #20992

- src/components/TimeControl/util.ts
- src/views/Play/Play.tsx
Simple bugfix so that custom komi of 0 gets the warning, like any other custom komi.
> Fix check for custom komi.

- src/views/Game/Game.tsx
> Fixed up saving the correct volume

- src/views/docs/GoResources.tsx
https://forums.online-go.com/t/yoons-baduk-cafe/22252/9?u=bhydden
> add yoon's channel to youtube resources

- src/views/Game/Game.tsx
Fixes #834
Removed saveVolume method to more closely match the structure of the Settings view. Don't know if this is desired. I could also add a saveVolume to the Settings view ...
> save volume on toggle

- src/views/docs/legal.tsx
As discussed in moderator team.
> Put the legals we refer to most often at the top.

- src/views/Play/Play.tsx
> Added missing string translations for cheat alert tooltip

- src/views/Game/Game.tsx
With this the shippable checks shouldn't fail any more.
> remove trailing whitespaces

- src/views/Game/Game.tsx
resolves gh-813
The score estimator is an analysis tool so should be disabled when analysis is disabled in the match options.
> Disable score estimator when analysis is disabled

- src/components/Notifications/Notifications.tsx
- src/lib/goban.ts
- src/views/Game/Game.tsx
PR to resolve issue #892 
WIP - LF feedback @anoek 
I get a Type Error preventing the site from loading when I try to communicate with src/components/Notifications/Notifications.tsx from src/lib/goban.ts
https://i.imgur.com/Vc9mkqJ.png
Looks like some kind of compiling dependency issue of things loading in the wrong order, could you point me in the right direction? I was thinking of moving the whole autoadvance function from lib/goban over to Notifications... is that the right idea or will that not resolve this dependency issue / create new issues?
> Only auto-advance if your turn

- src/components/NavBar/NavBar.tsx
> Add Joseki to the top nav-bar

- src/views/Joseki/Joseki.styl
- src/views/Joseki/Joseki.tsx
Making the whole thing scroll vertically like the game view does solves a bunch of vertical sizing problems!
> Another try at making it mobile friendly (!)

- src/components/TimeControl/util.ts
- src/views/User/User.tsx
> Add vacation days accrued to profile 

- src/components/JosekiTagSelector/JosekiTagSelector.tsx
Fixes #908 
- Remove the line that adds an empty element to the start
Co-authored-by: @GreenAsJade
> fixes #908 Joseki filter crash - GreenAsJade to test and confirm

- src/views/Joseki/Joseki.styl
- src/views/Joseki/Joseki.tsx
This brings a new "results" pane to the Play mode, where the user is told information about the number josekis they've played and how successful they are at playing them.
It also makes Play mode select the "Joseki" filter, if none is selected, rather than just opening the filter pane, because doing it this way is a lot more pleasant experience.'
> Joseki "Play mode" upgrade

- src/views/docs/GoResources.tsx
- Add "Interactive Tutorial for Beginners" under Learning Resources
- Add Twitch links for Dwyrin, Xhu98, and Lumbertruck under Video Channels
- Fix name of "Got Stats" to "Got Stats?"
- Add "PacifiGo" under Equipment
- various cleanup
> Adam's Interactive Tutorial and other various additions to Resources

- src/views/Joseki/Joseki.tsx
Fixes #920
Refactored initialisation to make sure goban is initialised on a revisit to the route (which apparently does not cause the component to re-mount - probably that makes sense!)
> Fixes Issue 920

- src/views/LeaderBoard/LeaderBoard.tsx
resubmit #927 
- Fix title on Leaderboards page to be less confusing.
- No changes to whole file formatting.
> resubmit Leaderboard Title

- src/views/docs/Team.tsx
> add flovo to mod team page

- src/views/Joseki/Joseki.tsx
Apparently you can't do that :)
> es5 reversion bugfix (can't edit joseki descriptions)

- src/components/Announcements/Announcements.styl
- src/lib/toast.styl
While in zen mode hide
- announcements
- message toasts
> Hide popups in zen mode

- src/views/Joseki/Joseki.tsx
when an exploratory position is clicked on.
(and start adding more typing)
> Remove lingering old position information 

- src/views/docs/GoResources.tsx
- Links for her English channel and her Korean channel added to "Video Channels" section of "Other Go resources"
> Add Cho Yeonwoo's channels to video resources

- src/components/Chat/Chat.tsx
- src/components/Chat/ChatDetails.tsx
popups still being blocked for some reason
> add middle click support to chat links

- src/views/docs/GoResources.tsx
resolves https://forums.online-go.com/t/please-add-weiqitv-to-other-resources-page/23478?u=bhydden
> Add WeiqiTV to Other Resources page

- src/views/Game/AIReview.tsx
Fixes #972 
- adds offset to move numbers to account for handicap stones
> add handicap offset

- src/views/User/User.tsx
Fixes issue with reviews and demos no longer showing
> Fixes bug introduced with game history table update

- src/views/User/User.tsx
Annulled games shouldn't get win/loss color in the history table
> remove win/loss color for annulled games

- src/views/User/User.tsx
Fixes word wrapping of annulled game result text
> add class to annulled games to prevent word wrap

- src/views/Settings/Settings.tsx
Fixes #991 
Added clarifying text to analysis setting in settings menu
> clarify analysis setting

- src/components/JosekiAdmin/JosekiAdmin.tsx
- src/components/JosekiStatsModal/JosekiStatsModal.styl
- src/components/JosekiStatsModal/JosekiStatsModal.tsx
- src/components/JosekiVariationFilter/JosekiVariationFilter.tsx
- src/ogs.styl
- src/views/Joseki/Joseki.styl
- src/views/Joseki/Joseki.tsx
Adds a column to the Joseki stats modal that has the count of position loads by guest (anonymous).
> Show Joseki guest position load stats and other tidyups

- src/views/Game/Chat.tsx
Fix as per #997 recommendation, tested on beta seems to work.
-
-
-
> Fixes #997, kinda urgent: Make blocked game chat get hidden

- src/components/Clock/Clock.styl
- src/ogs.styl
- src/views/Game/Game.tsx
- src/views/Game/Players.styl
... in a recent Dwyrin video I noticed what a pain it is for users to have a centre-screen swal dialog every time they want to clear marks.
This PR asserts that it's really not needed at all - clearing marks is a lightweight deletion that needs to be easy for a reviewer, and with low consequences of accidental use.
If it turns out some sort of confirmation is needed, let's find that out by putting this in, then adding the next thing if/when needed and when we know what it should be.
> There's really no need to double check the "clear marks" action

- src/views/Joseki/Joseki.tsx
Fixes use of null
Get rid of null :)
Could we have this branch on beta, to get a few more eyes on it?   I think I've checked everything, but a hard change to be sure about.
> Get rid of null, use undefined for undefined things.

- src/views/Moderator/Moderator.tsx
- Attempt to add an email column for new users in moderator page
> add email to moderator page

- src/components/Chat/Chat.tsx
- Fix wrong URL replacement for github-wiki replacements
- Add TOC to matches for github-wiki
> Chat markup update

- src/components/JosekiStatsModal/JosekiStatsModal.styl
- src/components/JosekiStatsModal/JosekiStatsModal.tsx
- src/views/Joseki/Joseki.tsx
* The stats for mode got broken late last year - fixed
* The stats display modal should be scrollable - fixed
> Joseki stats bugfixes

- src/views/Game/Game.tsx
- src/views/Game/Players.styl
As per this thread https://forums.online-go.com/t/player-leaves-match-no-way-to-contact-them/24574
the disconnect timer covers up more than one important function.
Just cover up the player's avatar.
This change also has a separate commit that reindents this part of the code, some of it was on 2-space, now it's all 4.
> Make the disconnect timer not cover up other important things

- src/components/GobanLineSummary/GobanLineSummary.styl
Horizontally centre the list on https://online-go.com/observe-games
> center the summary list on view games page

- src/views/Game/GameTimings.tsx
- src/views/Joseki/Joseki.tsx
... and fix the superfluous 's' on the game timings page.
Don't accept a back button press while we're waiting for a server response.
(Was supposed to be like that already, but not enough protection in place to achieve it)
> More protection against backsteppers in joseki

- src/components/JosekiStatsModal/JosekiStatsModal.tsx
- src/components/PrivateChat/PrivateChat.styl
- src/components/PrivateChat/PrivateChat.tsx
Fixes people not realising they are getting PMed by a Moderator
Put a banner at the top of the PM box saying it's a moderator
> Moderator pm banner

- src/components/JosekiStatsModal/JosekiStatsModal.tsx
- src/components/PrivateChat/PrivateChat.tsx
Improved wording of chat banner.
Get rid of spurious joseki data points
> Tweak moderator chat banner, tweak joseki stats graph filter.

- Dockerfile
Proposing update the base image tag here to `10.15.1`, following the version used in https://github.com/online-go/online-go.com/blob/devel/shippable.yml#L4
Reference - https://hub.docker.com/layers/node/library/node/10.15.1/images/sha256-8fc2110c6978657838569afd5e135ab2e0b4a668cbd6d56bd963ecea19b03cfd?context=explore
> Dockerfile - update base image tag

- src/components/JosekiStatsModal/JosekiStatsModal.tsx
- src/components/PrivateChat/PrivateChat.styl
- src/components/PrivateChat/PrivateChat.tsx
- src/views/Joseki/Joseki.tsx
Show a highlighted banner with official message when megaphone is on.
(Also, more tidyup of Joseki stats graph)
> Various tweaks: alert banner for megaphone, joseki graph, joseki play mode record fix

- src/components/IncidentReportTracker/IncidentReportTracker.tsx
Fixes: Claimed reports are buried by new reports
Show claimed reports at the top of the reports list.
> Show self claimed reports at the top of the list

- Gulpfile.js
> Fix bug which prevents from starting the server on Windows

- src/lib/chat_manager.ts
Don't increase unread message count when message is sent by a blocked user or oneself. 
Also don't mark such messages as mentions if the user is mentioned.
> chat_manager: don't count messages from blocked users

- webpack.config.js
> Add support for iOS 10 in minimized scripts

- src/views/Joseki/Joseki.tsx
Fixes #
Play mode was never intended to have the arrow keys enabled!
Disable arrow keys when in play mode
> Joseki disable arrow keys in play mode, you have to click in play mode

- src/views/GroupList/GroupList.tsx
This is my proposed PR for #1177
> Fix #1177 Group name search set to 'contains' instead of 'startswith'

- src/lib/preferences.ts
- src/views/Game/AIReview.tsx
- src/views/Game/AIReviewChart.tsx
Gives a shot at #1113
https://forums.online-go.com/t/proposal-score-based-ai-review
> AI reviews graphing scores: First PoC

- src/components/GobanLineSummary/GobanLineSummary.styl
- src/views/Overview/Overview.styl
On the profile page, sometimes the active games list overlaps with the activity list.
> Active games list: do not overlap with activity view

- src/views/docs/GoResources.tsx
Adding Israeli Go Association as requested in: https://forums.online-go.com/t/adding-a-link-to-other-go-resources/29408
> Adding "Israeli Go Association" into Go resources

- src/views/Game/Game.tsx
- src/views/Game/GameTimings.tsx
Fixes #
1) This shows each player's total time used
2) This fixes a bug where free-placed handicap stones were not taken into account,
> Show total player elapsed time, account for free handicap stones

- src/views/Game/AIReview.tsx
Fixes #1225
-  Fixes NaN when AI score is 0
> Bug fix for #1225

- src/lib/associations.ts
Fix title of Latvian go association.
> Fix title of Latvian go association

- src/views/User/User.tsx
> Don't show game winner trophy (or anything win related) if the game is annulled

- src/views/Game/GameTimings.tsx
Fixes the problem that the moderator game timings table had black and white reversed in Japanese handicap games
> Take into account that white goes first in japanese handicap games

- shippable.yml
- src/lib/translate.test.ts
- src/lib/translate.ts
- yarn.lock
- Add comments to translate.ts functions (Fixes issue #1248)
- Support plurals for more languages (Fixes issue #1257)
- Update *yarn.lock*. Not sure what info this file contains that *package.json* doesn't, but I think it needed to be updated after I added the jest dependency.
- Add `npx jest` to *shippable.yaml*. **I don't know how to confirm that I did this right - feedback welcome!**
> More translate updates

- src/views/Game/Game.tsx
- src/views/Game/GameTimings.tsx
#1263 had to work around start-time and end-time not being declared in GoEngineConfig.
https://github.com/online-go/goban/pull/12  will enable this PR to clean that up.
> Cleanup start time typing

- src/views/Settings/Settings.styl
- src/views/Settings/Settings.tsx
Fixes #656 
- In Settings, change the Language Picker to a dropdown
- Change the profanity switches to a multi-dropdown
> Language Settings Updates

- src/views/Game/Game.tsx
Fixes #954, Fixes #653 
- Add score estimation button to reviews.
- Fix bug where pressing `esc` during review leads to entering "play" mode (making the "Pass" button disappear in the UI).
Further enhancements (i.e. behavior when exiting score estimation mode) here: https://github.com/online-go/goban/pull/13
The PRs are independent and work without each other, but the user experience will be slightly better once both are in.
Tested locally; tslint passes.
> Added score estimation to review

- src/views/User/User.styl
Fixes: my mistake.
Fix typos in previous fix
> Correct messed up game history table css tweak

- src/lib/ogs-react-select.styl
- src/views/Settings/Settings.tsx
> Respect dark mode settings for the profanity filter setting.

- jest.config.js
- src/components/Chat/chat_markup.test.tsx
- src/components/Chat/chat_markup.tsx
- src/lib/profanity_filter.ts
Fixes #1251, but mostly other code health updates in chat_markup and profanity_filter
- Add types for profanity_filter.ts and chat_markup.tsx
- Add (some) tests for chat_markup
- Refactor chat_markup and remove empty spans that were produced.
- Remove silent issues: empty spans, global marker for RegExps
> Chat updates

- src/views/Puzzle/Puzzle.styl
- src/views/Puzzle/Puzzle.tsx
Fixes #1034
Modeled after the Joseki portrait layout.
> Added mobile portrait puzzle layout

- src/views/Game/AIReviewChart.tsx
> Fix AI chart move indicator's position on resize.

- Gulpfile.js
> Make joseki work on dev server

- src/views/Game/AIReviewChart.tsx
> Fix AI review chart's score mode when a move has score "0"

- src/lib/preferences.ts
Fixes [moaning and groaning about discoverability of the feature](https://forums.online-go.com/t/wish-better-noticeable-undo-requests/964/78?u=eugene)   ;)
Default visual-undo-request-indicator to true.
> Default undo indicator on.

- src/lib/chat_manager.ts
- src/views/Game/Game.tsx
Fixes a bit of noise in the console
Remove a couple of console.log()s
> -debug logs

- src/views/User/User.styl
- src/views/User/User.tsx
At the moment, only clicking on the game title opens the game. Clicking on any other part in the history does nothing.
With this change a click anywhere in the game history brings you to the respective game.
> GameHistory: Click on a row opens the game

- src/views/Play/Play.tsx
Fixes #1359 
Minor Typo fix 
Tested via: 
http://dev.beta.online-go.com:8080/play
> fix(1359):Fixed typo

- src/components/Chat/ChatLine.tsx
- src/components/Chat/chat_markup.tsx
- src/views/Game/Chat.tsx
- src/views/Game/Game.tsx
- Removes 1024 character limit for displayed messages which was causing some previously readable mod notes to show as `<Message too long>`
- When annulling games, words "white" and "black" will now be replaced with player links.
> Mod note improvements

- src/components/ChatPresenceIndicator/ChatPresenceIndicator.styl
- src/components/JosekiStatsModal/JosekiStatsModal.tsx
- src/components/NavBar/NavBar.styl
- src/components/NavBar/NavBar.tsx
- src/components/Notifications/Notifications.styl
- src/components/Player/Player.styl
- src/components/SeekGraph/SeekGraph.tsx
- src/index.html
- src/ogs.styl
- src/views/Game/AIReviewChart.tsx
- src/views/Game/Players.styl
Fixes the problem that we use very unfriendly colours for colourblind people.
Add a theme and tweak the colours.
> Accessibility theme

- src/components/PersistentElement/PersistentElement.tsx
- src/views/Game/Game.styl
- src/views/Game/Game.tsx
- src/views/Tournament/Tournament.tsx
Fixes #1392
Make PersistentElement take a hash of extra properties to put on the element, and put the game metadata on the Goban in this way.
> Add game metadata on Goban Div

- src/components/ChatPresenceIndicator/ChatPresenceIndicator.styl
- src/components/JosekiStatsModal/JosekiStatsModal.tsx
- src/components/NavBar/NavBar.styl
- src/components/NavBar/NavBar.tsx
- src/components/Notifications/Notifications.styl
- src/components/Player/Player.styl
- src/components/SeekGraph/SeekGraph.tsx
- src/index.html
- src/ogs.styl
- src/views/Game/AIReviewChart.tsx
- src/views/Game/Players.styl
Fixes win/loss being red/green which colour blind people find hard.
~~Make win == yellow and loss == blue~~
Make win == blue and loss ~= red
> Accessible win loss

- src/views/User/User.tsx
> Fix clicking on the username in game history

- src/components/Announcements/Announcements.styl
Left padding here causes horizontal scrollbar.
> fix announcment padding

- package.json
- src/components/AIReviewStream/AIReviewStream.tsx
- src/index.html
- src/lib/sfx.ts
- src/views/Game/AIReview.tsx
- yarn.lock
This implements the client side of the ability to interact with the AI while analyzing variations.
> Interactive AI

- src/components/KBShortcut/KBShortcut.tsx
Fixes #1407
- In **KBShortcut** class  was added handler for ctrl+c shortcut
> Added hadler for ctrl+c shortcut

- src/lib/data.ts
Just for completeness on this branch, if we want this feature update on a branch as finished.
This same fix is in #1457.
> Save sync update in localStorage

- src/components/Player/Player.tsx
- src/components/PlayerNotesModal/PlayerNotesModal.tsx
This makes it so the icon appears (or disappears) immediately in all
places and on all devices when notes are added or removed.
@GreenAsJade
> Watch notes in Player to add the notes icon when notes get updated

- src/components/PrivateChat/PrivateChat.tsx
Fixes Moderator chat PM window not opening in some cases.
Guard against moderator banner not being defined yet.
> Guard against timing resulting in moderator banner not being created yet

- package.json
- src/index.html
- src/lib/configure-goban.ts
- src/lib/sockets.ts
- src/main.tsx
- src/views/Game/Game.tsx
- yarn.lock
Replaces the old C based random playout score estimator with a remote call to the AI server cluster to perform the scoring. This affects score estimation and client driven autoscoring.
> Ai score estimate

- src/components/ChallengeModal/ChallengeModal.tsx
> a fix for the issue "Rematch setup is not consistent #1086"

- src/views/Game/AIReview.tsx
> Fix typo: queing -> queuing

- src/components/IncidentReportTracker/IncidentReportTracker.styl
- src/components/IncidentReportTracker/IncidentReportTracker.tsx
- src/components/PrivateChat/PrivateChat.styl
- src/components/PrivateChat/PrivateChat.tsx
- src/components/ReportedConversationModal/ReportedConversationModal.styl
- src/components/ReportedConversationModal/ReportedConversationModal.tsx
- src/components/ReportedConversationModal/index.ts
- src/lib/misc.ts
Fixes #1507
- I've added a report button to the top of the pm window
- Clicking the report button will open this report modal (There's a typo in "moderation" in this screenshot, but it's been corrected)
- PM reports will include a link to View Reported Conversation
- Which in turn opens a modal containing the chat
> PM Reporting

- src/components/ReportedConversationModal/ReportedConversationModal.styl
I adjusted the modal width and amount of padding for smaller screens to make reading more comfortable.
> increase reported conversation modal width for smaller screens

- src/views/Joseki/Joseki.tsx
OJE feels laggy.
It'd be good to have these log messages in production, to sanity check the basics.
> Improving Joseki Fetch

- src/views/Supporter/Supporter.styl
- src/views/Supporter/Supporter.tsx
Fixes #1069 
- Create a list of locales that should show images/text/etc from right to left.
- Draw paypal button according to this list.
This is my first attempt to contribute to OGS, so any comments are welcome! :)
> Support page - position of the paypal image

- src/components/PrivateChat/PrivateChat.styl
- src/components/PrivateChat/PrivateChat.tsx
Fixes #  1188 Added date in private message chat for first message of the day
> Show date in private message chat

- src/views/docs/Team.tsx
Added in the new mods and removed the hardcoded usernames since they are sometimes showing old usernames
> Add new mods

- src/views/docs/Team.tsx
Changed some language flags as requested in https://forums.online-go.com/t/language-skills-of-current-mod-team/39054/
> update moderator language flags

- src/views/docs/Team.tsx
I don't have a testing environment set up so just hoping this is as anoek described in https://github.com/online-go/online-go.com/pull/1527#issuecomment-922269060
Fixes English flag becoming user's country / American flag
> Allow England flag as an alternative to GB

- src/components/MiniGoban/MiniGoban.styl
Fixes #
Fixed minigoban style. Stones on minigobal oveerlay popup menu.
> Minigoban stones overlay Popup

- src/components/ACLModal/ACLModal.tsx
- src/components/GameAcceptModal/GameAcceptModal.tsx
- src/components/Modal/Modal.tsx
- src/components/TypedEventEmitterPureComponent/TypedEventEmitterPureComponent.tsx
- src/lib/misc.ts
- src/views/Game/GameInfoModal.tsx
This should help with #1362 because the info that is needed is contained in config, for which this PR adds types.
Depends on https://github.com/online-go/goban/pull/45 (expect CI to fail)
- Eliminate `any` (implicit and explicit) from GameInfoModal.tsx
- Move `yesno` to misc.ts
- Remove unused imports and variables
> Cleanup: GameInfoModal

- src/lib/misc.ts
> Fix sorting optimization introduced in #1477

- src/views/Game/AIReview.tsx
Fixes https://forums.online-go.com/t/some-bugs-report/40254/7
> bugfix: AI Review table breakage

- src/views/Game/AIReview.tsx
Fixes: [Forums: Black or Blanc](https://forums.online-go.com/t/black-or-blanc/40448)
Before:
After:
> Internationalize AI review bar.

- src/main.tsx
- src/views/Game/Game.styl
- src/views/Game/Game.tsx
Fixes the problem that you have to think twice to recognise who's turn it is.
Who wants to be reading the words that say who's turn it is - a visual cue will help avoid that.
Subtle box-shadow changes for the player-container who's turn it is
> Subtle highlight whos turn

- src/components/ChallengeModal/ChallengeModal.tsx
- src/views/Play/Play.tsx
Fixes the problem of finding live rengo challenges
Sort rengo challenge list by isLive() (which happens to include Blitz, IIUC)
> Sort rengo challenges by timesetting first (and undebug ChallengeModal)

- .github/workflows/main.yml
- src/components/JosekiTagSelector/JosekiTagSelector.tsx
> Enable prettier check in GitHub workflows.

- .eslintrc.js
- src/components/JosekiTagSelector/JosekiTagSelector.tsx
- src/views/Tournament/Tournament.tsx
- src/views/TournamentList/TournamentList.tsx
- src/views/TournamentRecord/TournamentRecord.tsx
- src/views/Tutorial/InstructionalGoban.tsx
- src/views/User/User.tsx
- src/views/docs/About.tsx
- src/views/docs/GoResources.tsx
- src/views/docs/RulesMatrix.tsx
- src/views/docs/Team.tsx
- src/views/docs/legal.tsx
> Lint unused vars

- src/components/Player/Player.tsx
xref: https://github.com/online-go/online-go.com/issues/1629
> Use createRef for elt ref

- src/views/Play/Play.tsx
Fixes a "need unique keys" error in console.
~~Give all items in the constructed list keys.~~
Don't use an array in that place, it's not an array, it's just a list of elements.
> Construction of the rengo challenge list needed a couple more keys.

- src/components/ChallengeModal/ChallengeModal.tsx
- src/views/Game/Game.tsx
Fixes people trying to use features that don't work in rengo
Disable fork and auto handicap in the client
> Disable fork and auto-handicap for rengo games

- src/lib/cached.ts
Fixes #1513 and probably some of the excess load we sometimes saw on the
site during upgrades. Hopefully doesn't break anything.
> Fixed refresh loop that sometimes happened while loading ui/config

- .github/workflows/main.yml
Testing if I have the CI timeout setting working right
> CI timeout test

- src/components/PaginatedTable/PaginatedTable.tsx
Attempt to deal with this strict mode warning
> Don't refresh when unmounted

- src/components/NavBar/NavBar.tsx
Partially fixes #1629
Tell me if you are open to these kinds of PRs and how to coordinate on them
> NavBar.tsx: migrate notification_list to createRef

- src/components/RengoManagementPane/RengoManagementPane.styl
- src/components/RengoManagementPane/RengoManagementPane.tsx
- src/components/RengoTeamManagementPane/RengoTeamManagementPane.styl
- src/components/RengoTeamManagementPane/RengoTeamManagementPane.tsx
- src/views/Play/Play.styl
Fixes people asking for a chat channel to discuss their rengo challenge.
Wack an EmbeddedChatCard into the RengoTeamManagementPane.
Whoa, reusable component FTW!
> Add a chat channel in the management pane of rengo challenges

- src/views/Moderator/Moderator.tsx
> Add link to API to Moderator Center

- src/components/ChallengeModal/ChallengeModal.tsx
Fixes newcomers chosing strict when creating ad-hoc games
Default rengo to casual until the user selects something else
> Default rengo games to casual

- src/views/User/GameHistoryTable.tsx
- src/views/User/ModTools.tsx
- src/views/User/ReviewsAndDemosTable.tsx
- src/views/User/User.tsx
- src/views/User/common.ts
I believe the User class has some natural component boundaries where modularization would be beneficial (even though the components are not used elsewhere).  Below is a visual representation of where these boundaries are.
Fixes [one block of JSX](https://github.com/online-go/online-go.com/blob/devel/src/views/User/User.tsx#L877-L2162) being over 1000 lines long.
> User.tsx: Extract Game History tables, mod tools into separate components.

- src/components/RengoTeamManagementPane/RengoTeamManagementPane.tsx
- src/views/Play/Play.tsx
Fixes [apparent sync delay between chat panes](https://forums.online-go.com/t/rengo-status/40415/452?u=greenasjade)
Don't show the same chat pane in two places :)
> Make it so that live rengo chat appears only in the automatch container

- src/components/AutomatchSettings/AutomatchSettings.tsx
- src/components/Chat/ChatChannelList.tsx
- src/components/Chat/ChatDetails.tsx
- src/components/Chat/ChatList.tsx
- src/components/ErrorBoundary/ErrorBoundary.tsx
- src/components/GobanThemePicker/GobanThemePicker.tsx
- src/components/TimeControl/TimeControlPicker.tsx
- src/lib/data_schema.ts
- src/lib/player_cache.ts
- src/lib/preferences.ts
- src/models/challenges.d.ts
- src/models/user.d.ts
- src/views/Game/Chat.tsx
- src/views/Supporter/Supporter.tsx
- src/views/Tournament/Tournament.tsx
Add the rest of the key-type pairs for the `data.ts` functions.
> More types for data (the rest of the owl)

- src/views/Play/Play.tsx
Fixes confusion between which column is which
Make no autostart be a '-' instead of 'no
> Make no autostart be a '-' instead of 'no', for contrast with handicap

- src/components/ChallengeModal/ChallengeModal.tsx
Fixes #1697
- Set `game.width` and `game.height` in `update_board_height` and `update_board_width`
> Bugfix: custom size challenges.

- src/views/Play/Play.tsx
Fixes people complaining that the chat has gone, and that they can't view it before they join
Put rengo chat window in the challenge list instead of the automatch pane
> Make rengo challenge chat consistent

- src/models/games.d.ts
- src/views/Game/Game.tsx
Adds a type to describe the `/api/v1/games/%game_id%` endpoint.
> Add rest_api.GameDetails

- src/views/Tournament/Tournament.tsx
So I was looking at [Through the Years: Long Correspondence](https://online-go.com/tournament/59567), and thinking to myself "I'm sure we could show *something* before the whole thing loads".  Well turns out there's 3 API calls and only one of them is insanely slow - all players.
There are a lot of components that don't depend on `players`, only the tournament details, so we can load all of those first.  Between the description, the info, and the chat, it makes up almost a full page of content!
- Render description, info and chat when the details are loaded (no longer wait for `rounds`/`players`)
I made a side-by-side demo (new stuff on the left):
https://user-images.githubusercontent.com/25233703/154016273-b3fdfbbc-1091-4d11-ada5-6c6cd4d8e79b.mov
Unfortunately running both at once caused …
> Update tournaments to show details as soon as they are loaded.

- src/views/Game/Game.tsx
Fixes https://forums.online-go.com/t/rengo-status/40415/685?u=greenasjade
Check if player is in rengo black team before saying white did the pause
> Check if player is in rengo black team before saying white paused.

- src/components/GameList/GameList.tsx
- src/components/GobanLineSummary/GobanLineSummary.tsx
- src/components/MiniGoban/MiniGoban.tsx
- src/lib/types.ts
- src/models/games.d.ts
- src/views/User/User.tsx
- Remove the unused pause
- follow up on some TODOs
- Remove unused pause stuff from GobanLineSummary and MiniGoban
- Merge the state types for GobanLineSummary and MiniGoban
- Remove unused refs in User
- Simplify GameList call in User
> User/GameList: general cleanups

- src/components/RengoManagementPane/RengoManagementPane.tsx
- src/lib/rengo_balancer.ts
- src/views/Play/Play.tsx
- Adds button for organizer to unassign players from rengo teams
- Clicking the button again reassigns players in approximately balanced teams
> Rengo team balance button in rengo management pane

- src/models/user.d.ts
- src/views/User/User.tsx
- src/views/User/VersusCard.tsx
I thought it would make sense to gather the `vs`-related code together in one component.  Currently, the logic is split across `update()` and `render()`.  Now, there is no `vs` logic in `update`, and the JSX in `User.render()` is simpler.
- Create `VersusCard` component
- Add `PlayerDetails` to `rest_api` types
> User.tsx: Move vs stuff into its own component

- src/views/User/User.tsx
A little more User.tsx cleanup
Tested: Ocular pat-down of https://online-go.com/player/1 and http://localhost:8080/player/1.  Look the same afaict.
> Remove unused property state.ranks.

- package.json
- src/components/Player/Player.tsx
- src/views/User/AvatarCard.tsx
- src/views/User/User.tsx
- yarn.lock
- Move Avatar into its own component
- Some additional code cleanups
- Remove unused timeout_provisional code
- Strict mode compliance
- added react-dropzone type (bumping to current version would also work, but I couldn't test this so left that for another day.)
- Default to https for websites where the URL is not specified.
- Fix bug where vacation time takes a second to show up
- Fix bug where missing bot_owner caused page to crash (thanks for reporting, @shinuito!)
> User.tsx: move Avatar into its own component

- src/views/User/User.tsx
- Remove class properties that were either unused, or set but not read
- Remove class methods that weren't used
- Many of these functions were moved into PlayerDetails popup, but never removed from User.tsx
- I'm guessing the superUser stuff was moved into ModerateUser modal (ps ~no more~ less jQuery!!)
> Cleanup: Remove unused properties and methods.

- src/views/User/User.tsx
Removing 200+ lines of code, mostly JSX.
> Remove unused ip widget

- src/views/Game/Chat.tsx
This is a types only change, so should have no effect on functionality (or even generated code)
> More typing in Chat.tsx

- src/components/ChallengeModal/ChallengeModal.tsx
- src/components/Chat/ChatLog.tsx
- src/components/Chat/ChatUsersList.tsx
- src/components/IncidentReportTracker/IncidentReportTracker.tsx
- src/components/Notifications/Notifications.tsx
- src/components/ObserveGamesComponent/ObserveGamesComponent.tsx
- src/components/Player/PlayerDetails.tsx
- src/components/PrivateChat/PrivateChat.tsx
- src/components/SeekGraph/SeekGraph.tsx
- src/components/UIPush/UIPush.tsx
- src/lib/ITC.ts
- src/lib/automatch_manager.tsx
- src/lib/bots.ts
- src/lib/chat_manager.ts
- src/lib/configure-goban.ts
- src/lib/data.ts
- src/lib/online_status.ts
- src/lib/sockets.ts
- src/main.tsx
- src/views/Admin/Admin.tsx
- src/views/Game/Game.tsx
- src/views/Game/GameLogModal.tsx
- src/views/docs/About.tsx
Rename `termination_socket` and `comm_socket` to `socket`.  Since they are the same:
https://github.com/online-go/online-go.com/blob/052321f1415044e6c2cc59e07b66f981f346942b/src/lib/sockets.ts#L46
this does not constitute a functional change, but it will be more clear to anyone not familiar with the sockets.
Tested: while I'm sure I can't test every socket call on the site, it looks like I get the usual socket traffic:
And I tried a few socket-y things like playing a move in a game and sending a PM.
> Rename termination_socket and comm_socket to socket.

- src/components/ChallengeModal/ChallengeModal.styl
- src/components/ChallengeModal/ChallengeModal.tsx
Fixes people complaining that they don't know what casual mode is
Put a (?) link next to the casual mode check box, taking them in another tab to doco.
> Rengo help link

- src/models/user.d.ts
- src/views/User/ActivityCard.tsx
- src/views/User/AvatarCard.tsx
- src/views/User/BotControls.tsx
- src/views/User/User.tsx
This one is a little bigger than previous ones.  I was trying to do everything that would make incrementally loading the profile page easier. Please let me know if I should break this up into separate PRs.
- Remove the update function: most of it was not necessary except for the `setState` call
- Factor out a few more components:
- Activities
- Bot Management
- deleted `syncRating()` as it was unused
- add types for selected size and speed
- add UserProperties and UserState as parameter for the props functions
- fix ts "strict" errors.  The biggest one here was strictNullChecks
> User.tsx refactorings

- doc/clock_system.md
- package.json
- src/components/AutoTranslate/AutoTranslate.tsx
- src/components/Clock/Clock.styl
- src/components/Clock/Clock.tsx
- src/lib/cached.ts
- src/lib/sockets.ts
- src/views/Appeal/Appeal.tsx
- src/views/Game/AIReview.tsx
- src/views/Game/CountDown.tsx
- src/views/Game/Game.tsx
- yarn.lock
This PR mostly tracks the goban PR https://github.com/online-go/goban/pull/66 which implements a more reliable clock system, enabling down to the wire moves safely.
> Reliable clock

- package.json
- src/components/JosekiStatsModal/JosekiStatsModal.tsx
Fixes react-charts being on an old version
Move react-charts to 3.x.
> OJE react charts 3.0

- package-lock.json
Fixes build breaking
Update package-lock to match previous commit
> npm run with package-lock generated

- src/main.tsx
- src/routes.tsx
Fixes "Links won't navigate (until I press reload)"
https://github.com/remix-run/react-router/issues/7870#issuecomment-1099884642
> Put <React.Strict> inside <Router> so that links work.

- src/components/PaginatedTable/PaginatedTable.tsx
Fixes noise in console.
Delete log()
> React18 quiet paginated table

- src/components/RengoTeamManagementPane/RengoTeamManagementPane.tsx
Fixes the nagging feeling that I should have done this in the first place.
Give moderators a dialog to confirm they want to kick the person from all rengo challenges.
> provide a warning saying what kick is about to do.

- src/components/Notifications/NotificationManager.tsx
... after a move is played
Fixes people (rightly) [complaining that the behaviour changed](https://forums.online-go.com/t/changed-behavior-of-black-circle-your-move-button/42937/14?u=greenasjade).
Make it so that if we played a move in a correspondence game and auto-advance, then we advance to the next least urgent.
In live, the new behaviour remains, which is that after playing a move with auto-advance turned on, the most urgent move will be selected (as per forum, there is some debate about this).
> Made it so that correspondence games still go to the next least urgent

- src/components/ChallengeModal/ChallengeModal.tsx
Fixes #1707 
- Add type definition for `ChallengeModal.props.config`
- Move `challenger_color` from `challenge.game.challenger_color` to `challenge.challenger_color`
- Reconcile conflicts in typings
> Set correct challenger color in ChallengeModal

- .eslintrc.js
- src/components/GameList/GameList.tsx
- src/components/GobanLineSummary/GobanLineSummary.tsx
- src/components/Player/Player.tsx
- src/lib/rank_utils.test.ts
- src/lib/rank_utils.ts
- src/models/challenges.d.ts
- src/models/user.d.ts
- src/views/Play/Play.tsx
- src/views/User/User.tsx
- Fully type all exported function signatures.
- Add unit tests for exported functions.
- Add JSDoc for exported functions.
> rank_utils: types, docs, and unit tests

- src/views/Game/PlayControls.tsx
Fixes #1834 
Fixes #1835
Fixes [Missing grant undo button](https://forums.online-go.com/t/cant-find-grant-undo-button/43124/7)
- Don't show `PlayButtons` if user is not a participant.
- Set initial state from Goban in `useState` calls.
> Fix resize, undo bugs

- src/components/JosekiTagSelector/JosekiTagSelector.tsx
- src/components/JosekiVariationFilter/JosekiVariationFilter.tsx
- src/views/Joseki/Joseki.tsx
Fixes tags not being able to be translated
Ask the translators to translate using `try { _("tag")}` trick from @benjaminpjones , use these translations.
(This PR coming to you from the Queensland Hinterland, after a day of dodging leeches snakes and poisonous plants :D )
> Oje tag i18n

- .eslintrc.js
- package.json
- src/components/Chat/ChatLog.tsx
- src/views/Firewall/Firewall.tsx
- src/views/Game/GameDock.tsx
- src/views/Game/PlayControls.tsx
- src/views/Game/PlayerCards.tsx
- src/views/Supporter/Supporter.tsx
- yarn.lock
- Add the `react-hooks` eslint plugin, and turn on the `rules-of-hooks` rule.
- Fix the resulting errors.
Discussion on #1836
> Add react-hooks/rules-of-hooks lint check.

- src/views/Game/PlayControls.test.tsx
This gives us a bit of coverage for the bugs addressed in #1836
In a previous PR, I only tested existence/absence of the "Resign" button.  These additions test the Undo and Pass buttons as well.
> Add more tests for the play buttons.

- src/components/JosekiAdmin/JosekiAdmin.tsx
- src/components/JosekiTagSelector/JosekiTagSelector.tsx
- src/views/Joseki/Joseki.tsx
- yarn.lock
Fixes patchy translation of OJE
Force-translate `MoveCategory`s, and apply translations to everything that needs to be translated.
> Translated `MoveCategory`s, and a bunch of missed/bugged other translations

- src/components/Notifications/Notifications.tsx
- src/lib/misc.ts
Fixes #1850 
- use a lightly wrapped `durationString()` in Notifications.tsx
- delete buggy `formatTime()` function from misc.tsx
> Just use TimeControl's durationString() in Notifications.tsx.

- src/components/ChallengeModal/ChallengeModal.styl
- src/components/ChallengeModal/ChallengeModal.tsx
Fixes tricksy people trying to see what happens if illegal values of auto_start are used
Validate so they can't enter illegal values.
Also, make the display of "no autostart" be "blank" not "0", lest someone raise the concern that "hey, this is going to auto start immediately!?"
> Validation of rengo auto-start

- src/components/Report/Report.tsx
Another thing that seemed easy to try. 
Usually people who leave games are reported on "game stalling" but I think they are two different things.
> New report category

- src/views/Game/GameDock.tsx
> Fix Original Game link missing from reviews.

- .vscode/extensions.json
For the folks who use VSCode, the extensions will show up as recommended.
https://dev.to/askrishnapravin/recommend-vs-code-extensions-to-your-future-teammates-4gkb
> Add VSCode extensions.json

- src/views/Game/Game.tsx
- src/views/Game/GameHooks.ts
Fixes #1876
This is a quick fix that should be revisited in the morning, it's not clear to me why recomputing the score fixes #1876 but it does seem to work around the issue if nothing else. 
Tagging @benjaminpjones in case you have any ideas before I get to diving deeper into it.
> Quick fix for AI based off of @mmartin's patch

- Gulpfile.js
- src/lib/data_schema.ts
- src/routes.tsx
Fixes small chance of developer confusion
Comment, function name change, de-dupe data schema, typo fix.
> Teensy tidy

- src/index.html
Fixes slightly jerky feel of bouncing loader.
Smooth around the edges.
I plan to have this thing (or a smaller version) showing while the linked-challenge details are fetched, so it will be seen slightly more.
> Teensy smoothing on loading bouncer movement

- src/views/docs/GoResources.tsx
Verified locally that the changes work.
> Add link to Ukrainian Go Federation

- src/views/Game/AIReview.tsx
- src/views/Game/Game.tsx
- src/views/Game/GameChat.tsx
- src/views/Game/GameDock.tsx
- src/views/Game/PlayButtons.test.tsx
- src/views/Game/PlayButtons.tsx
- src/views/Game/PlayControls.test.tsx
- src/views/Game/PlayControls.tsx
- src/views/Game/PlayerCards.tsx
- src/views/Game/game_control.ts
- src/views/Game/goban_context.ts
Probably as good a time as any to introduce this change :)
Design doc: [Goban Centric Components: GobanContext](https://docs.google.com/document/d/1viy_xeQbEZ4_N6SOQll2R4vMRDjxhDz5-wMdG7GtnHI/preview#heading=h.88bu2pc5ok8r)
- Created `GobanContext` and helper hook `useGoban`.
- Used the `GobanContext` in most of the sub-components of Game.tsx.
- Updated tests.
> GobanContext

- src/components/SocialLoginButtons/SocialLoginButtons.styl
- src/components/SocialLoginButtons/SocialLoginButtons.tsx
- src/components/SocialLoginButtons/index.ts
- src/views/Register/Register.styl
- src/views/Register/Register.tsx
- src/views/Settings/Settings.tsx
- src/views/SignIn/SignIn.styl
- src/views/SignIn/SignIn.tsx
Fixes inconsistent appearance and flow.
Factored out SocialButtons, aligned styles and layout.
> Converge signin and registration

- src/templates/component/TemplateComponent/TemplateComponent.styl
- src/templates/component/TemplateComponent/TemplateComponent.tsx
- src/templates/component/TemplateComponent/index.ts
Fixes "darn, now how do I do this again?"
Add a 'templates' directory and wack an example component in it with various things that we always need.
> Added a component template

- src/components/MiniGoban/MiniGoban.tsx
- src/routes.tsx
- src/views/Game/GameLinkModal.tsx
- src/views/GameEmbed/GameEmbed.styl
- src/views/GameEmbed/GameEmbed.tsx
- src/views/GameEmbed/index.ts
Fixes #893 
- Put a MiniGoban at online-go.com/game/%%/embed
- Add sample iframe code to the game links
> Embeddable games

- src/views/Settings/Settings.tsx
Fixes typo
permanant -> permanent
> Fixed typo in warning message

- src/components/ChallengeDetailsReviewPane/ChallengeDetailsReviewPane.styl
- src/components/ChallengeDetailsReviewPane/ChallengeDetailsReviewPane.tsx
- src/components/ChallengeDetailsReviewPane/index.ts
- src/components/GameAcceptModal/GameAcceptModal.tsx
Fixes need for a pane to display challenge details in different places
Factor out challenge details review pane from GameAcceptModal.
> Factor out ChallengeDetailsReviewPane from GameAcceptModal 

- src/views/Settings/LinkPreferences.tsx
- src/views/User/User.tsx
https://forums.online-go.com/t/add-badukpop-to-the-list-of-linked-accounts/42996
I hope it works :)
> Add BadukPop to the list of linked accounts

- src/components/ChallengeModal/ChallengeModal.tsx
- src/components/NavBar/EXV6NavBar.tsx
See https://github.com/online-go/online-go.com/issues/1918, it should work.
There are also three commits that cancel each other out. I realized late that "demo board" was on "tool" and couldn't delete the commits and I couldn't find a way to send just one. 
(If those 3 commits are a problem tell me how I can solve it please. Maybe with a new repository?)
> Remove "Invite only" from demo creation modal

- src/components/GameList/GameList.tsx
- src/components/GobanLineSummary/GobanLineSummary.tsx
- src/models/games.d.ts
Fixes #1925. Also fixes how rengo games are displayed in the GameList.
- Fix GameData type
- Add `rengo_teams` to `GobanLineSummaryProps`
- Fix calculation of player color in GobanLineSummary
> Fix list of active games

- src/views/Settings/Settings.tsx
Somehow this snuck in with #1912
> Remove unused "Help Settings"

- src/components/NavBar/NavBar.tsx
- src/views/HelpFlows/GuestUserIntroEXV6.tsx
- src/views/HelpFlows/GuestUserIntroOldNav.tsx
- src/views/HelpFlows/HelpFlows.tsx
This adds the "guest intro" flow for the old nav system.
Add a new flow, and factor both flows out into their own components.
Now the old nav flow is turned on by default, for debugging.
Visual stuff (better placement, colour, proper connection to guest-arrival) still coming.
> Add guest rdh for old nav

- src/components/PlayerAutocomplete/PlayerAutocomplete.tsx
- Turn off autocapitalize in PlayerAutocomplete input.
> Don't autocapitalize username in player invite input

- package.json
- src/components/NavBar/EXV6NavBar.styl
- src/components/NavBar/EXV6NavBar.tsx
- src/components/NavBar/NavBar.tsx
- src/components/PlayerAutocomplete/PlayerAutocomplete.tsx
- src/lib/data_schema.ts
- src/lib/preferences.ts
- src/main.tsx
- src/ogs.styl
- src/views/ChallengeLinkLanding/ChallengeLinkLanding.tsx
- src/views/HelpFlows/GuestUserIntroEXV6.tsx
- src/views/HelpFlows/GuestUserIntroOldNav.tsx
- src/views/HelpFlows/HelpFlows.styl
- src/views/HelpFlows/HelpFlows.tsx
- src/views/HelpFlows/index.ts
- src/views/Overview/Overview.tsx
- src/views/Settings/AccountSettings.tsx
- src/views/Settings/HelpSettings.tsx
- src/views/Settings/Settings.styl
- src/views/Settings/Settings.tsx
- src/views/User/AvatarCard.tsx
- src/views/User/User.tsx
- yarn.lock
- Merge react-dynamic-help branch, which brings help popups for guest users.
> Add help for guest users

- src/components/LadderComponent/LadderComponent.tsx
- src/components/NavBar/EXV6NavBar.styl
- src/components/NavBar/EXV6NavBar.tsx
- src/components/NotificationIndicator/NotificationIndicator.styl
- src/components/NotificationIndicator/NotificationIndicator.tsx
- src/components/TurnIndicator/TurnIndicator.styl
- src/components/TurnIndicator/TurnIndicator.tsx
- src/lib/preferences.ts
- src/ogs.styl
- src/views/GroupList/GroupList.styl
- src/views/GroupList/GroupList.tsx
- src/views/HelpFlows/HelpFlows.styl
- src/views/LadderList/LadderList.styl
- src/views/LadderList/LadderList.tsx
- src/views/TournamentList/TournamentList.styl
- src/views/TournamentList/TournamentList.tsx
This PR addresses a number of feedback points that came back from the community. Some of the feedback items, such as removing the tournament, group, and ladders from the nav bar have some fallout (namely that we now need a place to store those, since we're removing them from the home screen).
> New nav bar updates and fallout from the changes

- src/components/NavBar/EXV6NavBar.tsx
Fixes developers cursing the original author
Improve the comment relating to `show_signin`
> Improve explanation of `show_signin` (non-functional change)

- src/components/NavBar/EXV6NavBar.tsx
Fixes link to sign-in page showing up on the sign-in page.
Don't show the link to the sign-in page when on the sign-in page.
> Signin link tidyup

- package.json
- src/lib/data.ts
- src/lib/data_schema.ts
- src/main.tsx
- src/views/ChallengeLinkLanding/ChallengeLinkLanding.tsx
- src/views/HelpFlows/GuestUserIntroEXV6.tsx
- src/views/HelpFlows/HelpFlows.tsx
- src/views/Settings/AccountSettings.tsx
- src/views/Settings/HelpSettings.tsx
- yarn.lock
Fixes [activated flows from a  logged out user flowing into next user to log in](https://forums.online-go.com/t/preview-beta-test-popup-help-for-new-users-challenge-link-guests/44310/3?u=greenasjade)
Reset the help flows upon logout (specifically, when it's detected that the config.user is anonymous).
Needs rdh 2.1.5, for lots of stuff.
Needs https://github.com/online-go/ogs-node/pull/17 for "remote_storage_sync_complete"
> Reset help flows when the person logs out

- src/views/Game/PlayControls.tsx
Fix capitalisation consistency on `Accept Conditional Moves` button.
> Capitalisation consistency

- src/views/docs/legal.tsx
Another silly thing, I found it strange that some sentences ended with a period and some didn't. 
Maybe ";" could be better but I didn't feel like twisting things too much. Maybe it's not even wanted. 
(Again two empty commits, I did something wrong and can't get rid of them.  Sorry)
> Update legal.tsx 

- src/components/RengoTeamManagementPane/RengoTeamManagementPane.tsx
Fixes future ugliness using context in class based components: it's easier to add rdh to function components.
Convert to function component.
> Converted RengoTeamManagementPane to a function component.

- src/components/RengoManagementPane/RengoManagementPane.tsx
Fixes future ugliness when adding rdh context
Convert RengoManagementPane to be a function component.
> Converted RengoManagementPane to a function component

- src/components/ChallengeLinkButton/ChallengeLinkButton.tsx
- src/views/Overview/ChallengesList.tsx
- src/views/Overview/InviteList.tsx
Fixes confusion about what the text is in the top left of an invite card
Put the game name in quotes:
> Put the game name in quotes so it is clear that it is a name

- src/components/Chat/ChatDetails.styl
- src/components/Chat/ChatDetails.tsx
> Chat notification settings

- src/lib/ogs-rr6-shims.tsx
- src/views/Game/PlayControls.tsx
- src/views/Tournament/Tournament.tsx
- src/views/TournamentRecord/TournamentRecord.tsx
This is going to finally eliminate the need for the rr6ClassShim hack that we put in when we updated to react router 6. This shim is causing some problems that are affecting a number of people, so seems best to just try and eliminate it.
> Convert remaining main views from class views to functional components

- src/views/Game/PlayerCards.tsx
> Only hide # captures when points are shown and score estimator is not active

- package.json
- src/components/OgsHelpProvider/OgsHelpProvider.tsx
- src/lib/data_schema.ts
- src/views/ChallengeLinkLanding/ChallengeLinkLanding.tsx
- src/views/Game/Game.tsx
- src/views/HelpFlows/HelpFlows.tsx
- src/views/Overview/EXV6Overview.tsx
- src/views/Overview/Overview.tsx
- src/views/Play/Play.tsx
- yarn.lock
Fixes  existing users seeing help prompts when they accept challenge links
- Use `data` instead of UrlParam to track what's going on through challenge link registration
- Take advantage of RDH 2.6.0 to trigger login-time help flows in one place only
** Needs RDH 2.6.0
> Dont show new user challenge link help to existing users

- Gulpfile.js
This just adds a small wrapper which stops the proxy from parsing the request body when uploading files.
See [this issue](https://github.com/villadora/express-http-proxy/issues/127) for more details.
> Fix file uploads when using the dev server

- src/views/HelpFlows/GuestUserIntroEXV6.tsx
- src/views/HelpFlows/GuestUserIntroOldNav.tsx
- src/views/HelpFlows/GuestUserIntroRengo.tsx
- src/views/Settings/GeneralPreferences.tsx
Fixes https://forums.online-go.com/t/ogs-translation-pootle-and-stuff/45110/10?u=greenasjade
Add translation function for these strings.
> Translate help flow descriptions

- CONTRIBUTING.md
Fixes #2034
- Adds Git LFS installation link in CONTRIBUTING.md
- Fix minor casing in copy
> Fix #2034: Add Git LFS instruction to CONTRIBUTING.md

- src/components/TimeControl/TimeControlPicker.tsx
I was digging around in `ChallengeModal`/`TimeControlPicker` and thought it might be easier to code in here if we have stronger types.  This PR *should* only be types, no changes to the JavaScript output.
- Add (most) types that are necessary when `noImplicitAny` and `strictNullChecks` are on
- Add some comments about what still needs to be fixed.
> Add types to TimeControlPicker.

- src/models/online-league.d.ts
- src/routes.tsx
- src/views/ChallengeLinkLanding/ChallengeLinkLanding.tsx
- src/views/OnlineLeagueGame/OnlineLeagueGame.styl
- src/views/OnlineLeagueGame/OnlineLeagueGame.tsx
- src/views/OnlineLeagueGame/index.ts
- src/views/OnlineLeagueLanding/OnlineLeagueLanding.styl
- src/views/OnlineLeagueLanding/OnlineLeagueLanding.tsx
- src/views/OnlineLeagueLanding/index.ts
Fixes having nothing to show yet :)
Routes and view to support the URLs that we provide to online leagues.   They don't _do_ anything, but they do at least display a page.
Requires backend update: https://github.com/online-go/ogs/pull/1754
> Online league support

- .husky/post-checkout
- .husky/post-commit
- .husky/post-merge
- .husky/pre-push
After running commands in https://github.com/online-go/online-go.com/blob/devel/CONTRIBUTING.md
I got 4 new files.
Not sure what to do:
1. remove them and change husky settings
2. add them to .gitignore
3. merge them to `devel` branch
> chore: add npx husky result with git-lfs

- src/views/User/VersusCard.tsx
Fixes #2069 
- Fixed user name overflowing issue when it gets too long at VersusCard component
> bugFix: fixed VersusCard component user name overflowing issue

- src/views/Joseki/Joseki.styl
- src/views/Joseki/Joseki.tsx
Use the `see_also` field from the server to tell users that there are other identical positions in OJE
Needs https://github.com/online-go/ogs/pull/1768
> Add display of "See also" info in OJE

- package.json
- yarn.lock
Fixes #2086 
The real changes are in the goban library here: https://github.com/online-go/goban/pull/108
> Goban bump to fix slow stone group toggling in stone removal phase

- src/views/docs/GoResources.tsx
DM request from site owner.
FB page is closed, link to webpage instead.
> PacifiGo Link Update

- src/views/docs/GoResources.tsx
> Vladislav Vinokurov YT link update

- src/components/NavBar/NavBar.styl
- src/components/NavBar/NavBar.tsx
This changes the right drop down menu to work on hover instead of clicking it
This only applies to desktop, in mobile mode it presents an icon that is clickable as before
> Made right navbar drop down a hover drop down like the rest of the menu items

- src/components/IncidentReportTracker/IncidentReportTracker.tsx
Fixes fascinating link that does nothing appearing for users.
> Show report centre link to moderators only

- Gulpfile.js
Also add some error logging that will hopefully help narrow down why ogs.js isn't being served correctly out of the docker image run by uffizzi
> Add special case for serving out of Uffizzi

- src/components/Achievements/AchievementList.styl
- src/components/Achievements/AchievementList.tsx
- src/views/docs/GoResources.tsx
Fix book title broken by commit 2ccee72a3ce88bd0d1321687306b4983dacf00b1
> Fix removed years caught up in copyright change

- src/components/Chat/ChatLog.tsx
- src/lib/data_schema.ts
- src/models/onlineleague.d.ts
- src/views/HelpFlows/HelpFlows.tsx
- src/views/HelpFlows/OOLUserIntro.tsx
- src/views/OnlineLeagueLanding/OnlineLeagueLanding.styl
- src/views/OnlineLeagueLanding/OnlineLeagueLanding.tsx
As requested by NAGF.
Now the players arrive at the landing page to find a chat channel, and a button they can use to say that they are definitely ready to play now.
When both players have pressed the button (and neither player cancels) the game starts.
> OOL Meet then play support on the OOL Landing Page.

- src/views/Game/PlayControls.tsx
Fixes #239 and https://forums.online-go.com/t/could-we-go-straight-from-analyse-to-plan-conditional/12605?u=turtoise
- Adds a button that copies the selected analysis branch to the conditional move planner
> Copy analysis branch to conditional move planner

- src/views/ReportsCenter/ViewReport.tsx
Fixes potential confusion about who did what
Say "reported by" instead of "reporting user"
> Say "reported by" instead of "reporting user"

- src/views/Puzzle/Puzzle.styl
- src/views/Puzzle/Puzzle.tsx
- Added click on "correct" for this issue https://github.com/online-go/online-go.com/issues/2072
> Added click on "correct" for Puzzle component

- src/views/HelpFlows/OOLSpectatorIntro.tsx
- src/views/HelpFlows/OOLUserIntro.tsx
Fixes: Noisey help flow messages
Turn off component debug
> Turn off debug in OOL Help Flow components

- src/views/Game/PlayerCards.tsx
I thought declaring the `get` as void would basically quiet everything, but apparently not, so at least now it says in the console what's going on.
> Say in the console why we are getting 400 from the server

- .github/workflows/main.yml
It's not working on forks (that was the whole point!) will look into it later
> Suppress wearerequired/lint-action

- src/views/OnlineLeaguePlayerLanding/OnlineLeaguePlayerLanding.test.tsx
- src/views/OnlineLeaguePlayerLanding/OnlineLeaguePlayerLanding.tsx
Mock UIPush and set effect of calling the appropriate action.
Note: it seems like the UIPush mock could be a handy component, but factoring that out is a future exercise, because it wasn't as easy as it seemed like it should be.
> Test incoming server UI push effect

- src/views/Game/GameDock.tsx
Fixes folk clicking on fork and wondering why nothing happens 😅
Match display logic to functional logic.
> Show the Fork button disabled in analysis disabled games in play.

- CONTRIBUTING.md
Fixes Windows developers struggling to get started.
Add a tried / tested detailed process for getting development environment up on Windows.
> Windows dev detailed steps

- Makefile
- package.json
- src/components/AIReviewStream/AIReviewStream.tsx
- src/components/ChallengeModal/ChallengeModal.tsx
- src/components/Chat/ChatUsersList.tsx
- src/components/Notifications/NotificationManager.tsx
- src/components/ObserveGamesComponent/ObserveGamesComponent.tsx
- src/components/PrivateChat/PrivateChat.tsx
- src/components/SeekGraph/SeekGraph.tsx
- src/lib/ITC.ts
- src/lib/automatch_manager.tsx
- src/lib/chat_manager.ts
- src/lib/data.ts
- src/lib/data_schema.ts
- src/lib/online_status.ts
- src/lib/report_manager.ts
- src/lib/sockets.ts
- src/main.tsx
- src/views/Admin/Admin.tsx
- src/views/Game/PlayButtons.tsx
- src/views/SignIn/SignIn.tsx
- src/views/docs/About.tsx
- yarn.lock
This PR is a work in progress as we migrate from using socket.io to communicate to the server to GobanSocket, which will give us type checked direct websocket based communications to the server.
> Switch from socket.io to GobanSocket

- src/views/Game/GameDock.tsx
Fixes users not being able to use the call moderator button, due to only anonymous users being allowed.
Allow non-anonymous users to use call moderator 😝
> Fix call moderator logico

- src/views/ReportsCenter/MessageTemplate.tsx
Fixes missing templates
Put in Mark's suggestions, with added newlines and slight edits
Needs #2222
> Added in Mark5000 moderator templates (with tweaks)

- src/components/AccountWarning/AccountWarning.styl
- src/views/ReportsCenter/MessageTemplate.tsx
Fixes having to type undo harrasment warnings
- Add a Harrasment class of warning, with an undo-harrasment message
Needs #2222
> Added undo-harrasment warning

- src/views/Game/Game.tsx
> Issue #1449: Span elements to button

- src/views/ReportsCenter/MessageTemplate.tsx
Fixes need to manually tweak :)
-  Talk about chatban not ban
- Elaborate on cancellation
> Minor template tweaks

- src/components/Report/Report.tsx
Fixes having to raise a report then warn from there.
- Add moderator-only category of reports
- Add "warning" category
- Send the warning instead of filing a report, for "warning" category
> Add a class of report as a way for a moderator to warn someone directly

- src/components/AnnulQueueModal/AnnulQueueModal.styl
- src/components/AnnulQueueModal/AnnulQueueModal.tsx
- src/components/AnnulQueueModal/index.ts
- src/components/PaginatedTable/PaginatedTable.styl
- src/components/PaginatedTable/PaginatedTable.tsx
- src/views/User/GameHistoryTable.tsx
- adds selection mode to game history table, which adds games to an annulment queue
- adds modal for inspecting games within the queue
- passes array of ranked, non-annulled games to back end for annulment. 
~I've also written a draft of usage documentation for the forums that I can send if the screenshots and info there would be useful.~ That was before I saw the Uffizzi thing. How neat! Certainly a lot better than screenshots.  :)
> Mass annul

- src/views/ReportsCenter/ReportsCenterHistory.styl
- src/views/ReportsCenter/ReportsCenterHistory.tsx
- Adds a PlayerAutocomplete above the reports history table that filters the table by reporting user
> add filter for reporting user to report history table

- src/views/ReportsCenter/MessageTemplate.tsx
Fixes typing stuff about chatban every time
Added chat ban response messages
> Added messages for reporters about their chat abuse cases

- CONTRIBUTING.md
Fixes chance of confusion
Note in the header that the instructions are Windows
Get rid of comment that snuck in from draft.
> Slight clarification about windows instructions

- src/views/Game/PlayerCards.test.tsx
Fixes there being truly minimal testing
Add another test :)
> Make sure black player card doesn't get komi

- src/views/ReportsCenter/MessageTemplate.tsx
Fixes typing about cancel
Add cancel templates.
> Mod templates about cancel

- src/views/ReportsCenter/MessageTemplate.tsx
Fixes typing "no AI detected"
Add no AI use detected
Put "don't file dupes" under "Chastise"
> Added no AI use template, and tidied up a little

- src/views/ReportsCenter/ReportsCenter.styl
- src/views/ReportsCenter/ViewReport.tsx
Fixes accidentally closing a report after claiming it
Move action buttons for when a report is claimed over to the right.
> Moved "claimed actions" away from the place where the "claim" button is

- src/views/ReportsCenter/MessageTemplate.tsx
Fixes terse warning
Be more appreciative.
> Politer dupe reports warning

- src/views/ReportsCenter/MessageTemplate.tsx
Fixes warning sent confirmatio alert getting in the way
Make that a toast
> Changed warning sent confirm to a toast

- src/components/Dock/Dock.styl
Fixes scrambled dock layout in mobile
Apply the needed flex properties to Dock children.
> Fix Dock layout for mobile

- CONTRIBUTING.md
- src/lib/preferences.ts
- src/views/Game/AIReview.tsx
- src/views/Settings/GamePreferences.tsx
Fixes #2248 
Extra setting in GamePreferences.tsx and in preferences.ts
New function to limit moves shown in AIReview.tsx
Few tweaks to CONTRIBUTING.md
-
-
-
> Issue 2248 - AI variation max moves

- src/views/ReportsCenter/MessageTemplate.tsx
Fixes editing the "please resign" template
Add a template for users who escape before the game starts
> "Please cancel" template

- src/views/User/ModTools.tsx
Fixes loading moderator centre and searching
Link to moderator details api from moderator table in profile
> Easier player details for moderator

- package.json
- src/views/Game/PlayControls.test.tsx
- src/views/Game/PlayControls.tsx
- src/views/HelpFlows/HelpFlows.tsx
- src/views/HelpFlows/UndoIntro.tsx
- yarn.lock
Fixes people not knowing that they're not supposed to hassle people about undos.
Pop up a message when someone first encounters "undo", letting them know:
**: Note: rdh library version update required (added `hideOptOut` option, because I feel like I don't want people irritatedly turning off rdh just because they don't agree with our undo policy)
> Undo dynamic help note

- src/components/ChallengeModal/ChallengeModal.tsx
- src/components/Errcode/Errcode.tsx
- src/components/NavBar/NavBar.tsx
- src/components/PrivateChat/PrivateChat.tsx
- src/views/Appeal/Appeal.tsx
- src/views/Moderator/ban_functions.tsx
- src/views/ReportsCenter/MessageTemplate.tsx
Fixes a sense of unease about banning people.
Well, probably doesn't "fix" it per-se, but moderators agree it reflects the intent better.
Say "your account has been suspended" rather than "you have been banned", where possible.
> Terminology around "ban".

- src/views/Game/AIReview.tsx
- src/views/Game/GameDock.tsx
Fixes dismissing an alert.
toast instead of alert for "analysis started"
> Show a toast instead of an alert for "Analysis started"

- src/views/User/User.tsx
Temporary fix while main site is under upgrades to fix rank links.
https://forums.online-go.com/t/updating-aga-rating-linkage/48338?u=bhydden
> Update US rank search

- src/views/Firewall/Firewall.styl
Fixes truncated notes in firewall rule table
- Make notes expand to fill the space
Slightly ugly with the underline, but hey it's a header :)
> Make sure there is ample room to display notes.

- src/views/Game/GameTimings.tsx
Fixes ugly composite type noise
- Use the `GobanMovesArray` type introduced in https://github.com/online-go/goban/pull/124
Note: Built on top of #2317  (refactor of GameTimings)
> Use new proper goban engine moves type

- src/views/Game/GameTimings.tsx
Fixes out of date implementation.
Convert `GameTiming` to be a function component.
> GameTiming function component refactor

- src/views/Game/GameTimings.styl
- src/views/Game/GameTimings.tsx
Fixes  squinting at the table to see if there are any minute timings.
Highlight times that are minutes, not seconds.
This is built on #2317
> Highlight minute timings

- src/views/User/ModTools.tsx
Fixes ... remains to be seen.
- Call that narrow column Shared BIDs instead of BID Alias
> Try to make bid_match column clearer in as few words as possible

- src/views/ReportsCenter/MessageTemplate.tsx
Fixes beginners getting "warned" when they just need "advice"
Suggest they ask for help rather than tell them they'll get suspended.
> Softened endgame stalling template for beginners

- src/components/AnnulQueueModal/AnnulQueueModal.tsx
Fixes laboriously moving the mouse across the screen to step then dequeue then step
Have a "Next" button next to the "Dequeue" button so a small mouse movement can chose between those.
> Add a "Next" button to AnnulQueueModal

- src/views/ReportsCenter/MessageTemplate.tsx
Fixes typing that message.
Add template about don't hassle opponent
> Added "don't hassle about AI" template.

- src/views/Game/PlayControls.tsx
Fixes #1923
Keep track of whether we're in sync as per the solution recommended in #1923
> Mousing over a variation name does not put us in sync

- src/views/Game/PlayControls.tsx
- src/views/Play/Play.tsx
Fixes people accidentally deleting rengo challenges
Add an alert to confirm deletion of rengo challenge
> Confirm dialog for rengo challenge delete

- src/lib/cached.ts
Fixes #2302
It's late and this is not vetted, I feel like this shouldn't be necessary so I think before merging I'd like to understand why this seems to be necessary. A better fix might exist.
> Set user and config.user when we get ui/config results

- package.json
- src/components/AIReviewStream/AIReviewStream.tsx
- src/main.tsx
- src/views/Game/AIDemoReview.tsx
- src/views/Game/Game.tsx
- src/views/Game/GameDock.tsx
- yarn.lock
This is the client portion of adding support for AI analysis to be run by a controller of a game review or demo board.
> AI analysis support for reviews and demo boards

- src/components/NetworkStatus/NetworkStatus.styl
- src/components/NetworkStatus/NetworkStatus.tsx
- src/components/NetworkStatus/index.ts
- src/lib/sockets.ts
- src/ogs.styl
- src/routes.tsx
Fixes not noticing that there's a problem with the socket to OGS
- Display a flashing icon if we've lost contact (ping timeout or disconnect)
** needs https://github.com/online-go/goban/pull/130
> Network out notifier

- src/components/NetworkStatus/NetworkStatus.styl
- src/components/NetworkStatus/NetworkStatus.tsx
Fixes petty nit picking :D
(tweak while pondering tracking slow internet)
> rounded corners, enum for state, comment update

- src/components/NetworkStatus/NetworkStatus.styl
- src/components/NetworkStatus/NetworkStatus.tsx
- src/lib/sockets.ts
Fixes complaining about big red boxes
* Show just a teeny network issue indicator, unless they're on the Game page.
(build on #2387)
> Discreet network status

- src/components/NetworkStatus/NetworkStatus.tsx
- src/lib/sockets.ts
and  add console debug for users with trouble cases.
Fixes slow internet banner appearing on correspondence games
Check for "live game" properly
Add console log showing user's network status parameters more clearly
> Fix bugged check for live game

- src/models/games.d.ts
- src/views/Game/Game.styl
- src/views/Game/Game.tsx
- src/views/Game/PlayControls.styl
- src/views/Game/PlayControls.test.tsx
- src/views/Game/PlayControls.tsx
Adds some additional text as to why a game was annulled. The "Game Annulled" text can now be hovered (or tapped on mobile) to get some additional information:
> Add some explanations as to why a game was annulled

- src/views/Game/Game.tsx
Fixes people not liking auto-zen for correspondence
https://forums.online-go.com/t/request-zen-mode-default-option-improvements/49633?u=greenasjade
- Don't auto-zen correspondence games
> Don't auto-zen for correspondence games

- src/components/ModerateUser/ModerateUser.tsx
- src/components/ModerationOfferControl/ModerationOfferControl.styl
- src/components/ModerationOfferControl/ModerationOfferControl.tsx
- src/components/ModerationOfferControl/index.ts
- src/components/Notifications/ModerationOfferModal.styl
- src/components/Notifications/ModerationOfferModal.tsx
- src/components/Notifications/NotificationManager.tsx
- src/components/Notifications/Notifications.styl
- src/components/Notifications/Notifications.tsx
Fixes people getting community moderator powers without being asked first :)
- People get a notification that they have been offered community moderator powers
- They can accept or reject
- Moderators can see where they are up to (accepted/pending/rejected)
- The notification is dismissable only by accepting or rejecting the powers
Needs https://github.com/online-go/ogs/pull/1837
> Community moderation offer

- src/views/ReportsCenter/ViewReport.tsx
Fixes bug caused by checking `detected_ai_games.length` on older reports
> Reports center bug fix 

- src/models/games.d.ts
- src/views/Game/BotDetectionResults.styl
- src/views/Game/BotDetectionResults.tsx
- src/views/Game/Game.tsx
- src/views/Game/GameDock.test.tsx
- src/views/Game/GameDock.tsx
- src/views/Game/PlayerCards.test.tsx
- src/views/Game/PlayerCards.tsx
- src/views/User/GameHistoryTable.tsx
Depends on https://github.com/online-go/ogs/pull/1838
Depends on https://github.com/online-go/ogs/pull/1839
Depends on successful completion of `update_detection_results` command
- Add a button in the dock for mods to show the bot detection result details and button to mark as false positive 
- Display flag on game page and in user history if user is suspected of AI use in game
> Display bot detection result details

- package.json
- src/components/AccountWarning/CannedMessages.ts
- src/components/IncidentReportTracker/IncidentReportTracker.styl
- src/components/IncidentReportTracker/IncidentReportTracker.tsx
- src/components/ModerateUser/ModerateUser.tsx
- src/components/NavBar/NavBar.styl
- src/components/NavBar/NavBar.tsx
- src/components/OgsHelpProvider/OgsHelpProvider.tsx
- src/components/Report/Report.tsx
- src/lib/misc.ts
- src/lib/report_manager.tsx
- src/models/warning.d.ts
- src/views/Game/Game.tsx
- src/views/HelpFlows/CommunityModertatorIntro.tsx
- src/views/HelpFlows/HelpFlows.tsx
- src/views/HelpFlows/UndoIntro.tsx
- src/views/ReportsCenter/ModerationActionSelector.tsx
- src/views/ReportsCenter/ReportsCenter.tsx
- src/views/ReportsCenter/ViewReport.styl
- src/views/ReportsCenter/ViewReport.tsx
- yarn.lock
Fixes community moderators only having Score Cheating to look at :)
- Provide canned messages and voting support for escaping reports.
Built on #2411 
**Requires** 
* https://github.com/online-go/ogs-node/pull/48
* https://github.com/online-go/ogs/pull/1840
> Handle escaping community moderator power

- src/components/GameList/GameList.tsx
GameList doesn't consider the pause state when sorting by Clock. Document why, and explain how it could be fixed in the future. (Also document other limitations of the current sort.)
The short answer: during GameList's initial sort (before rendering), it doesn't have access to the pause state. The Goban (which has a pause state) won't be initialized until each line is rendered. Re-sorts could look at Goban.last_emitted_clock.pause_state. I tried this and it made the UI glitchy.
This commit also replaces the tuple returned by extractClockSortFields() with a dictionary to make it more obvious what's going on. No functionality change intended.
> Document why pause state is not considered when sorting by Clock

- .github/workflows/uffizzi-build.yml
- .github/workflows/uffizzi-preview.yml
This update sanitizes user input from contributor forks. This fixes a GHA workflow security vulnerability.
> Sanitize input from contributor fork workflows.

- src/components/LoadingButton/LoadingButton.styl
- src/components/LoadingButton/LoadingButton.tsx
- src/components/LoadingButton/index.ts
- src/views/Register/Register.styl
- src/views/Register/Register.tsx
- src/views/SignIn/SignIn.tsx
Fixes #
Add loading indicator in signup button and register button.
https://github.com/online-go/online-go.com/assets/16285118/a6dbd867-5180-4480-a164-73c174282fd3
> Add loading indicator in signup button and register button

- src/components/SeekGraph/SeekGraph.tsx
This removes restrictions from the SeekGraph related to ranked games.
Relates to #2446, but doesn't complete it, as there are also backend changes necessary. Draft for now, since I suspect those should land first.
> Allow any player to have a ranked game with any opponent

- src/views/Joseki/Joseki.tsx
placement field must always be presentation format on client side.
Fixes sending placement in internal format.
Always use presentation format - and assume server will always send presentation format.
> This time for sure

- src/components/GobanThemePicker/GobanThemePicker.styl
- src/components/GobanThemePicker/GobanThemePicker.tsx
… and emphasise selected theme
Fixes slightly off layout, and folk not being clear what's selected
- Use the Custom theme that comes from GobanSortedThemes in the picker, rather than create a new one
- 1px wider border for "selected"
> Make sure custom theme styles are applied to custom theme picker

- src/lib/translate.ts
Fixes having to hunt around for an example
- Pop an example in translate.ts
> Added an example of how to use interpolate, right where it's defined.

- src/views/ReportsCenter/ModerationActionSelector.tsx
Fixes some help items not showing
- Repair previous "replaceo"
> Fix accidental target element name change

- src/components/ModerationOffer/ModerationOfferModal.tsx
- Put a link to the CM doco in the offer modal
> Add a link to the CM doco in the offer modal

- src/views/Ladder/Ladder.styl
- src/views/Ladder/Ladder.tsx
On the ladder page itself, show what the rules are for the ladder.
Relates to #2541 (but doesn't really depend on it)
Depends on https://github.com/online-go/ogs/pull/1929
> Show the rules configured for a ladder

- src/lib/misc.ts
- src/views/Game/PlayerCards.tsx
- src/views/Game/Players.styl
Add titles for rules and handicap in the player cards.  For example:
- Expand "JP" out to "Rules: Japanese"
- Expand "③" out to "Handicap: 3"
> Add titles for rules and handicap in player cards

- src/components/IncidentReportTracker/IncidentReportTracker.tsx
Fixes CMs reporting a bug that the counter gets stuck at 10
- Don't show the counter to CMS
> Don't show report count to cms ... they don't have a daily limit.

- src/views/Settings/Settings.tsx
Fixes CMs on the phone not seeing the Moderator Preferences section (needed for report quota)
- Add CMs to the users who get offered this option
> Add the Moderator Preferences option to the dropdown used on the phone

- src/components/IncidentReportTracker/IncidentReportTracker.tsx
(because moderators can turn it off anyhow now)
Fixes # superuser developers thinking quota is broken
- Remove quota exemption for superuser
> Remove report quota exemption for super_user 

- src/components/IncidentReportTracker/IncidentReportTracker.tsx
Fixes report counter not updating when you change these things
- Watch the relevant data and refresh
> Watch prefs for changes to reports available

- src/components/TabCompleteInput/TabCompleteInput.styl
- src/components/TabCompleteInput/TabCompleteInput.tsx
Reverts online-go/online-go.com#2595
> Revert "Wrap the <input> in chat boxes in a form and provide hint"

- src/views/Tournament/Tournament.styl
- src/views/Tournament/Tournament.tsx
Fixes #2597
- Adds a player count to the tournament signup section
> Add player count to tournament signup section

- src/views/Game/GameChat.tsx
Fixes  confusion about what Malk really does
- Say what it really does
> Clarify the placeholder text for malkovitch

- package.json
- src/views/User/ActivityCard.tsx
- src/views/User/User.styl
- src/views/User/UserVoteActionSummary.tsx
- yarn.lock
, showing the summary of their efforts.
Fixes lack of feedback about what happened :)
- Put a pie of "what happened to their reports" in their Community Moderator section of Activity Card
(note, I intend to follow this with other pies by report type, which the back end PR supports)  
* Needs https://github.com/online-go/ogs/pull/1948
> Added a pie to CM's view of their Profile

- src/lib/moderation.tsx
- src/lib/report_manager.tsx
- src/lib/report_util.ts
- src/views/ReportsCenter/ReportsCenter.tsx
- factor a new function `community_mod_has_power` out of `community_moderator_can_handle`.
- tidy up logic to return false if the subject is not a CM.
> Factor "cm_has_power" out of "cm_can_handle" for future use.

- package.json
- yarn.lock
Fixes bomb when drawing pie due to missing dependency
- Add the dependency
> add missing nivo package component

- package.json
- src/lib/moderation.tsx
- src/lib/report_manager.tsx
- src/lib/report_util.ts
- src/views/ReportsCenter/ReportsCenter.tsx
- src/views/User/ActivityCard.tsx
- src/views/User/User.styl
- src/views/User/UserVoteActionSummary.tsx
- yarn.lock
Fixes wondering how we voted vs our peers in different report
- Show a pie of each report type
> Cm breakdown of vote outcomes

- src/components/AnnulQueueModal/AnnulQueueModal.tsx
- src/components/ChallengeModal/ForkModal.tsx
- src/components/GameList/GameList.tsx
- src/components/MiniGoban/MiniGoban.tsx
- src/components/RatingsChartByGame/RatingsChartByGame.tsx
- src/routes.tsx
- src/views/Game/GameLinkModal.tsx
- src/views/GameEmbed/GameEmbed.tsx
- src/views/LearningHub/LearningHub.tsx
- src/views/PuzzleCollection/PuzzleCollectionList.tsx
- src/views/PuzzleCollection/SortablePuzzleList.tsx
- src/views/PuzzleList/PuzzleList.tsx
- src/views/ReportsCenter/ReportedGame.tsx
- src/views/Tournament/Tournament.tsx
Adds support for iframe embedding of reviews
> Add support for embedding reviews as iframes like we can do for games

- package.json
- src/views/User/UserVoteActionSummary.tsx
- yarn.lock
Fixes  red screen 🤞
- Align version of @nivo/pie to the others
Full discloser: it makes sense, though it is also "trial and error" debugging.
> nivo package version align

- src/views/User/ActivityCard.tsx
- src/views/User/User.styl
- src/views/User/UserVoteActionSummary.tsx
- src/views/User/VoteActivityGraph.tsx
Fixes  higledypigldy appearance
- Tweak colours and margins
> Tweak layout of CM activity charts

- src/views/TournamentList/TournamentList.tsx
Add TournamentListImpl to share code between MyTournaments and TournamentList, and take the best of both.
Improvements for TournamentList:
- Show actual tournament start times if started.
- Show tournemtn end times if ended.
Improvement for MyTournaments:
- Show the minimum number of players needed for not-yet-full tournaments to start.
> Share code between MyTournaments and TournamentList

- src/views/Prizes/PrizeBatch.tsx
- Adds translation to voucher template
> Add translation for voucher template 

- src/views/ReportsCenter/ReportsCenterCMInfo.styl
- src/views/ReportsCenter/ReportsCenterCMInfo.tsx
Also got rid of "current week" from totals graph.
Fixes wondering about how the percentages are going :)
> Added a graph showing percentage of concensus/non/escalated.  

- src/components/AccountWarning/CannedMessages.ts
Fixes people being offended by accusation of cheating.
- Use different words
> Nicer score cheat message, composed by the forum.

- src/components/Report/Report.styl
- src/components/Report/Report.tsx
Fixes people choosing a different type  of report that they are allowed to submit
- Show the remaining character count above the greyed submit button
> Tell the user how many more characters they have to type

- src/views/ReportsCenter/MessageTemplate.tsx
Fixes templates encouraging moderators to use less-good wording
- Add beginner score cheating template
- Word both score cheating warning templates based on the CM score cheating template
> Modelled the moderator score cheating templates on the newer version approved by the forumites for CMs.

- src/views/OnlineLeagueSpectatorLanding/OnlineLeagueSpectatorLanding.tsx
Fixes #2670
- Add the word "when" in the message where it belongs.
> Fixed typo in message

- src/components/Chat/ChatLog.tsx
#Fixes 
https://github.com/online-go/online-go.com/issues/2677
adds back autocomplete false to chat input field.
> add autocomplete off to chat input field

- src/lib/report_util.ts
- src/views/ReportsCenter/ModerationActionSelector.tsx
- src/views/ReportsCenter/ViewReport.styl
- src/views/ReportsCenter/ViewReport.tsx
- Show CMs the current vote-count on each option
... helps decide if reclassifying a dubious report is worth it
> Vote counts

- src/views/ReportsCenter/MessageTemplate.tsx
Fixes officious confrontational tone
- Different words.
> Nicer  chat abuse warning moderator template

- src/components/ChallengeModal/ChallengeModal.tsx
- src/components/IncidentReportTracker/IncidentReportTracker.tsx
- src/lib/automatch_manager.tsx
- src/routes.tsx
- src/views/Tournament/Tournament.tsx
Fixes #2700
- Replaces `/game/view` calls with `/game`
- Replaces `/review/view` with `/review`
- Replaces `/demo/view` with `/demo`
This did not impact functionality when I attempted to use the new routes.
> Unify endpoints

- Gulpfile.js
Fixes me having to keep an eye on who's committing and find a way to contact them
- Put a slack invite link into dev server startup.
> Added a slack invite link to dev server startup message.

- src/views/ReportsCenter/MessageTemplate.tsx
Fixes us sounding officious
- Talk a bit more nicely.
> Update undo harrasment message

- src/views/Play/Play.styl
Fixes #2622 
- Just fixed a typo which prevented the tooltip from displaying when hovered
> Show challenge tooltip on hover

- src/components/AccountWarning/CannedMessages.ts
- src/views/ReportsCenter/ViewReport.tsx
Fixes accidental wrong report type
- Fire a confirm dialog before changing report type
- (and fix a couple of bad message formats)
> Confirm change report type

- src/components/IncidentReportTracker/IncidentReportTracker.tsx
- src/lib/report_util.ts
- src/views/ReportsCenter/ModerationActionSelector.styl
- src/views/ReportsCenter/ModerationActionSelector.tsx
- src/views/ReportsCenter/ViewReport.tsx
- Allows community moderators to cancel their own reports in the report view
I still have to test and style the changes
> Allow CMs to cancel their own reports

- src/components/IncidentReportTracker/IncidentReportCard.tsx
- src/components/IncidentReportTracker/IncidentReportTracker.styl
- src/components/IncidentReportTracker/IncidentReportTracker.tsx
Fixes people needing to submit another report to add more information
- Allow normal users to edit their reporter_note
Needs https://github.com/online-go/ogs/pull/1975
> Edit report description

- src/views/Group/Group.tsx
> Types for Group.tsx

- src/views/ReportsCenter/ReportsCenterCMHistory.tsx
- src/views/ReportsCenter/ReportsCenterCMInfo.styl
- src/views/ReportsCenter/ReportsCenterCMInfo.tsx
Fixes curiosity and wondering
- Add a tab to Community Moderation dashboard that shows CM's their own outcomes over time
** Needs https://github.com/online-go/ogs/pull/1984
> Add a tab to Community Moderation dashboard that shows CM's their own outcomes over time

- src/views/ReportsCenter/ReportsCenterCMInfo.styl
Fixes names taking up more space than the graph 🤦‍♀️
- Max width for the player name.
> Make the CM name column max width

- src/components/NavBar/NavBar.tsx
- src/lib/preferences.ts
- src/views/GoTV/GoTV.styl
- src/views/GoTV/GoTV.tsx
- src/views/GoTV/GoTVIndicator.styl
- src/views/GoTV/GoTVIndicator.tsx
- src/views/GoTV/GoTVNotification.tsx
- src/views/GoTV/GoTVNotifier.styl
- src/views/GoTV/GoTVNotifier.tsx
- src/views/GoTV/StreamCard.tsx
- src/views/GoTV/StreamManager.ts
- src/views/GoTV/index.ts
- src/views/GoTV/useTwitchIntegration.ts
- src/views/Settings/GoTVPreferences.tsx
- src/views/Settings/Settings.styl
- src/views/Settings/Settings.tsx
Depends on https://github.com/online-go/ogs/pull/1980
- Stop translating the name "GoTV" 
- Remove OGS chat from streams
- Switch from using iframe to Twitch.Embed 
- Add twitch OAuth to GoTV preferences and get user's followed channels
- Add notifications when followed channels go live
- I left in a little debugging section in GoTV preferences to help ease testing.  Let me know when you've finished looking around and I'll take it out
- Callback URIs will need to be updated in the twitch dev console
> GoTV updates

- .vscode/cspell.json
- src/views/ReportsCenter/ReportsCenterCMInfo.tsx
Fixes axes not matching data 😝
- Use better numbers
> Graph tidyups

- src/views/HelpFlows/CommunityModeratorIntro.tsx
- src/views/ReportsCenter/ViewReport.tsx
Fixes CMs feeling compelled to vote even if they aren't sure
- Add an RDH step that tells them about "Ignore"
- also fixed up another RDH message wording, which was out of date
> Tell CMs that they can Ignore reports.

- src/views/ReportsCenter/ReportsCenterCMHistory.tsx
- src/views/ReportsCenter/ReportsCenterHistory.styl
~Fixes~ Improves yucky presentation
-  Lay out the vote count more sensibly
- Show the CM their vote outcome (when it's available: https://github.com/online-go/ogs/pull/1990)
> Cm history update

- src/views/ReportsCenter/ReportsCenterCMInfo.tsx
Fixes # 404
- Point at the new route name
> Fix updated route

- src/lib/report_manager.tsx
Fixes console noise
- remove log (I think it was mine 😅 )
> remove debug message

- package.json
- src/components/ChallengeModal/ChallengeModal.tsx
- src/components/NavBar/NavBar.tsx
- src/views/Game/Game.tsx
- src/views/Game/PlayButtons.tsx
- src/views/Game/PlayerCards.tsx
- src/views/LibraryPlayer/LibraryPlayer.tsx
- yarn.lock
This patch adds a new button to the SGF library
This creates a self-play game where the player names can be provided like a demo board. The primary difference between this and a demo board is this is a "real game" in the sense that it is not a review itself, so can be reviewed itself by third party accounts.
> Add better support for IRL game recording

- package.json
- src/components/GobanThemePicker/GobanThemePicker.styl
- src/components/GobanThemePicker/GobanThemePicker.tsx
- src/components/MiniGoban/MiniGoban.tsx
- src/components/PersistentElement/PersistentElement.tsx
- src/lib/SettingsCommon.tsx
- src/lib/configure-goban.tsx
- src/lib/data_schema.ts
- src/lib/preferences.ts
- src/views/Game/Game.tsx
- src/views/Settings/GamePreferences.tsx
- src/views/Settings/GeneralPreferences.tsx
- src/views/Settings/Settings.styl
- src/views/Settings/Settings.tsx
- src/views/Settings/ThemePreferences.styl
- src/views/Settings/ThemePreferences.tsx
- yarn.lock
> Move advanced goban theme settings to settings page; add stone removal graphic and size options

- src/lib/misc.ts
- src/views/ReportsCenter/ReportsCenterCMDashboard.tsx
- src/views/User/VoteActivityGraph.tsx
Fixes ugly looking low data point at the end of the curve :)
- Put the existing "remove last period" function into misc, and call it from VoteActivityGraph
> Remove current (incomplete) period from vote count  graph

- src/views/ReportsCenter/ReportedGame.styl
- src/views/ReportsCenter/ReportedGame.tsx
- src/views/ReportsCenter/ReportsCenter.styl
Fixes hassles scrolling around trying to see the obvious :)
- Pull more bits into components, and shuffle for effect.
- Much less space given to "chat"
- Put very "game-board-related" things near the goban
Good in itself, also heading in the direction of having reported-game-elements that can be more flexibly laid out.
> Next step in `ReportedGame` relayout

- src/components/OgsHelpProvider/OgsHelpProvider.tsx
- src/lib/hooks.ts
- src/views/Game/GameLog.tsx
- src/views/HelpFlows/GameLogHelp.tsx
- src/views/HelpFlows/HelpFlows.tsx
Fixes CMs (and moderators :) ) not understanding what's going on with autoscore entries in the game log.
- Use an RDH popup to tell them
Really needs https://github.com/online-go/online-go.com/pull/2806 because the popup is badly placed on mobile until RDH layout bug is fixed.
> Help for game log autoscore

- package.json
- src/components/IncidentReportTracker/IncidentReportTracker.tsx
- src/ogs.styl
- src/views/Game/PlayControls.tsx
- src/views/Settings/Settings.tsx
- yarn.lock
Fixes lurking issues with RDH uncovered by newer eslint, and enables more RDH maintenance
- Move to RDH 3.0.1, which has a packaging revamp and can readily have updates published.
- Fix the things that eslint points out aren't necessarily going to work as intended.
> Move to RDH 3.0.1, fix issues uncovered in the process.

- package.json
- yarn.lock
Fixes yarn complaining.
-  Move to 7.0.0.
Seemed to "just work" for me, tested on Settings->General.
> Move to react-switch 7.0.0

- src/lib/translate.ts
- src/views/Game/GameLog.tsx
- src/views/HelpFlows/GameLogHelp.tsx
- src/views/User/VoteActivityGraph.tsx
Fixes some inadvertent reversions from the absolute imports PR
- Revert the non-import related changes.
> Absolute import fixups

- src/views/ReportsCenter/ViewReport.tsx
Fixes CMs not seeing why the report was escalated
- Make the CM note visible to CMs with SUSPEND
> Show CM note to CMs with suspend power

- src/views/HelpFlows/CommunityModeratorIntro.tsx
- src/views/ReportsCenter/ModerationActionSelector.tsx
Fixes out of date info
- Update prompt and RDH text to properly describe the new way things are
> Update the escalate vote action description and help text

- src/views/ReportsCenter/ModerationActionSelector.tsx
Fixes old unclear text
-  Be more specific
> Update description of escalation vote, in line with current thinking

- src/views/User/VoteActivityGraph.tsx
Fixes smooshed up dates on the x axis, because KoBa asked nicely.
- Just show the month, worry about what year it was later.
> Reduce precision on votes-by-week graph

- .vscode/cspell.json
- src/views/User/ModLog.styl
- src/views/User/ModLog.tsx
so CMs can "see at a glance" the important history
> Highlight the CM action in mod logs

- .github/workflows/main.yml
- .github/workflows/uffizzi-build.yml
- .github/workflows/uffizzi-preview.yml
Github is deprecating some action versions, this branch is updating those action versions
> Update github actions to avoid hitting deprecation date

- src/components/CMVotingGroupGraph/CMVotingGraphs.tsx
- src/components/CMVotingGroupGraph/index.ts
- src/components/NavBar/NavBar.tsx
- src/views/ReportsCenter/ReportsCenter.tsx
- src/views/ReportsCenter/ReportsCenterCMDashboard.tsx
… to everyone in,  the Reports Center
Fixes folk not knowing how lucky they are 😝
This is in advance of 'announcing' that the CM trial is pretty much no longer a trial, it's mainstream.
- Show the oldest open CM class reports in a tab in Community Moderation in Reports Center
- Allow all users to see "Community Moderation" and "My Reports" categories in the Reports Center
Needs https://github.com/online-go/ogs/pull/2025
> Show CM performance (and incidentally "My Own Reports) 

- src/views/ReportsCenter/ReportsCenterCMDashboard.tsx
Fixes wondering what report is languishing unattended.
- If the back end provides the report id (which currently it only does for moderators) then display a link to that report.
Needs: https://github.com/online-go/ogs/pull/2026
> Show a link to the oldest  open CM report, if the back end provides it.

- i18n/audit-translations.js
- src/views/ReportsCenter/ModerationActionSelector.tsx
Starting point for ACTION_PROMPT prompt engineering
- Provide some llm prompt context that we think will help
> Added common llm translate context for CM `ACTION_PROMPTS`

- src/components/TabCompleteInput/TabCompleteInput.tsx
This PR removes the jQuery dependency from the TabCompleteInput component by reimplementing the tab completion functionality in pure React.
Changes:
- Removed jQuery dependency and nicknameTabComplete plugin usage
- Implemented core functionality directly in React
- Added proper TypeScript types
- Improved code structure using React hooks
- Maintained all original features including:
- Tab completion for nicknames
- Support for partial matches and multiple matches
- Space handling after completion
- Player ID lookup and @-mention format
- Focus retention after tab completion
Benefits:
- No jQuery dependency
- Better TypeScript support
- More maintainable React-style code
- Better performance (no jQuery overhead)
- Easier to test and debug
> refactor: Remove jQuery dependency from TabCompleteInput

- src/views/ReportsCenter/ModerationActionSelector.tsx
- src/views/ReportsCenter/ViewReport.tsx
Fixes wondering which option I chose :)
- Preselect the chosen option, if it exists, and mark it with a star.
Needs: https://github.com/online-go/ogs/pull/2029, won't break, just won't work.
> Show CMs if they have already voted on an open issue what that vote is.

- src/views/ReportsCenter/ReportsCenter.tsx
Fixes #2922
- Allow for use of back button when navigating to reports center
> fix: replace history to allow back button

- src/views/ReportsCenter/ModerationActionSelector.tsx
Fixes tranlsation breakage
-
-
-
> move llm context to inline string

- src/views/ReportsCenter/ModerationActionSelector.tsx
Fixes erractic translation
- Tweaks as per https://forums.online-go.com/t/improving-cm-translation/54896/35?u=greenasjade
> translation prompt tweaks

- src/views/Puzzle/Puzzle.styl
> Fix puzzle description being cutoff on mobile

- src/views/ReportsCenter/ReportedGame.tsx
- src/views/ReportsCenter/ViewReport.tsx
Fixes bloody irritating arrow keys not working :)
- Expose the goban from ReportedGame to ViewReport and have keypresses there do next/prev
> Wire up the arrow keys on the ViewReport page to prev/next in the ReportedGame goban

- .github/workflows/main.yml
- vite.config.ts
- yarn.lock
I broke our CI, this should fix it
> Fix the CI

- src/components/AIReviewStream/AIReviewStream.tsx
- src/views/Game/AIReview.tsx
This contains a few fixes for some edge cases that don't work as expected with our AI reviews
> Fix editing board positions breaking ai reviews in game analysis

- src/views/Game/PlayButtons.tsx
Fixes #2943
- It add a condition (current move is last move) to show the Pass Button
I verified also that the pass button still shows during a Live game
> Add current turn to the condition to show Pass button

- src/components/FriendList/FriendList.tsx
- src/main.tsx
- src/models/friends.d.ts
- src/models/puzzles.d.ts
- src/models/user.d.ts
> Add pending friend invitations to friends list

- src/views/Game/Game.tsx
Fixes #2869
I am not sure how to check the presence of the official moves correctly :man_shrugging:
> Follow the selected branch if the official branch is empty when the fast forward button is pressed

- src/views/Game/Game.tsx
> Do not update title if there were no new moves

- src/views/ChatView/ChatView.tsx
> Change window title to Chat on ChatView mount

- src/views/User/User.tsx
> Hide user's empty associations and servers

- src/views/ReportsCenter/ModerationActionSelector.tsx
- src/views/ReportsCenter/ViewReport.tsx
Fixes console messages and head-scratching
- undebug and clarify some jsx
> teeny tidy

- src/components/IncidentReportTracker/IncidentReportCard.tsx
- src/components/IncidentReportTracker/IncidentReportList.styl
Fixes clicking on the button and cursing
- Make the button onClick navigate to the report, for moderators
> Make the report_id button on IncidentReportCard navigate for moderators.

- e2e-tests/cm/cm-dont-notify-escalated-ai.ts
- e2e-tests/cm/cm-show-only-post-escalation-votes.ts
- e2e-tests/cm/cm.spec.ts
- e2e-tests/helpers/user-utils.ts
Fixes not having a test for that bug.
- Added `cmShowOnlyPostEscalationVotesTest`
> Added e2e test for https://github.com/online-go/ogs/pull/2055

- .vscode/cspell.json
- src/components/RatingsChartDistribution/RatingsChartDistribution.styl
- src/components/RatingsChartDistribution/RatingsChartDistribution.tsx
- src/components/RatingsChartDistribution/index.ts
- src/views/User/User.tsx
Feature Request #2431 
- Borrowed from Lichess repo based on user feature request: https://lichess.org/stat/rating/distribution/classical
- adds RatingsChartDistribution.tsx to Profile Section (User.tsx) below Ratings above current Game Chart
- UX/UI experience? Best location/div to put in
- React component mounting raises warnings see browser log when testing
- adds chart.js to dependencies
- fetch() for /termination-api/ reading? vs get?
> New Feature Request: #2431 Player Rating Histogram

- e2e-tests/cm/cm-dont-auto-warn-first-turn-blitz.ts
- e2e-tests/cm/cm.spec.ts
-  Test for https://github.com/online-go/ogs/pull/2060
> Add test for https://github.com/online-go/ogs/pull/2060 dont autowar blitz escape

- .vscode/cspell.json
- src/components/ChallengeModal/ChallengeModal.api.tsx
- src/components/ChallengeModal/ChallengeModal.test.tsx
- src/components/ChallengeModal/ChallengeModal.tsx
- src/components/ChallengeModal/ChallengeModal.types.ts
- src/components/ChallengeModal/ChallengeModal.utils.ts
- src/components/ChallengeModal/index.ts
This PR aims to reduce the file size of [https://github.com/online-go/online-go.com/blob/devel/src/components/ChallengeModal/ChallengeModal.tsx](url) by splitting parts into new files, without changing the behaviour. The idea is to make it easier to get and keep an overview.
Unfortunately a big diff for not much, but I believe this as a good first step.
- Move types and interfaces into `ChallengeModal.types.ts`
- Move functions which other components can use to open the modal into `ChallengeModal.api.tsx`
- Move other functions outside of the component class into `ChallengeModal.utils.ts`
- Update imports and exports accordingly
- Remove unused consts `negKomiRanges`, `posKomiRanges`
> separate into multiple files, remove unused consts

- e2e-tests/helpers/user-utils.ts
- src/models/moderation.d.ts
- src/views/ReportsCenter/ModerationActionSelector.tsx
- src/views/ReportsCenter/ViewReport.tsx
Fixes ~~AI not knowing how to write code for me :)~~ ...  um benjito frowning when he sees Array\<string\> 😝
- Add type for CommunitModerationActions set of strings, and all fields that use these.
> Extra typing for CommunityModeratorAction definition

- e2e-tests/challenges/ch-rengo.ts
- e2e-tests/challenges/ch.spec.ts
- e2e-tests/helpers/challenge-utils.ts
Fixes no test for #3050
- Some basic tests using things #3050 touched.
> E2e rengo challenge modal tests

- e2e-tests/challenges/ch-rengo.ts
- e2e-tests/helpers/challenge-utils.ts
Fixes not having a test for the way the checkboxes interact
- Add checkbox interaction to rengo challenge e2e test
- Improve challenge modal utils
> Added testing for challenge modal rengo related checkbox interactions

- src/views/ReportsCenter/ReportsViewer.styl
- src/views/ReportsCenter/ReportsViewer.tsx
Fixes me being slow to realise I'm looking at an already-handled report :)
- Add a "Resolved" label in the heading when the report looks resolved.
> Add a label showing on reports in ViewReport that are resolved.

- .gitignore
- e2e-tests/challenges/ch-private-invite.ts
- e2e-tests/challenges/ch-rengo.ts
- e2e-tests/challenges/ch.spec.ts
- e2e-tests/helpers/challenge-utils.ts
Fixes not having test for these
- New test for private and invite only checkboxes
> E2e challenge private invite only checkboxes

- src/views/Play/QuickMatch.styl
Fixes wondering whether that line is broken or not :)
- Add a colon to a display stylus that didn't have one.
> Add a colon to display directive

- src/models/games.d.ts
- src/views/AIDetection/AIDetection.tsx
Fixes wondering why some games don't have AI reviews
- Show number of moves in games
Needs https://github.com/online-go/ogs/pull/2067
> Add number of moves in the game to the table

- .vscode/cspell.json
- src/components/JosekiAdmin/JosekiAdmin.styl
- src/components/JosekiAdmin/JosekiAdmin.tsx
- src/components/JosekiTagEditor/JosekiTagEditor.styl
- src/components/JosekiTagEditor/JosekiTagEditor.tsx
- src/components/JosekiTagEditor/index.ts
- src/components/JosekiTagSelector/JosekiTagSelector.tsx
- src/components/JosekiVariationFilter/JosekiVariationFilter.tsx
- src/models/joseki.d.ts
- src/views/Joseki/Joseki.styl
- src/views/Joseki/Joseki.tsx
Fixes me not being able to change or add to OJE position tags :)
- Add some CRUD in Admin
Needs https://github.com/online-go/ogs/pull/2074
> Add some buttons to help admin OJE tags

- src/views/AIDetection/AIDetection.styl
- src/views/AIDetection/AIDetection.tsx
hide dubious ones.
Fixes # ease of absorbing at a glance.
-  Separate AI analysis parameters into their own columns, hide dubious ones.
> Separate AI analysis parameters into their own columns, 

- src/views/AIDetection/AIDetection.styl
- src/views/AIDetection/AIDetection.tsx
- src/views/ReportsCenter/ReportedGame.styl
- src/views/ReportsCenter/ReportedGame.tsx
Fixes AILR 
- Show the new AILR
Needs: https://github.com/online-go/ogs/pull/2076
> Display fixed-ailr calculation results in good places.

- src/views/AIDetection/AIDetection.tsx
Fixes # a page full of sad cats
- Don't show AILR at all for fast reviews
> Don't show broken data cat for fast reviews, they just don't have AILR

- src/views/AIDetection/AIDetection.tsx
Fixes # AI detectors not being able to filter :)
- Add grooming filters to AI detection
> Make ai detection table filterable by parameters

- src/models/games.d.ts
- src/views/AIDetection/AIDetection.tsx
Fixes # borked filters, and improves a bunch of stuff
- Numerous tweaks to AI D table.
> Aid filter logic

- src/components/Player/Player.styl
- src/components/Player/Player.tsx
- src/models/games.d.ts
- src/views/AIDetection/AIDetection.tsx
Fixes needing to know more about the game to understand the parameters
-  Show ranked, speed & banned players
Needs https://github.com/online-go/ogs/pull/2082
(It's on top of #3084  ... the difference is that this one needs the backend update, although it won't break without it, it might just lie :) )
> More aid info

- src/views/AIDetection/AIDetection.tsx
Fixes wondering why the filter isn't doing anything
- Grey it out when it's not active
Note: intended PR for testing deploy to beta.
> tweak filters off logic

- src/views/Game/AIReview.tsx
Fixes AI detectors relying on moderators or fast reviews.
- Enable the buttons that request full reviews.
Needs https://github.com/online-go/ogs/pull/2084
> Enable full ai review request for AI detectors

- src/views/AIDetection/AIDetection.tsx
Fixes having to retype the parameters all the time
- Write filter updates to the URL params, and load them from there
> Store AID filter params in URL for ease of sharing and refresh page

- src/views/LearningHub/LearningHub.styl
- src/views/LearningHub/LearningPage.tsx
- src/views/LearningHub/Sections/BasicPrinciples/BPKo.tsx
- src/views/LearningHub/Sections/BasicPrinciples/BPSelfCapture.tsx
- src/views/LearningHub/Sections/BasicPrinciples/CountAtari.tsx
- src/views/LearningHub/Sections/BasicPrinciples/CountChains.tsx
- src/views/LearningHub/Sections/BasicPrinciples/CountLiberties.tsx
- src/views/LearningHub/Sections/BasicPrinciples/GroupAlive.tsx
- src/views/LearningHub/Sections/BasicPrinciples/InAtari.tsx
- src/views/LearningHub/Sections/BasicPrinciples/RealFalseEye.tsx
- src/views/LearningHub/Sections/BasicSkills/BSEscape.tsx
- src/views/LearningHub/Sections/BasicSkills/BSGroupAlive.tsx
- src/views/LearningHub/Sections/BasicSkills/CompareLiberties.tsx
- src/views/LearningHub/Sections/BasicSkills/CountTerritory.tsx
- src/views/LearningHub/Sections/BasicSkills/EscapePossible.tsx
- src/views/LearningHub/Sections/BasicSkills/ReduceLiberties.tsx
- src/views/LearningHub/Sections/BasicSkills/Winner.tsx
- src/views/LearningHub/Sections/Fundamentals/EndingTheGame.tsx
- src/views/LearningHub/Sections/Fundamentals/Territory.tsx
- src/views/LearningHub/sections.ts
Fixes #
- structure for new type of exercises: multiple choice
- added multiple choice exercises for the first 3 chapters of the course
-
> added multiple choice exercises

- src/lib/ai_review_move_categories.ts
- src/lib/misc.ts
- src/lib/preferences.ts
- src/views/Game/AIReview.styl
- src/views/Game/AIReview.tsx
- src/views/Settings/GamePreferences.tsx
Fixes debate about what move categorisation to use
- Refactor AIReview to get categorisation calculation out at a pure function
- Add "new" to the "old" method of categorisation, switchable
> Update move categorisation

- src/lib/ai_review_move_categories.ts
- src/lib/preferences.ts
- src/views/Game/AIReview.tsx
Fixes AI detectors not being able to experiment
- Editable move threshold values
> configurable move categorisation

- src/components/ChallengeModal/ChallengeModal.tsx
- update bindings: board size, disable analysis, rank restrictions, demo board players
- remove upstate functions
> Challenge modal state updates

- src/components/Errcode/Errcode.tsx
Fixes agumentation.  Perhaps.
-  Change "you cant have that game name" as per https://forums.online-go.com/t/offensive-title/52885/17?u=greenasjade
> Tweak "you can't have that game name"

- src/components/AIReview/AiSummaryTable.styl
- src/components/AIReview/AiSummaryTable.tsx
- src/components/AIReview/MoveListPopover.tsx
- src/lib/ai_review_move_categories.ts
- src/views/Game/AIReview.styl
- src/views/Game/AIReview.tsx
Fixes wondering which moves were categorized which way.
- Add a dropdown to show the moves of each category
- Show these moves on the graph
- Make them clickable to get to them.
> Show move categorisation

- src/components/AIReview/AiSummaryTable.tsx
- src/lib/ai_review_move_categories.ts
- src/models/games.d.ts
- src/views/Game/AIReview.tsx
Fixes not being able to debug score loss :)
- Put the logs back
> Put back debug log of score-loss data (and format tidy)

- .vscode/cspell.json
- src/lib/ai_review_move_categories.ts
Fixes MrMTal hassling me to change it :)
- Put in the forumula as per  https://forums.online-go.com/t/game-to-debug-2nd-try/56878/8?u=greenasjade
> Change the "new" ASL computation to use MrMTal "blue compensated" formula

- src/lib/ai_review_move_categories.ts
Fixes MrMTal not understanding my debug log
- Say what ai_review elements were used.
> Better messages about what's going into scoreless now

- e2e-tests/friends/decline.ts
- e2e-tests/friends/friends.spec.ts
- e2e-tests/helpers/challenge-utils.ts
- e2e-tests/helpers/user-utils.ts
- src/components/FriendList/FriendList.tsx
- src/components/Notifications/Notifications.tsx
Fixes people feeling bad about declining.
Slightly controversial
https://forums.online-go.com/t/feature-request-not-to-send-declined-friend-request-notification/56862/22?u=greenasjade
-  Checkbox to opt into decline friend request notification
Needs https://github.com/online-go/ogs/pull/2098
> Provide a checkbox to say if you want to notify your friend request decline.

- src/components/AccountWarning/CannedMessages.ts
Fixes people being annoyed about getting warned.
-  Reword.
(standalone, doesn't depend on anything)
> Be more friendly, less blamey.

- src/lib/data_schema.ts
- src/lib/debug.ts
- src/views/Settings/AccountSettings.test.tsx
Fixes having to set the debug on every time
-  Look in `data` as well as window for debug enabled.
> Add `data` means to persist debug setting

- e2e-tests/e2e-utils/run-game.ts
- e2e-tests/helpers/game-utils.ts
Fixes having to test japanese handicap manually
- Support japanese handicap in playMoves.
> Support Japanese handicap in run-game e2e

- e2e-tests/e2e-utils/run-game.ts
- src/views/Game/AIReview.tsx
Fixes not being able to see the difference between medium and strong cheat detection reviews (if we get the latter :) )
- Add an extra symbol for Strong Cheat Detection reviews.
Won't do anything unless we have https://github.com/online-go/ogs/pull/2116
> Add an extra symbol differentiating a (potential!) strong cheat review.

- e2e-tests/friends/decline.ts
- e2e-tests/helpers/user-utils.ts
- e2e-tests/moderation/mod-auto-warn-first-turn-disconnector.ts
- e2e-tests/moderation/mod-auto-warn-first-turn-escaper.ts
- src/components/AccountWarning/AccountWarning.styl
- src/components/AccountWarning/AccountWarning.tsx
Fixes e2e failures
- Update e2e tests to match recent changes
> Update e2e to deal with various recent changes.

- src/views/LibraryPlayer/LibraryPlayer.tsx
Fixes it has to be the libary owner
- Let AI detectors see the checkboxes
> Let AI detectors see library checkboxes

- .vscode/cspell.json
- src/components/Chat/ChatChannelList.tsx
- src/components/Chat/ChatList.tsx
- src/components/NavBar/OmniSearch.tsx
- src/components/Player/PlayerDetails.tsx
- src/components/PlayerIcon/PlayerIcon.tsx
- src/lib/cdn.ts
- src/lib/player_cache.ts
- src/views/Game/PlayerCards.tsx
- src/views/Group/Group.tsx
- src/views/GroupList/GroupList.tsx
- src/views/LadderList/LadderList.tsx
- src/views/Overview/EXV6Overview.tsx
- src/views/Overview/Overview.tsx
- src/views/TournamentList/TournamentList.tsx
- src/views/User/ActivityCard.tsx
We're moving to a new CDN, this code transforms old CDN urls to the new CDN.
> Migrating user upload urls to new CDN

- AGENTS.md
- src/components/Announcements/ActiveAnnouncements.styl
- src/components/Announcements/ActiveAnnouncements.tsx
- src/components/Announcements/AnnouncementEntry.tsx
- src/components/Announcements/Announcements.styl
- src/components/Announcements/Announcements.tsx
- src/lib/announcement_templates.ts
- src/lib/announcement_utils.ts
- src/views/AnnouncementCenter/AnnouncementCenter.styl
- src/views/AnnouncementCenter/AnnouncementCenter.tsx
Also does not show pop up announcements when ActiveAnnouncements are present, and non system announcements while you're playing a game.
> Multi-link and multi-lingual announcement updates

- src/components/CollectionSharingModal/CollectionSharingModal.styl
- src/components/CollectionSharingModal/CollectionSharingModal.tsx
- src/components/CollectionSharingModal/index.ts
- src/views/LibraryPlayer/LibraryPlayer.styl
- src/views/LibraryPlayer/LibraryPlayer.tsx
Fixes  not being able to share libraries of sgf with select folk.
- Use the new backend ACL to add people to share private collections with
- Fix up the gnarly interface for making new collections that are private
-- Hide the selector until they start creating a new collection
-- Use a toggling icon and label to be clear what is happening
Needs https://github.com/online-go/ogs/pull/2140
> VIBE Share private collection

- src/views/ReportsCenter/ReportedGame.styl
- src/views/ReportsCenter/ReportedGame.tsx
Fixes # untidy unobvious untranslated important information :)
- Translate, highlight
> Prep for simul message: tidy up important info div

- src/views/LearningHub/Sections/BasicSkills/CapturingRace.tsx
> Fix wording in capturing race explanation
