online-go/online-go.com

README.md, package.json, yarn.lock
This works because npm scripts have node_modules/.bin in their
environment as bin.
=> misc(build): add an npm script for convenience

Gulpfile.js, webpack.config.js
Adds ```'use strict';``` to the head of Gulpfile.js and webpack.config.js.
Currently, developers running ```make``` will receive an error similar to the following when the script tries to load the application:
```
Running node-supervisor with
program ''
--watch 'Gulpfile.js'
--extensions 'node,js'
--exec 'gulp'
Starting child process with 'gulp '
Watching directory '/home/mark/dev/websites/online-go.com/Gulpfile.js' for changes.
Press rs for restarting the process.
/home/mark/dev/websites/online-go.com/Gulpfile.js:18
let ts_sources = ['src/**/*.ts', 'src/**/*.tsx'];
^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Object.Module._extensions..js …
```
=> Use strict in Gulpfile and webpack.config

src/components/GobanThemePicker/GobanThemePicker.styl, src/components/GobanThemePicker/GobanThemePicker.tsx, src/lib/ogs-goban/GoTheme.ts, src/lib/ogs-goban/Goban.ts, src/lib/ogs-goban/themes/board_plain.ts, src/lib/ogs-goban/themes/disc.ts
This PR allows for customization of the Plain themes' colors, using standard HTML5 `color` inputs. It fulfills [this feature request](https://ogs.uservoice.com/forums/277766-online-go-com-suggestions-and-feature-requests/suggestions/8182245-custom-colors-for-plain-board-and-stones).
=> Custom colors

src/views/Game/Game.styl
Simple style change causes the goban offsetHeight to report correctly and fixes the issue displayed below. Tested in Chrome and Firefox, goban still works as expected after the change.
=> goban size fix for webkit2-based browsers such as midori, ps4 browser

src/components/PaginatedTable/PaginatedTable.styl
Adds a bit of margin to the top of `.page-controls`.
Fixes issue #63.
=> fixes margin of page-controls

src/main.tsx, src/views/RatingHistory/RatingHistory.styl, src/views/RatingHistory/RatingHistory.tsx, src/views/RatingHistory/index.ts, src/views/User/User.tsx
A **Full View** link is added to a user's profile page below
the rating graph,
which opens a new tab with a fullscreen view of it.
=> Open user's rating history graph in a new tab

src/components/SeekGraph/SeekGraph.tsx
Open challenges are shown as follows:
- Green: Ranked 19x19
- Magenta: Ranked 13x13
- Cyan: Ranked 9x9
- Orange: Unranked
- Grey: Not eligible (as always)
=> Use more colors on seek graph

src/components/GameAcceptModal/GameAcceptModal.tsx
This is minor but it was bugging me, ha.  This changes the text when you accept a game to say `Accepting...` instead of `Accepting..`.
=> Edit ellipsis on accept

src/views/Game/Game.tsx
If the board is not in counting mode (i.e. when in play or analyze mode; and when the game finished on timeout, resignation or cancellation) points are incorrect and therefore irrelevant. Captures and komi are needed instead.
=> Show captures and komi instead of points when relevant

src/components/Chat/Chat.tsx, src/lib/chat_manager.ts, src/lib/misc.ts
It's probably better for ChatUserList to pass a ranking object, so the professional value can be tested for future compatibility. But I couldn't figure out what to change to pass the object instead of the rank. This work around also works.
=> ChatUserList passing rank # not object, but pros aren't > 1000 any more

src/components/PaginatedTable/PaginatedTable.styl, src/components/PaginatedTable/PaginatedTable.tsx, src/views/ObserveGames/ObserveGames.styl, src/views/ObserveGames/ObserveGames.tsx
- Larger font size, this way buttons are easier to access on mobile and numbers are more legible.
- Fix overlap betweeen Total Pages and Next Page button on /observe-games:
- Make "**of**" string translatable.
- Fix #88
=> Page control improvements

src/views/RatingHistory/RatingHistory.styl, src/views/RatingHistory/RatingHistory.tsx, src/views/User/User.styl, src/views/User/User.tsx
Fixes #57. Now that the link to the game is colored, this fix only requires darkening the tooltip background color.
=> Change history graph tooltip background

src/views/Game/Game.tsx
It appears that the function that updates the number of spectators in a match works correctly but is not being called when the number of spectators changes. I have a hunch that a setTimeout is throwing an exception that is silently dropped. Add code to log any exceptions thrown, and continue to watch for further occurrences of the bug.
=> Working on bug #62.

src/lib/ogs-goban/Goban.ts, src/lib/ogs-goban/themes/rendered_stones.ts
Fix proposition for https://github.com/online-go/online-go.com/issues/140
The change acknowledges specific position of stone inside of rendered square. Pre-renders all stones shifted 0.5 pixel to the left, which aligns with the way goban lines are printed. 
Also, since the stone alignment is done correctly, prerender function is able to accept fractional radius parameter. I used that opportunity to make radius scale proportionally to board size instead of leaving 1 pixel of margin at all times.
=> Align stone and line centers

src/components/Player/Player.styl, src/ogs.styl, src/views/Game/Game.tsx, src/views/Game/Players.styl
In light theme, the black player's name and rank are hard to read. In the dark theme, the White player's name and rank are almost impossible to read. Those are the main points.
I made a black and white name color in each theme. I made the player-name-container div also  subclass the color (I think that's how you describe it. It has been  a while since I did anything web). The color style attribute for `.[color] .player-name-container` is then themed. This implies removing the color responsibility from the `Player` class.
I removed the transparent border as it was creating an unsightly white line under the player boxes while in the dark theme. Also, I lessened the contrast between the score text and the background while in the dark theme.
=> Improved text contrast for player name and score (especially dark theme)

src/ogs.styl
So sorry for not being more careful originally. It would appear I am a bit rusty with this web stuff. Anyway, one of the color names had a typo. This didn't effect the look since at the moment what it defaulted to was essentially correct. Anyway this should be the last of it.
=> fixed variable name typo

src/views/User/User.styl, src/views/User/User.tsx
Each player's profile page displays the rankings of the players using a progress bar style UI element with a number indicating the progress. When the progress is less than 50%, then the number is supposed to be displayed to the right of the progress bar, whereas for more than 50% the number is on top of the progress bar. This ensures that the number doesn't overflow the progress bar element.
In the first case (<50% progress) the bar was invisible. This commit fixes that.
=> Fix bug #189 that caused rankings to display incorrectly

src/lib/ogs-goban/Goban.ts, src/lib/ogs-goban/themes/rendered_stones.ts
This fix I'm happy with. Hope you like it as well 😀 
https://github.com/online-go/online-go.com/issues/193
I thought about it for a while before understanding that the problem is in symmetry. For the higher resolution of mobile devices I can ignore the centre alignment (as the pixels are so small) and focus on a simple stone symmetry to make them look nicer. Visually this should revert the look and feel for mobile to before my original change, while keeping centre positioning for non-scaled devices. 
I believe that visually this is the best solution. Here are the examples:
=> Focus on symmetry for scaled stones rather than center placement.

src/components/Notifications/Notifications.tsx
Notification showed "You have timeout to make your move" instead of e.g. "You have 12 hours to make your move".
=> Fix timecop notification

src/components/ModerateUser/ModerateUser.tsx
Apparently, abstract React components don't actually define a componentWillMount method.
=> Fix for #395.

src/views/Game/Game.tsx
The Game view would attempt to display a ChatPresenceIndicator before the engine is initialised, causing the indicator to receive an undefined user id. We fix this by performing more checks before rendering the indicator.
Fixes #263.
=> Fix the ChatPresenceIndicator.

src/components/Player/Player.tsx
We were displaying PlayerDetails for guest players. (This kind of bug could have been prevented by the type system.)
=> Don't display PlayerDetails for guest players.

src/lib/goban.ts, src/lib/ogs-goban/Goban.ts, src/lib/preferences.ts, src/views/Game/Game.tsx, src/views/Settings/Settings.tsx
This new setting would disable the analysis mode (and conditional moves) in all of your games for you, no matter if the game was created with analysis enabled or not. By default, this setting is off, so everything works as before unless you change the setting for yourself.
This setting would only affect yourself, of course - that is, if the game has been created with analysis enabled, your opponent can still use the analysis feature, but you can't.
See <https://forums.online-go.com/t/option-to-always-disable-analysis-for-yourself/13408> for the motivation behind this setting. There has been some positive feedback (from two users) about the suggestion, not sure if that is enough or what the criteria for adding a new feature are?
Assuming for a moment, that this feature is considered …
=> Add "always-disable-analysis" preference

src/components/Player/PlayerDetails.tsx
Sometimes the backend uses an integer for the player.rating.professional field, and sometimes it uses a boolean. React displays integers literally, but treats false or null as a signal to not render the component. Hence, if the backend sends a zero to indicate that the player is not a professional, then that zero gets displayed literally.
=> Ensure that the player.rating.professional field is treated as a boolean in the PlayerDetails.

src/components/Modal/Modal.styl
Increased the space b/w the buttons and the sides of the modal.
Current & proposed looks:
For comparison, Facebook buttons are placed at the same distance from both edges of the modal:
same w/ Bootstrap:
=> Modal: Increased space b/w the buttons and the edges of the modal.

src/views/Play/Play.styl, src/views/Play/Play.tsx
Because all buttons have their icon on the left, "settings" should do too.
Current:
=> Moved Settings icon to the left (for consistency w/ buttons).

src/views/User/User.styl, src/views/User/User.tsx
On the user profile page, organizing content w/ vertical spaces makes it easier to read.
Current: 
=> User Activity: added vertical space b/w activity types.

src/views/Group/Group.styl, src/views/Group/Group.tsx
UI tweaks on group page:
Larger buttons (same size as "Full View" buttons) + space b/w buttons.
Spaces b/w admins + ":" on admin title like other titles.
Current:
=> Group: Larger bottons + space b/w admins.

src/views/User/User.tsx
There's currently a slight bug in the "you have won x games against ..." section:
This PR fixes that:
=> There's currently a slight display bug with the the "You have won

src/views/Supporter/Supporter.styl, src/views/Supporter/Supporter.tsx
No ad on support page.
Standard max-width
Added page title
Moved donation box to the top for improved visibility (on 2nd columns)
Added margin on button.
Current look:
=> Support page: improved UX

src/components/Player/PlayerDetails.styl, src/components/Player/PlayerDetails.tsx
Moved buttons and reduced space inbetween.
Current:
=> Player details: repositionned buttons.

src/views/Play/Play.styl, src/views/Play/Play.tsx
In this thread, some time ago, I suggested an alternative layout for the Game Creation Card:
https://forums.online-go.com/t/clearer-layout-of-game-finder-pane/12354
This PR implements that suggestion.
The rationale is explained in the thread.
As noted in the thread, the "computer" button is not a perfect fit for the layout logic, but close enough I think.
=> Different layout of Game Creation Card for improved intuition about what does what

src/components/NavBar/NavBar.styl
This change is barely noticeable but I think it is nice to have.
Current:
Proposed:
=> Left navigation: Black icons on hover.

src/views/Play/Play.tsx
Fixes https://github.com/online-go/online-go.com/issues/450
Show the rank in a separate column when listing custom challenges.
=> Dedicated column for rank in game list

src/components/PrivateChat/PrivateChat.styl
This pull request changes the title bar color of the private messaging window from "shade0" to "shade5" which is a lighter color in the light theme and a darker color in the dark theme. This improves the contrast between text and background.
Change was suggested on [this forum thread](https://forums.online-go.com/t/username-color-change-difficult-to-see-username-on-pm-box/14932/)
Screenshots of the title bars below
**Before:**
Light theme
Dark theme
**After:**
Light theme
Dark theme
=> Improve text visibility in private messaging title bar

src/components/FriendList/FriendList.tsx
Friends droplist shouldn't close when clicking the "Show offline" checkbox. Fixes #520.
=> Prevent friends droplist from closing

src/components/PaginatedTable/PaginatedTable.styl, src/components/PaginatedTable/PaginatedTable.tsx, src/views/PuzzleList/PuzzleList.tsx
Add optional props to PaginatedTable so that columns can be sorted
ascending/descending. Used by PuzzleList in response to #141.
=> Make PaginatedTable optionally sortable

src/components/RatingsChart/RatingsChart.styl, src/ogs.styl
Rejigged the theming of win/loss colours for the RatingChart so the strongest looking colour is always the one for stronger opponents.
Had to push this back into the theme itself.
=> Fix up win/loss colours so they are intuitive in both themes (#603)

src/components/GameList/GameList.tsx, src/components/GobanLineSummary/GobanLineSummary.tsx
Add a column displaying the board size to game lists in Observe Games, Overview, and Profile.
=> Add Size column to game screen #506

src/views/Tournament/Tournament.tsx
=> Sort players displayed in a tournament table so that dropouts are at the bottom (implements #611)

src/views/User/User.tsx
Previously, the games history table and the review games tables would show the players current ranks, instead of the ranks they were at when they played the game. This pull request displays the old ranks.
=> Displays players' rankings at gametime in the games history table (fixes Issue #364/#542)

src/views/Game/Game.tsx
Use innerText instead of innerHTML to retrieve edited messages.
=> Fix &nbsp; added to quickchat messages #613

src/components/Dock/Dock.styl
As per #618, it is irritating having the Dock pop out when the mouse strays on to it.
This PR delays the opening of the Dock by 2 seconds, enough for someone to click an icon if they know what it is without the Dock opening, and not too long to have to wait if you want to confirm what the items are.
=> Apply a delay to the pop-out-on-hover of the Dock (implements #618)

src/lib/popover.ts
As simple as the summary: put popups above a target element if they don't fit below as requested by config.bottom.
Before:
After:
=> Put the popup above the target element if it doesn't fit below - fixes #607

src/components/ChallengeModal/ChallengeModal.tsx, src/global_styl/misc-ui.styl, src/views/Play/Play.tsx
@anoek  How about this approach?
It seems to work, simplistically testing. 
I'm not sure what gotchas there are.
I'm not sure what "active_check()" is doing in ChallengeModal - I left it there.
I can see that there is a case in ChallengeModal after the user cancels:
(this.props.mode === "open" ? "challenges/%%" : "me/challenges/%%"),
where I don't know what the false side is for.
That is to say, I cancel the challenge in Play.tsx the same way the "Remove" button does, which always uses challenges/%% not me/challenges/%%
=> Do away with waiting dialog for live custom challenges.

src/views/Game/Game.tsx
Sorry about that - review mode got some extra buttons due to me not noticing it was rendered by a different routine.
=> BUGFIX: fix review controls, broken by control button placement enhancement (fixes #632)

src/lib/ogs-goban/Goban.styl
The gray shadow in the "Loading..." (and other messages) has bugged me, since it's lighter than the thing casting the shadow, and solid. This makes it a semi-transparent, dark shadow.
It's super minor and doesn't affect any functionality, but it's something that I've noticed for a while and I decided to finally do something about it. 😄
=> Add semi-transparent, non-gray shadow to message box

src/components/NavBar/NavBar.tsx, src/lib/preferences.ts, src/views/Settings/Settings.tsx
I never play tournaments and the tournament countdown in the top right gives me a little anxiety every time I look at it.
What about a setting to toggle the indicator on/off? It would look like this:
By default the tournament indicator is shown, but you can disable it if you really want to.
=> Add a setting to show/hide the tournament indicator

src/components/NavBar/NavBar.styl
Adds left padding to items in navbar's drawer. Please see the red and green bars in the image below to see the change in padding.
=> Adds left padding to items in navbar's drawer

src/views/LibraryPlayer/LibraryPlayer.tsx
Implements fix described in #710
=> dropzone only accepts .sgf file extension

src/components/IncidentReportTracker/IncidentReportTracker.styl, src/components/IncidentReportTracker/IncidentReportTracker.tsx
This is mostly to avoid hitting "Claim", then hitting it again because it didn't respond quickly, except it changes to "Good Report" as you do it.
=> Move "Claim" button away from "Good Report" button, hide moderator notes

src/components/TimeControl/util.ts
Either there has to be enough time for a game, or enough time for each move ongoing.
=> A better rule for detecting troublesome time settings

src/views/Game/Game.styl
As per #724
AdamR identified what was going on - nice work.
Idea for solution found here
https://bugzilla.mozilla.org/show_bug.cgi?id=1098151
=> Stop firefox from collapsing editable quick chat lines (fixes #724)

src/lib/ogs-goban/Goban.ts
Fixes #727. 
It looks like after placing a stone but before submitting it, `this.engine` refers to the game tree updated with this new move. 
Because of this, `this.engine.otherPlayer()` will actually refer to the current player after a stone has been placed but before submitted. However, if there are handicap stones left to place, the engine will know this and `this.engine.otherPlayer()` will now refer to the actual other player. So I have added an if-statement that checks if there are handicap moves left and if so sets color to `this.engine.player`.
=> fix handicap stone color bug

src/components/GameAcceptModal/GameAcceptModal.tsx, src/views/Play/Play.tsx
People still fall for trick custom komi.
It appears these get obscured by fast game settings that the acceptor doesn't mind.
So here is a separate warning.
=> Tweaked komi warning

src/lib/goban.ts, src/lib/ogs-goban/Goban.ts, src/lib/preferences.ts, src/views/Settings/Settings.tsx
As recently discussed, and comes up from time to time, it irritates some players to have voice countdown during main time for Byo-yomi and Canadian.
So here is an option to turn that off. 
Because Dwyrin and Collosiuss both complained about this, and they are not great setters-of-settings, I have made it the default to have it turned off, so they get to experience the change for good without effort on their part.
=> Added option to turn off countdown in main time for byo-yomi and canadian

src/components/PaginatedTable/PaginatedTable.styl
Lines frequently broke mid-word on pages like /groups and /puzzles. This was due
to the word-break property being set to break-all. This commit fixes the issue
by removing the setting of this property. word-wrap is still set to break-word,
so extremely long words should still break.
=> Fix mid-word line breaks in PaginatedTables

src/views/Game/Game.tsx
Background: whenever Dwyrin plays on OGS he opens the settings and turns down the volume.
Sometimes he mutters about how it's always too loud.
Although I have mentioned it, he doesn't seem to catch on that you can save the setting using the archaic "save" icon.
So that got me thinking "Why do we need a save option?  Why would you change it and _not_ want it to persist".
Hence this PR: just persist the volume setting.
=> Always save a volume setting change

src/views/Play/Play.styl, src/views/Play/Play.tsx
Folk are still missing the warning that they are joining a game with tricky settings.
This change:
1) Moves the warning triangle icon over next to the accept button
2) Causes a popup as they mouse over the cell with the button in it, so they can't press the button without seeing the warning details popup.
=> Better challenge cheat warnings

src/components/RatingsChart/RatingsChart.tsx
Fix #466 
force ratings_x axis range to span full months.
remove today-related logic, i.e. treats current month like past months (code not removed but commented out for eventual easier reuse)
=> Kind of lossy fix to the ratings bar chart (issue #466)

src/components/RatingsChart/RatingsChart.tsx
fix #811
My mistake. I missed the part of the code that recomputed the bar chart in the onTimelineBrush.
=> fix #811: Bar chart is wrong when making a time selection

src/components/RatingsChart/RatingsChart.tsx
Substitute hard coded 60 to win_loss_bar_height value where it looked
pertinent. This leads to better spacing between each element.
Change clipPath height to the svg height. Fix #810
=> Fix #810 and various cometic changes for win-loss bar chart

src/components/ChallengeModal/ChallengeModal.tsx
Fixes  #842. Removes a line that conditionally renders the disable analysis checkbox so that it is always rendered regardless of challenge mode. I've also dedented the jsx that was previously enclosed in the condition.
=> let vs computer challenge modal have disable analysis checkbox

src/views/Play/Play.styl
Fixes  #845 by changing some styles on the cheat-alert class. See screenshot below.
=> fix cheat-alert alignment style issue

src/views/Play/Play.tsx
As discussed in https://forums.online-go.com/t/please-remove-that-for-games-without-handicap/22447?u=flovo there is a bug for the "Custom handicap" warning when using another language than English.
When using another language, every open challenge had the "Custom handicap" warning attached.
This should fix this.
<details>
<summary>Screenshot</summary>
Before:
After:
</details>
=> Fix for incorrect custom handicap warning

src/views/Group/Group.styl, src/views/Group/Group.tsx
At the moment, the group chat is only accessible in the chat view. Adding a chat window to the group page could increase the usage of group chats and increase the activity of users within groups.
This pull request adds an EmbeddedChat window to the group page. 
It is basically a copy and paste of the implementation on the tournament page.
<details>
<summary>Screenshots</summary>
</details>
=> Add chat window to group view

src/views/Game/Game.tsx
Don't switch "Play" mode after the user disabled AI review.
When using "Disable AI review" we shouldn't change the game mode, since the user probably want to keep doing what they were on.
Fix for https://github.com/online-go/online-go.com/issues/858
=> Don't jump to last move when disable AI reveiw

src/views/Game/Game.tsx
This is a fix for https://github.com/online-go/online-go.com/issues/856
When the user disables AI review in Game view, the AI marks are only deleted for the current move. For other moves the marks are still visible.
To remove the AI marks for all moves we have to go over the whole tree.
=> Revome marks from all moves when AI review disabled

src/views/Game/AIReview.tsx
The AI review is sometimes full of move suggestions (percent points). Many are only poorly explored.
This is a suggestion to limit the shown variations to variations on which leela spend more than 10% of her total visits.
At this point the pps are only shown if it's
- the played move,
- the AIs top suggestion, or
- at least 10% of the total visits were spent on the particular variation (or 50 visits)
- 26 visits for Supporter (250 total),
- 50 visits for Kyu Supporter (1000 total), 
- 50 visits for Dan Supporter (800 total), or 
- 50 for Pro Supporter (2000 total).
Tested for [Kyu Supporter](http://online-go.com/game/18734180), [Pro Supporter](https://online-go.com/game/18588826) and [Basic Supporter](https://online-go.com/game/19093854) level. There are still many visible variations …
=> limit the visible AI suggestions to well explored variations

src/lib/ogs-goban/Goban.ts, src/views/Game/AIReview.tsx
resolves online-go/online-go.com#874
I also changed the normalization of the heatmap to be relative to total visits. With this it's easier to see how many visits the AI spent on a variation. 
1) Policy network:
2) Visits:
3) Visity / total visits
=> Use visits for heatmap instead of policy network

src/components/ServerTimeDisplay/ServerTimeDisplay.styl, src/components/ServerTimeDisplay/ServerTimeDisplay.tsx, src/components/ServerTimeDisplay/index.ts, src/views/Overview/Overview.tsx, src/views/User/User.tsx
Display current server time above active games on profile page as per [Issue #849](https://github.com/online-go/online-go.com/issues/849)
=> Add server time display

src/views/Game/Game.tsx, src/views/Game/Players.styl
resolves gh-882
The captures/points don't reflect the result of the SE, so best is to hide it.
=> Hide captures/points while score estimator active

src/components/Notifications/Notifications.styl, src/components/Notifications/Notifications.tsx
I added a dark theme for the turn indicator
and a grayed version if the turn counter shows `0`
On the dark theme the turn-indicator had a bright white border (#fff). That's much brighter than everything else on the dark theme (text color #ddd)
I changed the color of the turn-indicator circle to match the text-color of the theme. The number within the turn-indicator now has the same color as the top bar.
Since the border would have the same color as the background for both themes, it's now just set to be transparent.
When the turn-indicator  shows `0` it has the same color as the friends icon when no friends are online.
=> Turn-indicator: theme update

src/components/Chat/Chat.tsx
Now the chat recognises when an username is followed by a `,` or a `'` as a mention of username.
If the user is mentioned as `player 1`, now this is a mentioning as well.
I also made the space between `player` and the player_id optional. 
Same for `issue` and `pr`.
This still leaves some mentions undetected:
In German `Adam's` would be `Adams` (without Apostrophe). I don't know if there is any language which adds letters at the beginning of a name to indicate anything.
It could be better to remove the checks for word boundaries entirely.
=> Chat improvements

src/views/Joseki/Joseki.tsx
These changes are intended to prevent the two Joseki related UI Sentry alerts that I have seen.
Each due to apparently-undefined variables that I hadn't realised could be undefined at that point.
=> Some defence against unexpected nulls

CONTRIBUTING.md
Instructions about how to point a local OGS client environment at the beta Joseki Explorer server.
=> How to point at the beta joseki explorer server

src/index.html
When running Chromium with WebAssembly disabled, the `WebAssembly`
global is still defined, and so a `typeof` check isn't quite enough.
Instead, let's try to allocate a Memory region. This operation will
fail with `RangeError` if WebAssembly is disabled.
See: https://github.com/openbsd/ports/blob/77b70736cf794ac0ff7c420e4321017471799f6d/www/chromium/files/chrome#L57
=> Make WebAssembly feature detection more robust

src/components/PrivateChat/PrivateChat.styl, src/components/PrivateChat/PrivateChat.tsx, src/views/Game/Game.tsx
In the forum it was mentioned that the private-chat window is disturbing the zen experience (minimal disturbance). 
https://forums.online-go.com/t/hide-messages-while-being-in-zen-mode/23026
This should hide the private-chat window while Zen mode is active. 
Hopefully superchat still shows up. (If I interpret it correctly superchat means a moderator wants to talk to you officially). Obviously I haven't tested if moderator chat is still visible.
=> hide private-chat in zen mode

src/components/TimeControl/util.ts
Fixes #915 
-removed if(days) which was returning false when days===0
=> fixes #915 - Vacation Day Accrued not displaying for 0 Days

src/views/Joseki/Joseki.tsx
... otherwise we end up displaying "undefined".
=> Bugfix: make sure best_attempt is null when there hasn't been one.

src/views/Joseki/Joseki.tsx
The goal is to ensure that we don't sneak a filtering change on them, but that they also see the (new) results without having to select them, because that's what you'd typically want: results visible.
This change makes it so that
- If they enter Play mode with a Filter already set then they see the Results
- If they enter Play mode without a Filter set, so we force Joseki filter, then they see the filter pane, but it swaps to Results after they start playing.
=> More intuitive and self-discoverable behaviour of Play Mode extra info

src/components/Chat/Chat.tsx, src/components/Player/Player.tsx, src/lib/player_cache.ts, src/lib/tabcomplete.ts
Instead of showing `player 1` when someone links a user profile, show the username instead.
This pull request needs a close review. I'm not sure if I broke anything in a subtle way (I encountered no obvious problems)
- Replace `<Link>` with `<Player>`: I had to enable CacheUpdate to get the username. (There are repeated requests if no user with id exists, else it looks like every user is requested only once)
- Add another Chat shortcut `@" "` to allow link mentions by name. I had to modify [Player.tsx](src/components/Player/Player.tsx) and [player_cache.ts](src/lib/player_cache.ts) to allow for fetching of `user` by username.
- Modify [tab-completion](src/lib/tabcomplete.ts) to automatically enclose completed usernames in `@" "`. 
(I tried to enclose every typed username after it's …
=> Show username in chat instead of player 123

src/lib/rank_utils.ts
When the rank of a player is near threshold, there is a discrepancy between the PlayerDetails (rank rounded to 1 decimal point) and the rank displayed in [] behind the players name (rank ceiled with no decimal places)
This came up in the [forum](https://forums.online-go.com/t/rank-wrong-presentation-calculation-solved-rounding/23343) for a player whose precise rank would be (7.0301…k). His rank is shown as [8k] and 7.0k in PlayerDetails, which led to enough irritation to create a forum post.
My proposal is to floor/ceil the decimal rank as well (to 7.1k in this case). It's more consistent and should mitigate such inconsistencies in the future.
Before:
After:
=> Always floor/ceil rank

src/views/Game/Game.tsx
This is a needed step to enable different layouts for zen mode in
portrait and landscape mode. (as mentioned in #953)
With this change `view_mode` stores the screen orientation, and `zen_mode` if zen mode is enabled.
=> seperating view_mode and zen_mode

src/views/Game/Chat.tsx
Let's use the upgraded chat_markup in game chat as well
The difference of both functions (before I made all the changes to Chat.chat_markup) was:
```diff
< export chat_markup(body, extra_pattern_replacements?: Array<{split: RegExp; pattern: RegExp; replacement: ((m: any, idx: number) => any)}>): Array<JSX.Element> {
---
> export function chat_markup(body, extra_pattern_replacements?: Array<{split: RegExp; pattern: RegExp; replacement: ((m: any, idx: number) => any)}>): Array<JSX.Element> {{{
8a9,11
>         {split: /(player [0-9]+)/gi, pattern: /(player ([0-9]+))/gi, replacement: (m, idx) => (<Link key={idx} to={`/user/view/${m[2]}`}>{m[1]}</Link>)},
>         {split: /(issue [0-9]+)/gi, pattern: /(issue ([0-9]+))/gi, replacement: (m, idx) => (<a key={idx} target="_blank" …
```
=> use same chat_markup for game chat and Chat

src/components/Player/Player.tsx
The joseki code is using -1 as fallback userid.
The changes I made earlier to [Player.tsx](https://github.com/flovo/online-go.com/blob/e7ca023e62d71641381f5355e9aeaa556798df49/src/components/Player/Player.tsx) caused notpositive ids to be interpreted as usernames and tried to fetch users with that name (what luckily failed).
This pr restores the original 'do nothing' behavior for invalid (not positive) userids again.
=> Correct Player id handling in Player React

src/components/JosekiVariationFilter/JosekiVariationFilter.tsx
**Requires server 5e5aecbb**
Folk have been saying they want to search by source alone, etc.
Fair enough too.
This change lets them do that.   
If we get bazillions more sequences, there may be performance issues to be fine tuned.  Worst case scenario will be  "to get better performance, select a tag to filter by".
=> Allow user to select filters that don't have tags included. 

src/views/User/User.tsx
Games with no time limit (`time_per_move===0`) were accidentally shown as blitz games in the game history on the profile page. This pr should fix it, showing it as correspondence.
Using `time_control_parameters.speed` as default source should improve the detection of the right game speed further.
Additionally, I added checks to ensure that negative `time_per_move` isn't interpreted as “Live”, but I doubt we get negative values. If neither corr, live nor blitz is detected, no icon will be displayed for game speed.
=> Fix game history speed icon for no timelimit

src/components/Chat/Chat.tsx
Fixes #979 
I accidentally removed the syntax for player references used by review, when the control is passed to another user. This adds the syntax again.
=> chat-subs: add player syntax review control passed

src/views/Joseki/Joseki.tsx
Caching broke Play mode.
This disables caching except for Explore more, where it's most useful anyhow.
Some code resequencing needed to make Play mode work with caching (due to cache causing move processing in-line instead of after call to server).
=> Quick fix for Play mode, broken with caching

src/views/Game/AIReview.tsx
In my opinion, a game changing move is a move which deviates much from perfect play. Since we don't know what perfect play would look like, we approximate it by using an AI. 
Positive win rate changes are an artefact of the limited AI, not a sing for a game changing move. Therefore, we shouldn't include positive changes in the Top 3. (positive changes are rarely in the top 3 anyway, since their abs is usually small)
=> Change top 3 game changing moves to worst 3 moves

src/components/RatingsChart/RatingEntry.ts, src/lib/rank_utils.ts, src/views/User/User.tsx
Fixes https://forums.online-go.com/t/wins-losses-against-stronger-weaker-opponents-again/23952?u=flovo
In 
https://github.com/online-go/online-go.com/blob/ac381c26f952e344574b5a69e7e8d3d340b12c7f/src/components/RatingsChart/RatingEntry.ts#L106
handicap is passed as string, resulting the math going wrong. (effective rating ~ real rating)
Besides the coloring on the game history used the real ratings to determine stronger/weaker.
- move the code to determine the effective outcome to rank_utils.ts
- use the new code for rating graph
- use the new code for game history
=> Fix bug in handicap adjustment for rating graph

src/components/Clock/Clock.styl, src/ogs.styl, src/views/Game/Players.styl
Fixes #1005 
Make the "white player container" have more whiteness, and be whiter at the bottom where the player name and score is, so it is more obvious which container is for "white"
Current dark game underway
New dark game underway
Current dark game paused
New dark game paused
Current light game underway
New light game underway
Current light game paused
New light game paused
=> Player-container colour tweaks for improved "white" container

src/views/Joseki/Joseki.tsx
Fixes (hopefully) the problem of the jwt not being ready occasionally, and the potential problem of users changing their identity after starting to use OJE.
(Note that the front end will still have the wrong idea about their permissions if they change to an account with different permissions, but this would be very rare, and caught server-side anyhow).
=> Read JWT from config every request

src/components/MiniGoban/MiniGoban.tsx, src/components/Player/Player.tsx, src/components/Player/PlayerDetails.tsx, src/components/ProfileCard/ProfileCard.tsx, src/lib/preferences.ts, src/views/Settings/Settings.tsx, src/views/User/User.styl, src/views/User/User.tsx
Some players (including me) find it more relaxing to not see their opponents' or their own rank and rating.
This commit adds a setting called "Hide ranks and ratings".
When the setting is activated:
* Ranks next to player names are hidden
* Ranks in the mini goban are hidden
* Ranks and ratings in the player details and profile card are hidden
* Ratings in the rating table on the profile page are hidden
* The rating chart on the profile page is hidden
* There is a button on the profile page that toggles the visibility of the rating chart and rating table, as well as the rank next to the player name.
=> Add a setting to hide ranks and ratings

src/components/RatingsChart/RatingEntry.ts, src/views/User/User.tsx
I confused the stronger/weaker labels. The coloring of all games in history and graph where reversed. 
This changes the colors back to the right ones.
=> Correct stronger/weaker labels in game history and rating graph

src/components/Player/Player.tsx
Fixes #1003
- check if right mouse button is part of click event, and do nothing if it is.
Checking buttons bitmap: https://www.w3schools.com/jsref/event_buttons.asp
as fallback check button value: https://www.w3schools.com/jsref/event_button.asp
Left- and middle-button are still working.
- Desktop:
- Android:
=> Reenable context menu when right-click on usernames

src/views/Joseki/Joseki.tsx
Provide a right arrow button with right arrow key binding to let users go forwards again through moves that they just backed up from using the left arrow.
=> Right-arrow to move back forwards through previously visited moves

src/views/Joseki/Joseki.tsx
Fixes a bug where "pass" gets given to goban as a location and results in a random stone being placed, when the person tries to forward-arrow through a pass.
Play a pass instead, when the placement is "pass".
=> Joseki support going forwards through pass (bugfix)

src/components/Chat/Chat.tsx, src/components/PrivateChat/PrivateChat.tsx
Replace tsumegodojo with tsumegododo as proposed in chat.
This is a rather aggressive implementation, not only replacing URLs but all occurrences of tsumegodojo.
It works in chat and PMs
=> replace tsumegodojo with tsumegododo in all chats

src/views/Game/Game.tsx
Fixes #1053
Make the accept-clock visible to the moderator (noting that they can't press the button on behalf of the players, largely because goodness knows if that would work).
=> Show moderator the accept clock 

src/components/Clock/Clock.styl, src/components/MiniGoban/MiniGoban.styl, src/components/MiniGoban/MiniGoban.tsx, src/components/Player/Player.styl, src/components/Player/PlayerDetails.styl, src/components/Player/PlayerDetails.tsx, src/views/User/User.styl
Long usernames are disrupting the layout at several places.
This PR tries to fix the layout. 
Related to:
https://forums.online-go.com/t/clock-hard-to-read-with-long-usernames/25747?u=flovo
=> Long usernames

src/components/NavBar/NavBar.styl, src/components/NavBar/NavBar.tsx
Fixes #
It is not very noticeable but I see it so I wanted to fix it.
Icons are closer to text for Tournament, Ladders, Groups... for other menus on hover there is an underlined space before the text.
- removed space before menu text (in HTML)
- added margin after icon (in CSS)
=> Made left navbar spacing b/w icons and text uniform.

src/views/Group/Group.tsx
On the forum, we got multiple [requests](https://forums.online-go.com/t/kgs-style-rooms-in-groups/25191/5?u=flovo) to make the online status of group members visible. 
This adds the online indicator to the members list on the group page.
=> Make online status visible on groups member list

src/components/GobanLineSummary/GobanLineSummary.styl
Limit the length of game and user names on the game-view page. 
A user complained at the [forum](https://forums.online-go.com/t/limit-length-of-game-names/26174?u=flovo)
This PR limits the width of the game and user name column to 13em.
=> Limit the length of game names in game list

src/views/Settings/Settings.tsx
The selection of a new value wasn't accepted by the selector.
It turned out that the `ev` value is a number, not an Object.
=> fix settings thumbnail list threshold

src/views/Settings/Settings.tsx
The ideal number of MiniGobans depends on the usecase, display size, …. In my case 8 would be a good number (2 rows of 4 games on the home page), but it isn't in the list. A numeric input is more flexible.
Conflicts with https://github.com/online-go/online-go.com/pull/1083. `updateGameListThreshold` works in this case as expected.
=> Alernative: Use numeric input for thumbnail list threshold

src/views/ObserveGames/ObserveGames.styl, src/views/ObserveGames/ObserveGames.tsx
There is nothing special about the numbers in the drop down list. Just make it numeric input.
=> Make page size of ObserveGames numeric input

src/views/User/User.tsx
This prevents the page from reloading all resources.  At the moment, those links cause the browser to reload everything.
=> User: Make links <Link> instead of <a>

src/views/Joseki/Joseki.tsx
Disable joseki comment entry when user doesn't have edit permission
... more relevant when recent Joseki Server commit is merged, disabling noobs from commenting
=> Disable joseki comment entry when user doesn't have edit permission

src/views/Tournament/Tournament.tsx
The Tournament Director actions "Kick", "Disqualify", and "Adjust Points" are not always visible.
1) Go to the group page.
2) In the open/ongoing tournaments list, click on a tournament you are TD in.
3) The Tournaments page will open.
4) Click on a participants username
5) Observe: The buttons "Kick", "Disqualify", and "Adjust Points" are missing in the PlayerDetails.
If you go to the tournaments page by any other means (refresh the page for example), the controls are there.
Move `setExtraActionCallback(this.renderExtraPlayerActions);` from `UNSAFE_componentWillMount` to `componentWillMount`.
I hope this hasn't any side effects I'm not aware of.
=> fix: TD actions not always visible

src/views/Joseki/Joseki.tsx
Fixes #
Being unable to go fowards over the same variation after going backwards from a linked position.
Save up the route taken going backwards past the beginning of the trace.
=> Fix joseki arrows going backwards from a linked position then forwards

src/components/JosekiStatsModal/JosekiStatsModal.tsx
Fixes #
* Axes were always labelled dark, even on dark background
* There are occasional spurious day-records with zero in them.  Don't display those.
* Label axes color based on OGS theme selected
* Don't display zero day records
=> Fix up Joseki stats chart axis label theme

src/components/Chat/Chat.tsx, src/components/Chat/ChatDetails.tsx, src/components/Chat/ChatIndicator.styl, src/components/Chat/ChatIndicator.tsx, src/components/Chat/ChatList.styl, src/components/Chat/ChatList.tsx, src/components/Chat/index.ts, src/components/ChatPresenceIndicator/ChatPresenceIndicator.tsx, src/components/ChatUserList/ChatUserList.tsx, src/components/NavBar/NavBar.tsx, src/lib/chat_manager.ts, src/lib/preferences.ts, src/views/Game/Game.tsx, src/views/Settings/Settings.tsx
Adds a chat notification Icon to the NavBar. The Notification Icon shows the total count of unread messages and if the user is mentioned in any chat room selected by the user.
---
To achieve this, the following changes are made:
-   The chat receiving logic moved to a central location (`chat_manager`), to keep the different components in sync. 
The `chat_manager` seems to be a good place for this. It's called chat_manager after all.
-   The read timestamp for each chat room is stored in local storage, to be able to notify the user if there was chat activity while they were offline. Due to backend limitations the backlog is limited to 40 messages.
-    A copy of the Chat Room List (left hand site on Chats page) is used as dropdown for the Chat indicator. A click there on the chat room …
=> Chat indicator

src/views/User/User.styl, src/views/User/User.tsx
Fixes #1092
- Add a new css class .library-hidden-result that is used for all results in the game history when ratings are hidden.
=> Hide game history colors when ratings are hidden

src/views/Settings/Settings.tsx
Fixes: Thumbnail threshold setting didn't save 0. When `parseInt` evaluated to 0 (false), we skipped the save settings part.
- Check if `parseInt` evaluates to NaN. `parseInt(undefined)` and `parseInt("")` both evalutate to NaN, therefor we can skip the check for undefined.
- Also, when the preference is changed, set the text field to the stored value. This makes it more transparent, which value is used.
=> Fix: Make threshold settings accept 0

src/views/ObserveGames/ObserveGames.styl
Fixes #1118. This should prevent the reported line breaks in the head line of Observe games.
=> fixes #1118: prevent linebreak in headline on observe games

src/lib/tabcomplete.ts
Fixes: In some cases `matchFullName` matched multiple different usernames. This resulted in various occurrences of `@" /0"`. The result was either additional `@"/0"` cluttering the chat line, or worse, the chat substitution to interpret is as user 0. The later results in hiding the username.
This fix prevents the mismatch from happening. 
----
The error happens if the input is 1 char shorter than any username. In this case `lastIndexOf` retruns -1, since the username isn't a substring of input. Since input.length was 1 letter shorter than the username, the result of `input.length - value.length` was -1 (equal to `lastIndexOf`). 
An additional check if the username is a substring of input solves this issue.
=> fix tabcompletion match every username thats's 1 letter longer than input

src/views/Puzzle/Puzzle.tsx, src/views/PuzzleList/PuzzleList.tsx
Fixes #1112
- Save a visited puzzle of collection in local storage
- If a collection is found in local storage, navigate to it instead of the starting puzzle.
=> Navigate to last visited puzzle of collection

src/components/ChallengeModal/ChallengeModal.tsx
Based on: https://forums.online-go.com/t/cant-start-live-bot-games/27265/4, creates simple validation when trying to create challenges using an invalid custom komi.
- defaults the custom_komi to 0
- Prompt user to correct custom komi settings in case they sent a null value (probably from bad session having being saved in the state)
=> Default custom komi value

src/index.html
… so it doesn't catch our eyes if page loads fast
Fade the bouncer in, so we don't see it at all if the page loads fast (therefore don't have our eyes caught by it) and so it's appearance is gentler when it arrives.
=> Give bouncer a soft start

src/views/Supporter/Supporter.tsx
Fixes #1132 
Currently any price >= 1,000 will drop all digits below the thousands place. 
This PR fixes the regex responsible.
=> Fix #1132, Display correct pricing information

src/components/Chat/Chat.tsx
When clicking on the chat indicator on a channel, it brings you to the chat page. If the channel is not in joined channels, the chat page is blank. This PR prevents the blank page by making sure we load the active channel,
Fixes:
https://forums.online-go.com/t/tournament-chat-channels-have-to-join-to-see-the-messages-multiplying-messages/28159
https://forums.online-go.com/t/problems-bugs-in-group-chat/28168
https://forums.online-go.com/t/chat-notifications-bugs-and-weirdness/28120/2?u=flovo
=> Prevent blank chat when opening chat using the chat indicator

src/views/Joseki/Joseki.tsx
Fixes: sometimes the URL doesn't update when the user uses arrow keys to move around the joseki
Use the most recent value we have for the current position.
=> Joseki: Make sure that the URL update is using the most recent position id

src/components/MiniGoban/MiniGoban.tsx
Switch the vertical current score display on mini goban, as on my/observe games page, to use ngettext so as not to say "1 points". Also changed state object to contain the raw number and string building in the view as I think that's better practice, don't know what you OGS folks think. Assumes numbers come before unit, which may not be valid in all languages.
Fixes: silly looking "1 points"
=> SingularPointMiniGoban

src/lib/chat_manager.ts
Last weeks https://github.com/online-go/online-go.com/pull/1160 had a bug, resulting in (almost) all messages are considered from blocked users. Therefore they didn't increased the unread chat count and mentioned status.
This time I checked it both ways. 
1) Blocked messages don't count
2) Not blocked messages count
=> chat_manager: fix ignoring of blocked users

src/components/JosekiAdmin/JosekiAdmin.tsx, src/views/Joseki/Joseki.tsx
The recent "dump outdated server requests" check exposed a bug from Joseki Admin that was calling loadPosition with an integer instead of a string, resulting in positions not loading from the "updates" table.
Convert to string.
=> Fix link to position from "Updates" table

src/index.html
Fixes #1047 
This simply sets the OGS light/dark theme preference to match the user's own operating system's theme preference, only for the first visit. 
Note that afterwards if the user changes the light/dark theme from within OGS, that preference will remain on subsequent visits.
EDIT: To be honest I don't know if we want to sync up the OGS theme with the user's OS theme on _every_ visit, or just the first visit, or even perhaps implementing a new option entirely called "Set OGS theme to sync with OS". In any case for this PR I just went with first visit only sync.
=> Set OGS theme to match user's OS theme on first visit only

src/components/Chat/Chat.tsx
I was looking at #946 and while I couldn't reproduce the error he was having, I did nevertheless find the rtl (right to left reading languages) chat channels a bit buggy. 
Initially when we click on an rtl chat channel (like, say Arabic), the text is displayed correctly, sticking to the right hand side. As soon as we scroll, the div with the `chat-log` class loses the `rtl` class, which ends up displaying the text messages sticking to the left hand side (incorrect for rtl languages).
This fixes it.
=> Prevent rtl chats from losing rtl class when scrolled

src/views/Game/Game.styl, src/views/Game/Game.tsx
When games became un-anullable, we lost the ability to see if they are annulled by hammer status.
Make the hammer fall when the game is annulled, so we can see that it has been done.
Also fix up the status of the Dock after annullment has happened (the info and hammer status need to be refresher)
=> Anull hammer fall

src/views/Joseki/Joseki.tsx
Fixes #
If you enter a bad URL looking like a joseki position, the server will respond with an error.
This is caught by the joseki client code, but it leaves the throbber running, so the user has no idea that actually there's nothing else going to happen.
Turn off the throbber when a server error is received.
=> Don't leave joseki throbber running after a server response we couldn't parse

src/components/GobanThemePicker/GobanThemePicker.styl, src/components/GobanThemePicker/GobanThemePicker.tsx, src/lib/configure-goban.ts
**WARNING: This PR is co-dependant with [this one](https://github.com/online-go/goban/pull/6) on goban**
---
The basic idea is to allow users to style their goban with a custom image in the form of supplying a link to an external picture. 
- I have changed the look of the plain board preview in the selector, to more intuitively represent the cutomizable nature
- Upon selecting the custom option an input form appears together with the color selectors, once the text is replaced with an image link, it will automatically update the board background. 
- in the future I was thinking of creating a similar option for the stones, together with two buttons allowing for playing one-color-go and blind-go easily. Let me know what you think about that.
---
Please note, this is my first barbecue with …
=> External goban image

src/views/LearningHub/LearningPage.tsx
=> Make 'Great job!' and 'Puzzle failed' strings translatable

src/views/Overview/Overview.tsx, src/views/User/User.tsx
Fixes #1180 
- Adds the number of active games in parentheses to `User` and `Overview` views
=> Show number of active games in User and Overview views

src/views/Game/AIReview.tsx
Fixes #785 
Most of the highlighted file changes are simply due to reindentation. But essentially I'm wrapping the code where we generate the AI marks in a for loop to use the AI generated branches from previous trunk moves as well, to fix the bug (see fillAIMarksBacktracking method).
You can test this by visiting http://dev.beta.online-go.com:8080/game/8598 @ move 2/3 (where the triangle move is part of an AI branch). Please use the account username: huh, password: woo to view the game since it is private.
=> AIReview: draw out ghost branch even when on trunk

src/views/Overview/Overview.styl
Games list on home and profile page was cropped on the left and right.
With this change, horizontal scroll is available when the list is wider than the available space.
=> Fixing games list wider than view

src/views/Game/Game.styl
There is a strange margin in portrait zen mode:
This PR changes the css to maximize the goban in zen mode when possible.
=> Maximise Goban in Zen Mode

src/views/Game/Game.tsx
In portrait zen mode, ply controls are missing right now. 
Since they are needed to Submit move and resign, we should show them there as well.
=> Show play controls in portrait zen mode

src/views/Game/Game.styl
A suddenly appearing button has the potential to break concentration and
therefore, is not zen.
=> Hide accept undo button in zen mode

src/views/User/User.tsx
Fixes https://forums.online-go.com/t/rank-display-disabled-and-profile-page/28624
- Adds win/loss colors to games in user game history table when ranks are hidden without revealing the relative strength of the opponent
=> add win/loss colors for games when ranks hidden

src/ogs.styl, src/views/User/User.styl, src/views/User/User.tsx
Put an icon next to the winner's name in the game history table, so you can see at a glance who won.
Dark:
Light:
=> Use an icon in the game history table to show clearly who won in each game

src/lib/misc.ts, src/views/Game/Game.styl, src/views/Game/Game.tsx, src/views/User/User.tsx
Fixes #1244 
- In the Game view, strikethrough the game result and add "GAME ANNULLED"
- Strikethrough the game result in the Game History pane if the game has been annulled.
=> Mark annulled games more clearly.

src/views/User/User.styl, src/views/User/User.tsx
As discussed in this thread: https://forums.online-go.com/t/update-of-game-history-table/31742
* Get rid of the "Black" and "White" player columns, and have just "Opponent", for major redundant information removal
* Have a column for the colour of the current player
* Reorder the columns to make this look good
* Grey-out annulled games
=> Revamp Game History Table

src/ogs.styl, src/views/User/User.styl
In the thread on this topic, it was complained that the opacity of annulled games in the game history table was not enough - I believe this is referring to light mode, and I agree with that.
Theme the opacity, so it can be greater in light mode.
=> Put annul-opacity (in game history table) into the theme

src/components/Chat/chat_markup.tsx
Fixes https://github.com/online-go/online-go.com/issues/1251
- Replaces email address regex with one that properly rejects a URL that contains `@`
=> Fix email address regex in Chat

src/views/Game/Game.tsx, src/views/Game/GameTimings.tsx
As per Vsotvep request here: https://forums.online-go.com/t/move-timing-go-public/31770/9?u=eugene
Calculate and show how much time was spent in the game after the last move was played (this is either score phase or timeout time)
=> Added display of the time of last thing that happens 

src/views/User/User.tsx
The recent changes had two problems raised:
1) We can't see the rank of the player at each game anymore
2) It's not clear who's colour the colour indicator is
https://forums.online-go.com/t/update-of-game-history-table/31742/91?u=eugene
=> Show the user's rank for each game in the history table 

src/views/Game/GameTimings.tsx
The code was inadvertently shifting the moves array passed in on props.  Naughty naughty.
Don't do that.  Make a copy first.
=> A further fix for GameTimings in Japanese Handicap mode

src/views/User/User.styl, src/views/User/User.tsx
https://forums.online-go.com/t/update-of-game-history-table/31742/113?u=eugene
Don't let the first column wrap (note it has to be one column so that the header "User" spans it).
=> Prevent the user's rank from wrapping in game history table.

package.json, yarn.lock
Fixes #1280 
When upgrading webpack (00b295ef6aa676ad5264c8f49e9c57e9d365b5b2) `stylus` was upgraded from `0.54.7` to `0.54.8` which broke `embedurl()`: https://github.com/stylus/stylus/issues/2546
This caused the embedded `ogs-font.woff` data in `ogs.css` to be corrupt, leading to:
`Failed to decode downloaded font: data:application/font-woff;base64,...` and 
`OTS parsing error: incorrect file size in WOFF header` in the console.
This change downgrades `stylus` to `0.54.7` which fixes the problem.
=> Fix ogs-font loading issue due to stylus bug

src/views/Game/Game.styl
When viewing my own games I noticed that there was horizontal scroll on mobile. See this screen capture: https://streamable.com/pbzr4e
It looks like the implicit left/right margin in `analyze-mode-buttons` was causing the issue:
This fixes the problem by explicitly only setting top/bottom margin.
=> Fixed oversized element causing mobile horizontal scroll

src/views/Game/Game.tsx
I noticed that in uploaded sgf games if you entered analyze mode (e.g. pressed left arrow a few times) you couldn't go back to the end board state by pressing "Back to Game" like you normally can in games. For example: https://online-go.com/game/28512079
I found two ways to go back to the end game state:
1. Refresh the page.
2. Enter score estimation and then press "Back to Game".
When looking at the code I noticed we also disabled the escape key from returning to end game state for these games. I have enabled both of these features for uploaded sgf games in this diff.
I wasn't able to test this as it seems the dev server doesn't support uploading sgf's, but it should follow similar logic to the "Back to Game" button press when leaving score estimation mode (i.e. return to "play" mode and …
=> Enabled escape and 'Back to Game' for uploaded sgf games

src/views/Game/Game.tsx
Fixes #881 
Made the following changes to fix wrong display of final board after using some features:
- Sync state after disabling AI review.
- Remove `this.goban.engine.clearRemoved();` when exiting scoring estimate mode, which seemed to corrupt the final board state requiring a refresh to fix.
Also changed the "Back to Game" button for score estimation to "Back to Board" to reflect that it has different behavior than the "analysis toolbar" "Back to Game" button after https://github.com/online-go/goban/pull/14 merges (new behavior is to return to previous board position rather than the last official move). To get back to final board state after score estimation will require two presses: (1) "Back to Board", (2) "Back to Game", or alternatively just hit `esc` twice. I'm happy to name it …
=> Fixed wrong display of final board after using score estimation or AI review

src/components/Player/Player.tsx, src/components/Player/PlayerDetails.tsx
Fixes #1286 
Two main changes were required to get this fixed:
I fixed the `resolved` state property logic in `PlayerDetails` to get the buttons to not be disabled. The previous semantics of `resolved` were inverted, where the buttons were disabled if the state was resolved as opposed to the other way around. 
There was a crazy bug here that was causing it to "work" before despite the semantics being wrong: for some reason the `player` object (of type `PlayerCacheEntry`) was getting the `PlayerDetails` state properties added to the object! So on first `resolve()` for a player we set `resolved: true` which disabled the buttons, then on second `resolve()` the player had `resolved: false` property set (false due to initial blank state), so `Object.assign({resolved: true}, player as any)` had …
=> Fixed player details popup not loading on first press

src/views/Overview/Overview.tsx
Fixes #1277 
I noticed that the `ProfileCard` user prop had stale data in it and didn't match the child `Player` component's user ratings. Looks like this is just because we assign the user once during initial render and `data.get("config.user")` when the page first loads could be out of date. This fix watches for `config.user` changes and forces re-render if it occurs, preventing stale homescreen data.
=> Fixed stale rank on homescreen

src/views/User/User.styl, src/views/User/User.tsx
The user's rank should not be shown if they have selected "Hide ranks" option.
Don't show it if they have selected hide ranks option 👍 
I also took the opportunity to vertically align the user's rank with the rest of the row.
=> Hide user's own rank when "hide ranks" is active (and alignment tweak)

src/components/ChallengeModal/ChallengeModal.tsx, src/lib/sfx.ts
Fixes #1293 
There's a race condition that causes the `Game started` sfx to play twice:
1. User A requests live game from User B.
1. User B accepts the game.
1. User A receives the `gameStarted` notification and plays `game_started` sfx.
1. User A receives game data and `ChallengeModal` plays `game_started` sfx.
If 3/4 are swapped then the notification is suppressed since the game is already open and notifications for the actively viewed game are suppressed, hence why this only happens some of the time and is a race.
This "fixes" the bug by suppressing the repeated `Game started` sfx if the race condition occurs and steps 3/4 are less than 3 seconds apart. Fixing the race condition itself seemed much more complicated. If we find this still triggers frequently we can increase the window …
=> Fixed repeated "Game started" sfx

src/components/LadderComponent/LadderComponent.tsx, src/components/RatingsChart/RatingsChart.tsx, src/views/Game/AIReviewChart.tsx, src/views/Game/Game.tsx, src/views/Joseki/Joseki.tsx, src/views/Play/Play.tsx, src/views/Puzzle/Puzzle.tsx
Fixes #1292
It looks like the `onResize=...` callback passes in some arguments, so `skip_state_update` arg in `this.onResize()` had integer values (maybe the window height or width?) which are "true" values (as opposed to the default false for the argument), causing the view mode to not be re-evaluated when rotating screen. Wrapping in a lambda to discard the args and use default ones fixed the issue. Made the change in all `onResize=...` places to avoid the bug in other places.
=> Fixed mobile rotation view_mode bug

src/components/NavBar/NavBar.tsx
In the navbar, there's no space between the play icon and the play word, which looks odd compared to the rest of the items in the menu. I think this might be a typo?
Just added a fa in the className in Navbar.tsx so it added the extra space and look consistent.
=> Added a space between play icon and play in the Navbar

src/views/Puzzle/Puzzle.styl
As part of PR #1298 `overflow: hidden` was removed from `.center-col` in `Puzzle.styl`. This caused the goban container to extend over the buttons making it so you can no longer press them. This fixes `wide` view mode (the most commonly used mode). Sometimes the goban container can still extend down over the buttons on mobile, but that doesn't always happen and it's a harder fix, so I just wanted to get this one pushed out since it affects more people.
I'll fix all of these mobile issues (including #1300) in a future PR.
@anoek Puzzles are currently pretty broken without this fix, so probably worth getting this one deployed when you've got a minute.
=> Fixed Puzzle goban container overlay blocking buttons in wide view

src/views/Puzzle/Puzzle.styl, src/views/Puzzle/Puzzle.tsx, src/views/Puzzle/PuzzleTransform.ts
**_Note_**: this doesn't fix the Firefox issues, I'll work on that soon and post a new PR for it. Was planning on doing that tonight but started shaving the yak instead...
Moved center col (i.e. goban) behind right-col elements so the overly long goban container didn't block transformation and undo/reset buttons (using `z-index`). This only was an issue on mobile for certain goban dimensions, so wasn't really a problem until the portrait mode was added in #1298.
Prevented jumping when transformation button pressed (issue was when we tried to focus on a different element (`$("#selected_puzzle").focus().blur()`) so that button didn't look improperly selected, we ended up causing page to jump). Changed to blur the just-pressed button instead, using react refs to get the button element. In …
=> Fixed various Puzzle bugs

src/global_styl/global.styl, src/views/Joseki/Joseki.styl, src/views/Puzzle/Puzzle.styl, src/views/Puzzle/Puzzle.tsx
Fixes #1300
Fixes the following bugs:
- Removed focus on settings, edit, and hint buttons to match behavior of transform buttons.
- Fixed nav bar not scrolling with rest of Puzzle page (Puzzle needed to be visible so the whole main div would scroll rather than just the puzzle).
- Fixed puzzle list scrolling to the side on mobile due to left/right padding in `page-width` css class. This padding change also fixed a bug where scrolling down in the puzzle list on mobile would sometimes jerk down after you stop scrolling (I was already planning on looking into that separately, but it turned out that the padding change had already taken care of it!).
- Centered Joseki extra info box in explore pane by removing left margin when in portrait.
- Fixed broken Joseki/Puzzle in Firefox portrait …
=> Fixed more Puzzle/PuzzleList/Joseki bugs

src/views/Supporter/Supporter.styl
Fixed on the Support page, the supporter card text overlapping in safari browser. Change flex: 0 to flex: 0 0 auto to make it the same as Chrome
Screenshot for overlapping text (Safari)
=> Fixed supporters card text overlapping on support page in safari

src/views/Puzzle/Puzzle.tsx, src/views/PuzzleCollection/PuzzleCollection.styl, src/views/PuzzleCollection/PuzzleCollection.tsx, src/views/PuzzleCollection/SortablePuzzleList.styl
After solving a puzzle, if the text field is too large the `Next` button is off screen. When we focus on `Next` it would cause the screen to jump. Fixed by ensuring we don't scroll after focusing on `Next` by restoring previous scroll position.
Fixes #1306 
Before (desktop, mobile):
After (desktop, mobile):
The mobile screen is still horizontally scrollable so we can rearrange puzzle list entries and edit them:
=> Fix puzzle scroll jump and puzzle collection mobile

src/lib/rank_utils.ts
Fixes #1307
Before:
After:
The server is returning player ranks >900 in the game data which wasn't properly handled in the `rankString()` util:
```
{
"related":{
"reviews":"/api/v1/games/9677/reviews"
},
"players":{
"black":{
"username":"Sun Zhe",
"ranking":43,
"professional":true
},
"white":{
"username":"Fujisawa Rina",
"ranking":40,
"professional":true
}
},
...,
"gamedata":{
"players":{
"black":{
"username":"Sun Zhe",
"rank":1043,
"pro":true
},
"white":{
"username":"Fujisawa Rina",
"rank":1040,
"pro":true
}
},
...,
}
}
```
=> Fixed SGF rank issue

src/views/Puzzle/Puzzle.styl
I noticed that when the `.right-col` page elements dynamically change as you click on moves in a puzzle, sometimes the screen would jump. See screen capture: https://streamable.com/ke1oaa
To fix this I set a minimum height on `.right-col`, which means that even if you're scrolled down to look at the puzzle text box and click a move, the page height shouldn't shrink enough to cause the screen to jump up. If the puzzle text box is larger than this minimum height, it is possible to scroll down far enough that after clicking a move the page height would shrink, _however_, this isn't really a concern as the goban would most likely be out of frame (since min height is based on page height with `vh`) so you shouldn't be able to click on anything that would cause the `.right-col` elements to …
=> Fixed puzzle jumping on resize issue.

src/views/LibraryPlayer/LibraryPlayer.styl
The SGF details were overflowing their container. Made the container horizontally scrollable instead.
=> Improved SGF collection page (LibraryPlayer) on mobile

src/lib/preferences.ts, src/views/Game/Game.tsx, src/views/Settings/Settings.tsx
I've found it difficult when looking at an AI review to tell the current board state apart from the projected moves in a variation.
This change adds a setting to control the transparency level of stones in a variation (default is 0.6, my personal preference is 0.2). For the sake of not changing existing behavior I've kept the default the same, but if others agree that a lower value is better I am happy to change the default.
This diff requires this goban PR to merge first (shippable test will fail until goban PR is merged and version bumped): https://github.com/online-go/goban/pull/19
Below are some screenshots with different variation stone transparency settings values:
0.0:
0.2 (my personal preference):
0.3 (maybe would be a good happy medium for a new default?):
0.6 (default):
1.0:
=> Added variation stone transparency to game settings

src/components/Notifications/Notifications.tsx
Fixes the problem that people click on the TurnIndicator in live games and thereby disconnect from their current game, which we don't want them to do.
Create a new tab for the next game if it is different to the current one.
(Note that once people have a tab for each live game they are playing at the same time, they should not click on the turn indicator, they should just switch tabs.   If they click on the turn indicator they'll get another tab, but there is not much we can do about that other than let them learn not to do that)
=> Use a new tab for advance to next board if this game is live.

src/views/Joseki/Joseki.styl
Fixes #1324 
Increased spacing from `1em` to `2em`. Original suggestion was to increase to `3em`, but I think `2em` looks good on both desktop and mobile and gives enough separation to avoid misclicks.
Before (desktop, mobile):
After (desktop, mobile):
=> Increased spacing between Joseki move control buttons.

src/views/Game/GameTimings.tsx
Fixes the problem that "final action" timing can only be accurate to a second
Don't display sub second amounts.
=> Display final action time in appropriate resolution

src/views/Game/Game.tsx
Fixes missing translations
* Use " not ` for simple string inside _()
* Add _() where it is missing
=> Fix translation of a string - don't interpolate inside _()

src/components/Notifications/Notifications.tsx
Fixes [the problem of creating a new tab on notification click if the live game has finished](https://forums.online-go.com/t/clicking-on-black-dot-with-of-moves-waiting-opens-in-new-tab/32626/4?u=eugene) .
Don't create a new tab on notification click if the live game on the current tab is finished.
=> Don't create a new tab on notification click if the game is finished

src/lib/preferences.ts, src/views/Game/Game.tsx, src/views/Settings/Settings.tsx
Fixes [the problem some people have knowing that they got an undo request](https://forums.online-go.com/t/wish-better-noticeable-undo-requests/964/70?u=eugene)
Add a player preference for showing a visual indicator of undo pending.
Show a '?' instead of the circle for the most recent move if there is an undo request for it and the preference is turned on.
This implementation requires the Goban support provided in https://github.com/online-go/goban/pull/23 .
This implementation does _not_ attempt to colour the '?' red, as requested by some, because that is a can of worms to get right visually (think themes, custom boards, highlights on stones etc).
=> Add option to show '?' on latest move if there is an undo request for it

src/components/ChallengeModal/ChallengeModal.tsx, src/components/GameAcceptModal/GameAcceptModal.tsx, src/components/Notifications/Notifications.tsx, src/lib/misc.ts, src/views/Puzzle/PuzzleEditing.ts
- Signature of dup() changed from `dup(obj: any): any` to `dup<T>(obj: T): T`
- Fix type errors that arose from above change
- Log an error when `game_id` is missing from a notification
The third item may seem separate from the first two, but I came across `dup()` while debugging the stone removal notification error (hence the branch name).  Happy to break this PR up if necessary.
=> Preserve type for dup() and add some logging for Notifications error

src/components/ACLModal/ACLModal.tsx, src/components/TimeControl/util.ts, src/lib/translate.test.ts, src/lib/translate.ts, src/views/Game/GameLinkModal.tsx
After translation updates, this will fix one of the German language localization issues presented in the OGS Forum thread [message not localized (unremovable branch, time control)](https://forums.online-go.com/t/message-not-localized-unremovable-branch-time-control/32557/15)
- updates to internals of `durationString`
- `durationString` now returns lowercase (if not translated)
- Remove some unused imports, functions
=> Updates to TimeControl.durationString()

src/views/Game/Game.styl
Rebase of #1213.
In horizontal zen mode we have enough vertical space to place the clocks above each other.
This allows the user to reduce the windows width even further while keeping the goban at maximum size.
=> Align clocks above each other in horizontal zen mode

src/views/Moderator/Moderator.tsx, src/views/User/User.tsx
- Leverage existing chat markup to automatically convert mod note links in mod center and on user profiles
=> Make game links and user profiles clickable in mod notes

src/views/User/User.styl, src/views/User/User.tsx
In the game history make the game title a link again, but keep the row clickable. This way one can use the link context menu when right clicking on the game name.
=> Make game name a link again

src/lib/rank_utils.ts, src/views/User/User.tsx
With the breakdown ratings now being comparable with the overall rating — they are the would be rating if the player had only played the games with the speed+boardsize — we can show the ranks in the breakdown chart instead of the ratings. Most users do not know how to read the ratings, and we are using rank everywhere else on the site already.
=> Show rank instead of rating in rating-grid

src/views/Moderator/Moderator.tsx
Some notes in the mod center are showing as `<Message too long>`.  I increased the limit of those to match what we're using for notes on user profiles.
=> Increase length limit for notes in mod center

src/index.html, src/views/Game/Game.styl
Fixes #1387
Support Safe area bottom. So in iPhoneX or iPad Pro the Home Screen Bar in the bottom will not cover the tools when review a Game.
Before Screen Shot
After Screen Shot
-
-
-
=> Feature: make Game support webkit safe area

src/components/Notifications/Notifications.tsx
Fixes [the problem of opening a new tab if on a game that is finished](https://forums.online-go.com/t/clicking-on-black-dot-with-of-moves-waiting-opens-in-new-tab/32626/15?u=eugene) which should not happen
Look in the right place for window's game status.
=> Bugfix in choosing whether to open new game tab or not

src/components/Clock/Clock.styl, src/views/Game/Players.styl
Fixes #1373
- Show number of byo-yomi periods left once byo-yomi has started
- Some code style fixes: mixed tabs/spaces
- Some css simplification: elements inside byo-yomi-container were handled separately, even though they share the same style in all cases.
Note: Byo yomi periods do not show up until main time is used up.  If desired, it would be easy to add byo-yomi during main time, but I tried to maintain the minimalist philosophy of zen-mode.
=> Show number of byo-yomi periods in zen mode

src/components/GameList/GameList.tsx
Fixes #1388 
- Adding a sorting case for board size to fix bug #1388
It seems to be working as expected, when I check with some dummy games on http://dev.beta.online-go.com:8080/.
I would be happy to receive comments, since I'm not familiar with the code base.
=> Adding sorting case for board size

src/components/NavBar/NavBar.styl, src/ogs.styl, src/views/Game/Players.styl, src/views/Supporter/Supporter.styl, src/views/TournamentList/TournamentList.styl
Fixes #1404
- Use #A48200 for site-supporter player names on light backgrounds. (For a contrast ratio of about 3:1)
- Use light theme color for the white Player info in a game
=> Darker gold in light mode

src/ogs.styl, src/views/Game/Players.styl
Fixes issue that Vsotep brought up [in the forums](https://forums.online-go.com/t/yellow-on-white-is-an-awful-color-choice-for-text/34275/43?u=benjito).  Mods who support were no longer getting purple'd.
- Ensure the proper "color priority" is followed (e.g. admin status is more important than supporter status)
- Use dark mode in the black player box, and light mode in the white player box *for all player colors*
- Also make sure the correct gold is in accessibility mode (my stuff and @GreenAsJade's stuff overlapped)
Please let me know if y'all can think of any other good players/games to look at.
=> Fix mod/supporter color issue in player boxes

src/components/Announcements/ActiveAnnouncements.tsx
I had copied `"announcements.cleared"` and did not change it to `"announcements.hard_cleared"`.  This meant that we were saving hidden announcements from the card, but actually overwriting the hidden pop-ups.
Apologies for the issues.  Thanks @anoek for looking into it and thanks @pdg137 for reporting!
=> Fix data id causing announcements not to go away.

src/components/Notifications/Notifications.styl
Fixes issue I reported in the forums (sorry - will use Github Issues in the future)
https://forums.online-go.com/t/web-client-performance-issues/35191/8
There is apparently an infinite webkit animation in the unread notifications UI which causes the browser to continuously repaint at 60 frames per second, causing high CPU/GPU usage.
This PR simply removes the animation, because as far as I can tell it's not even really noticeable to begin with. This fixes the CPU load issue.
See below the difference (pay attention to the "Frames" row)
=> Remove animation which causes constant 60fps repaints

src/views/User/User.tsx
Credit to benjito in link beneath
https://forums.online-go.com/t/has-recently-timed-out-of-a-game-uh-does-years-ago-count/31064/12
This display is erroneous, and the backend fix, it seems, is non-trivial. While we wait for a backend fix, this removes the message entirely and frees the users from any potential negative impact on their reputation.
Fixes #
-
-
-
=> Remove "user has recently timed out of a game"

src/global_styl/global.styl, src/views/Puzzle/Puzzle.tsx
Fixes #1454
Hi, first time contributing. Love OGS! 
- Add a "toggle coordinates" button in Puzzles
- Add `title` attribute to buttons
- Minor changes to clean up button styling 
- Remove border outline and add margin instead (feels more modern and the spacing improves accessibility)
- Fix active state border color
=> Feature: Add "toggle coordinates" button in Puzzles

src/components/Player/Player.tsx, src/components/Player/PlayerDetails.tsx, src/components/PlayerNotesModal/PlayerNotesModal.tsx
Per-user keyed player notes
This ensures that when you log in as a different user, you don't see
notes from another account.
While there's a loose idea that should be firmed up regarding keying all
data and preferences with the user id, I have a nagging suscpicion that
we'll want still have these keyed to make our lives easier when it comes
to transitioning data and preferences to those keyed values, and dealing
with what do we do when we change accounts and transition from being
logged out to logged in and vise versa.
This PR stacks on top of #1462 @GreenAsJade
=> Per-user keyed player notes

src/lib/configure-goban.ts, src/lib/preferences.ts, src/lib/sfx.ts, src/views/Game/Game.tsx
Hi there,
I'm Riley, and I've been a customer of online-go.com for about a year. I really enjoy the site, but I frequently find myself thinking the master volume is set to zero, but then surprised that the sounds are playing after all.
One potential area of confusion is the separation of the concepts of the "override" volume and "master" volume, I think. I was interested in checking it out and so I humbly submit this sacrificial PR.
* Merge the volume override setting visible on game boards with the master volume setting visible on the settings page
* Drop the `sound-volume` and `sound-enabled` preference keys. If deployed, this will cause existing user preferences to revert to their "master volume" setting.
* Overall, this means when a user adjusts the volume on a game screen, it ALSO …
=> Unify "master" and "override" volume settings

src/components/FriendList/FriendList.styl, src/components/Player/Player.styl, src/components/PrivateChat/PrivateChat.styl
Fixes ongoing hassles of alignment of elements of `Player`
- Don't use absolute positioning for presence indicator, use flex to line it up on the centreline no matter what size it is
- Use flex to put all the elements on the baseline in the case of "chat", where we have flare instead of presence indicator
- Put the primary parameters in `Player` and specialise only where it needs to be specialised (eg PrivateChat)
- This also fixes the squished private chat header.
=> Systematic fix to presence/flare alignment in Player

src/lib/chat_manager.ts, src/lib/misc.ts
Fixes (improves, anyway) #1476 
The chat_manager was re-sorting channel user lists twice every time someone joined or parted the channel. This led to the CPU graph below even when sitting idle on the home screen, where you can see a single call to `_update_sorted_lists` was taking about 20ms
I changed the code to either insert joining users or remove parting users, with the assumption the sorted lists were already sorted. This made the CPU graph look more like this:
I'm not totally sure what the gray hashes mean, but I think it's like "idle" or some such. The overall tab CPU usage dropped for me on my 2013 MBP from 25% CPU to 2% CPU.
I only tested on chromium on Mac - maybe Firefox or Safari have different optimizations that would see different CPU impact. It's hard to imagine this making …
=> keep users list sorted instead of re-sorting from scratch each time

src/views/Register/Register.tsx, src/views/SignIn/SignIn.tsx
This is to change the texts on the social login buttons from "Login with ..." to "Sign in with ...", since Apple just rejected my iOS app again due to the text on the AppleID login button. 😔
According to [Apple's guideline](https://developer.apple.com/design/human-interface-guidelines/sign-in-with-apple/overview/buttons/), there are only three options: "Sign in with Apple", "Sign up with Apple", or "Continue with Apple".
- Change the texts on the social login buttons on Sign in and Register page from "Login with ..." to "Sign in with ...".
=> Change the social login buttons' text from "Login..." to "Sign in..." to comply with Apple's Guideline

src/components/RatingsChart/RatingEntry.ts
Fixes #1483
Set win/loss counts to zero on detection of special "initial rating" RatingEntry
=> Set win/loss counts to zero on special initial rating RankEntry

src/lib/misc.ts
Fixes the incorrect instruction, and the amount of space for typing.
Tries, but fails, to fix the problem of closing prematurely when accidentally clicking outside.
- Use a textarea instead of an input
- Say "clear" instead of "brief"
- Specify closeOnClickOutside to be false ~~(done, but doesn't work)~~
=> Improve report-raising modal

src/components/PrivateChat/PrivateChat.styl
Fixes:
Very slight but jarring misalignment of PM box icons
- Code: gets rid of multiple margin-top's on each icon, replaced by one padding-top for the naughty icon.
- Layout effect: tiny (couple of pixel) improvement in vertical alignment of icons in title bar
=> Tidy up PM box icons vertical alignment

src/ogs.styl
Restore the old color from https://github.com/online-go/online-go.com/pull/1391#issuecomment-870628520
=> Restore the old indicator's color after changes in #1391

src/global_styl/flags16.styl, src/global_styl/flags32.styl, src/lib/translate.ts
I am not sure if this is implemented correctly, I tried to follow previous PRs. apologies if there is some mistake
- add the “Progress Pride Flag” by Daniel Quasar as an option. image taken from [here](https://quasar.digital/terms/) note the CC license. not sure if there is more OGS needs to do to use it
- originally suggested by Gooplet on the forums: https://forums.online-go.com/t/adding-an-lgbt-pride-flag/38303
- I assume this depends on the new sprites file, see [this PR](https://github.com/online-go/world-flags-sprite/pull/2/files)
tested it locally:
=>  add LGBT+ Pride flag

src/components/MiniGoban/MiniGoban.styl, src/components/MiniGoban/MiniGoban.tsx, src/components/RatingsChart/RatingsChart.tsx, src/components/RatingsChartByGame/RatingEntry.ts, src/components/RatingsChartByGame/RatingsChartByGame.styl, src/components/RatingsChartByGame/RatingsChartByGame.tsx, src/components/RatingsChartByGame/index.ts, src/lib/preferences.ts, src/views/Settings/Settings.styl, src/views/Settings/Settings.tsx, src/views/User/User.styl, src/views/User/User.tsx
Add a toggle that allows the rating graph to be plotted by game.
When selected, 
- the win-loss bars are removed (because they don't make sense without timeline granularity)
- the x axis becomes "games played"
- the pie chart shows the date for the games selected by the lower sub-selection area
=> Plot rating by game

src/components/MiniGoban/MiniGoban.styl, src/components/MiniGoban/MiniGoban.tsx, src/components/RatingsChart/RatingsChart.tsx, src/components/RatingsChartByGame/RatingsChartByGame.tsx
Fixes:
- Lingering PieChart artifacts on resize (corner cases)
- Display of game hover popup when pie chart won't fit (don't do that)
- Overlapping textual win-loss information in by-game chart in phone form factor (don't display this info, for now)
- Display of meaningless points when game is finished (don't do that)
- Display result of game that is finished in the title (do do that)
Got rid of renderWinLostResultsAsText in the by-game component, for now.   This is actually buggy in the original chart component: the render of this extends below the extent of the element (it looks like vertical clip was turned off to allow this). but due to fortunate spacing in the rating-by-time case, it looks almost OK.
I couldn't quickly work out how to solve this properly - the whole "calculation of …
=> Various fixes for game popup in rating chart

package.json, src/components/Throbber/Throbber.styl, src/views/docs/GoResources.tsx, yarn.lock
In light theme while the OJE, joseki explorer is loading the throbber spinner is white like the background, hence is invisible, unlike in dark theme. Changed the background of spinner to use themed(background,shade0), which at least has some contrast to the theme background.
- Add a link to the Irish Go Association in the Other Go resources page, with Ireland flag beside the link.
I'm not sure why the yarn version is different from the main repository in package.json and yarn.lock. I'm using npm 6.14.14, node.js v14.17.5 . Is there another version I should use instead? The cache loader line just seems to have been moved automatically (alphabetically), but not changed.
=> OJE Throbber Spinner Light theme and Go Resources IGA

src/views/Joseki/Joseki.tsx
Fixes the problem where when you press double back arrow to get to the empty board, it re-fetches the result, even though we cached it.   That's because double back arrow requests "root" (because we don't know the empty board node-id) but we cached it by the resulting node-id.
Cache all immediate fetches immediately, by the requested node-id (instead of by fetched-node-id via the pre-fetch result that comes next), ensuring there is an entry for "root".
=> Fix OJE caching root

src/views/Joseki/Joseki.tsx
Fixes some lagginess
- Keep track of what nodes have already been prefetched, don't do them again
- Don't fire a second prefetch if one is in flight
- Ensure that browser prioritisation funkiness doesn't result in prefetch hitting server before main fetch
=> Optimize OJE prefetch

src/views/Tournament/Tournament.tsx
This fixes a problem with display of tournaments that have equal numbers for minimum and maximum players , such as all the "start when full" tournaments in the [New Zealand Tournaments](https://online-go.com/group/3207) group. Here's an example of such a tournament on the beta site:
https://beta.online-go.com/tournament/138
Currently it shows up like this:
This change removes the "+" in the case where min and max are equal.
=> in Tournament.tsx, handle the case where minimum and maximum players are equal, instead of showing it incorrectly as e.g. "10+"

src/views/Game/AIReviewChart.tsx
When the interactive AI review goes past the game's move count it gets cut off in the chart.
Example: game has 94 moves, created interactive AI variation from move 92 to 101.
Before:
After:
=> Fixed AI review chart's X axis when interactive variation goes past game's move count.

README.md
- Adds the real time API documentation to README.md
---
There is no mention of the real time API in the main [API documentation](https://ogs.docs.apiary.io/). As far as I can tell, this is the only documentation for the real time API.
The real time API documentation is still linked in the [gtp2ogs repo](https://github.com/online-go/gtp2ogs/blob/devel/docs/DEV.md#doc), so I think it is also appropriate to add here.
---
Side note: Are the [readme.io docs](https://ogs.readme.io/) deprecated? If so, I think the site should be taken offline after moving any remaining documentation over to apiary. It was confusing to track down all the APIs needed to build a client.
Also, thank you for making OGS! Love this site.
=> Add the real time API documentation to the README

src/components/TimeControl/util.ts
Fixes #839
- Allow *initial time* of up to 4 hours instead of up to 1 hour
- Allow *max time* of up to 4 hours or 28 days instead of up to 1 hour
The lack of longer time settings where mentioned by European professional Ali Jabarin as an "OGS bug" during a European Go Championship stream. He thought players should gain time that exceeds the 1 hour *initial time*, which was not possible because the highest *max time* was (prior to this change) also 1 hour. It sounded like he was expecting no max time at all. @BHydden considered this also as "real Fischer" on the OGS forum.
I've chosen 28 days as highest *max time*, because I think (for live games) it is close enough to infinite time or no max time and can still nicely be represented in the select list without any further changes.
=> Allow longer live games using Fischer time settings

src/views/Game/AIReview.tsx, src/views/Game/AIReviewChart.tsx
Fixes #1343
Depends on https://github.com/online-go/goban/pull/43
- Use score instead of win rate for calculating Key Moves
- note: will fall back on win_rate if score is not provided
- Show key moves as red dots for site supporter games
- Cleanup: remove unused variables in AIReview.tsx
Before:
After:
=> AI Review: use ΔScore in calculation of top 3 moves

src/components/GobanThemePicker/GobanThemePicker.tsx, src/components/PersistentElement/PersistentElement.tsx
I think I was digging around `GobanCore`, and came here because I wanted to see how `preRender[white|black]` and `place[White|Black]Stones` were used externally.  Anyway, it always helps me to figure out what types are floating around..
- Removed unused stuff (unused variables, imports, commented code)
- Added types to everything
- Added tooltip (screenshot below)
If the tooltips are disagreeable, I can take that out. But the theme names are already translated, so I figured why not...
=> GobanThemePicker: Cleanup & tooltips

Gulpfile.js, tsconfig.json
Fixes some eslint-related issues that @GreenAsJade found.
- Add `'include': ['src']` to tsconfig.  This fixes the issue where new files in `src` would trigger lint errors before they were included elsewhere.
- Run eslint once at start of gulp script.  Turns out `gulp.watch` has a setting for that!
=> Some dev improvements

src/components/AutomatchSettings/AutomatchSettings.tsx, src/components/Chat/ChatLog.tsx, src/lib/automatch_manager.tsx, src/lib/data.ts, src/lib/types.ts, src/views/Moderator/Moderator.tsx
This PR makes it so that the output of `data.get` is typed if a default value is provided.  For example:
```
// some_bool is now boolean instead of any
const some_bool = data.get("bool-prop", false);
```
- type data.get
- type the automatch defaults in AutomatchSettings
- This was prompted by the update to `data.get`.
This is the code that prompted this change. Before, `challenge` was typed as `any`.  Now, it's pretty accurately typed, without having touched that area of code.
=> data.get: deduce type from default_value

src/components/DismissableNotification/DismissableNotification.tsx, src/components/Dock/Dock.tsx, src/components/GobanLineSummary/GobanLineSummary.tsx, src/components/KBShortcut/KBShortcut.tsx, src/components/MiniGoban/MiniGoban.tsx, src/components/PaginatedTable/PaginatedTable.tsx, src/components/PersistentElement/PersistentElement.tsx, src/components/ProfileCard/ProfileCard.tsx, src/components/RatingsChart/RatingsChart.tsx, src/components/RatingsChartByGame/RatingsChartByGame.tsx, src/components/ServerTimeDisplay/ServerTimeDisplay.tsx, src/components/UIPush/UIPush.tsx, src/views/Game/AIReviewChart.tsx, src/views/Game/Chat.tsx, src/views/Joseki/Joseki.tsx, src/views/Ladder/Ladder.tsx, src/views/LearningHub/InstructionalGoban.tsx, src/views/LearningHub/LearningPage.tsx, src/views/Play/Play.tsx, src/views/Tutorial/InstructionalGoban.tsx
Pretty much all of these were marked as `any`.  Note, this is only `React.Component`s, there are plenty of `React.PureComponent`s that can possibly be updated in the same way.  I did not make logic changes in this PR, but left some comments about code that looks either unnecessary or mis-annotated and could be updated in the future.
Add a `*State` interface for every `React.Component` that had state typed as `any`. In some cases, I just deleted `any` from the template arguments, since the default is `{}` and that is more appropriate for components that do not update state:
```diff
-class SomeComponent extends React.Component<SomeProps, any> {
+class SomeComponent extends React.Component<SomeProps, SomeState> {
// this.state is now a SomeState
-class SomeComponent extends …
```
=> Add State Types to all React.Components

package.json, src/lib/preferences.ts, src/lib/sockets.ts, src/views/Game/AIReview.styl, src/views/Game/AIReview.tsx, yarn.lock
Fixes:
When a game ends with consecutive passes, there's a console error which results from empty branches in the AI review having their (non existent) move coordinates checked. So added in a mv === undefined check.
Adding in a new AISummaryTable component to the AIReview which tries to summarise the data according to score loss, and categorise the types of moves as Excellent = blue move, Great = one of the green moves, Good = some positive score change move or mistake <1 point, Inaccuracy <2 point mistake, Mistake <5 points loss, Blunder >=5 point loss.
- It currently only shows for katago reviews (full or fast, but fast omits the Excellent and Great categories).
- It currently only shows for moderators, in order to test and tune before showing it to everybody.
- It should work on …
=> Ai summary table

src/components/PaginatedTable/PaginatedTable.tsx, src/lib/preferences.ts, src/models/tournaments.d.ts, src/views/Group/Group.tsx, src/views/TournamentList/TournamentList.styl, src/views/TournamentList/TournamentList.tsx, tsconfig.json
Fixes #1143 (@kobakitty please verify)
- Add a toggle that removes stale or exclusive tournaments (default: don't show stale/exclusive).
- arbitrary filtering was way easier than I thought it would be.  Cool API!
- Make Schedule the default tab, since it has the official tournaments.
- Add template args to `PaginatedTable` for tighter types.
- Add a **models/** dir that can be a home for various types such as types for important API calls. (pretty much just a proof of concept right now)
=> TournamentsList updates

src/views/Tournament/Tournament.styl, src/views/Tournament/Tournament.tsx
See this thread:
https://forums.online-go.com/t/tournaments-should-show-winners/33767/9
- Shows "Final results" with a list of the winners (top 3) of the tournament.
- Each winner is shown with the corresponding trophy:
- I had to compute trophy filenames since these don't seem to be available in the API; they won't work for the special title tournaments or non-standard sizes.
- Someone should check how I did the styling.
- This introduces a new loop over players which could be slow for large tournaments.
- I didn't implement hover text on the trophies since it seemed redundant.
- Maybe should be a bit narrower for mobile.
=> Tournament: show final results for finished tournaments

src/views/Tournament/Tournament.tsx
- After a tournament starts, show the number of players:
I've kept the information from when it was open in case it's useful to players or directors.  (Without that information, "Starts when full" doesn't make much sense either.)
=> Tournaments: show number of players in the tournament after it starts

src/views/Tournament/Tournament.tsx
- While a tournament is loading, do not show wrong default values
Fixes #1581, I think.  Not sure if this is the right place to put this line, but it seems to at least block anything from getting displayed while the tournament is loading. 
Of course it would be nicer if the OGS loading icon could continue bouncing up and down while the page is loading.
Merry Christmas OGS team! 🎅
=> Tournaments: do not show wrong default data while loading

src/views/Tournament/Tournament.styl
Example: https://online-go.com/tournament/16820
Before / after:
=> Tournament final results: do not bold player names since that messes up the emoji font

src/components/MiniGoban/MiniGoban.tsx, src/lib/misc.ts, src/views/Game/GameInfoModal.tsx, src/views/User/User.tsx
Fixes #1362 
- Use getGameResultText  in misc.ts to compute the string following the same style as in the user profile page (around [here](https://github.com/online-go/online-go.com/pull/1591/files?diff=split&w=1#diff-66a31d293aab8a1670fb4609c8c607d53df748b37db0d1d9ce4e0fc6d8262cecR169) and [here](https://github.com/online-go/online-go.com/pull/1591/files?diff=split&w=1#diff-66a31d293aab8a1670fb4609c8c607d53df748b37db0d1d9ce4e0fc6d8262cecR275)
- my code is inspired on the code in MiniGoban.tsx, I merges both codes to avoid duplication
- What's the policy concerning prettier? I see it installed and it ran automatically by my IDE... but then it made lot's of changes... I see there's a build script `prettytsx` but it does lots of changes a little bit everywhere... not sure it runs very …
=> add getGameResultText on GameInfoModal 

src/components/ChallengeModal/ChallengeModal.tsx
Fixes #1603
- bot choice is now saved as integer, not string
1. Go to "Play"
2. Click "Computer"
3. Select an AI Player other than amybot-beginner
4. Click "Play" again at any point in the future
Notice: Your previous bot choice will already been selected.
The bot choice was being forgotten because its HTML Option element stores `bot_id` as a string, whereas our `bots_list()` has ids that are all integers. Now, when the state updates from an Option event, it will run `parseInt` before storing.
I did a code search to see if there was anywhere that might depend on `bot_id` being a string, but couldn't see anything obvious.
=> bot choice is now saved as integer to match bots_list()

.husky/pre-commit, CONTRIBUTING.md, package.json, yarn.lock
(some prep for prettier)
Here's a simple way to get a lint precommit for anyone who wants it!  I've set it up to be opt-in, so if you want to try it out, run `npx husky install` first.
- Add husky and lint-staged to the repo
- Set up lint-staged to run eslint on files that have been staged
- Set up husky to run lint-staged
- Add documentation
=> husky + lint-staged

src/views/Group/Group.tsx
Fixes #1614 
- Remove two string refs (I could not find associated ref variables, so I don't think this will have a functional effect besides fixing the error)
Related: Perhaps the "Loading..." overlay should be suppressed for news editing.  It is displayed every time the user types:
=> Remove two string refs from the Group News table.

src/views/Game/Players.styl
Old Apple devices and/or versions of Safari seemed to have issue with this, meaning buttons went under the player card, or the board went over the player card
Fixes https://forums.online-go.com/t/board-position-covers-names-rank-score/40679?u=shinuito
Tested with Xcode simulating iOS 12.4 below.
Further tests with updated browsers seem to indicate that it doesn't change the layout on recent Safari, Chrome, Firefox on Mac for example. Likely a remnant of css from rengo from before the team members were moved from below the player cards to inside them.
(images are a bit choppy, trying to remove backgrounds, poorly, from screenshots, and poorly scaling to not take up too much space in Github).
iPad Air
and in portrait mode
=> Try to fix display issue for old Apple devices

src/views/Game/AIReview.tsx
- re-orders the key moves in the AI Review to be in the move order, not based on the review's internal metric
before:
after:
@anoek had said in #1589 that he wanted to "help users who first see this intuitively understand what these bubbles with letter/number combinations mean."
This PR doesn't necessarily fix this, but having the key moves and the red dots in the same order further drives home the point that they refer to the same thing.
Players can also click through to see the story of the game unfold.
We don't show the underlying metric that the AI Review uses to score these moves to the user, nor would it be clear if we did. (I saw some healthy debate in the forums on ways to score these moves.)
I had intended to get this into #1589, but I didn't want to change too much at once.
=> Re-order key moves in AI review by move_number

.eslintrc.js, src/components/Chat/ChatLog.tsx, src/components/Errcode/Errcode.tsx, src/components/Notifications/Notifications.tsx, src/components/SeekGraph/SeekGraph.tsx, src/lib/misc.ts, src/lib/sfx.ts, src/lib/translate.ts, src/views/Admin/MerchantLog.tsx, src/views/Game/Game.tsx, src/views/Settings/Settings.tsx, src/views/Supporter/Supporter.tsx, src/views/Tournament/Tournament.tsx, src/views/TournamentList/TournamentList.tsx
Thanks @anoek for the excellent project, huge fan.
This PR just re-enables a few eslint rules, partly by disabling by line instead of project-wide. Let me know if you'd like any changes (e.g., is it fine to blanket allow empty catch clauses? That was almost all the no-empty errors.).
=> Re-enable some eslint rules

src/views/Game/AIReview.styl, src/views/Game/Game.styl, src/views/Game/Players.styl
This patch replaces the drop shadow with an underscored blue line with a
small arrow as the turn indicator, up for aesthetic discussion. I'm not sure this is the best it can be, so if anyone has any ideas lets hear them :)
Relates to #1600
There's some places the current drop shadow looks a bit funky, so this PR is attempting to fix those with an alternative look.
1. Shadow overlaps neighboring player box (Might be fixable with a z index thing, I'm not sure)
2. Shadow gets clipped as it attempts to extend past the bounds of the containing box (I don't think this is fixable, not easily at anyrate). It also drops shadow deep into the "Black to Move" text, which could be fixed with margin, but that has some downsides too.
3. Similarly, on non rengo games the whose turn is it is not present, …
=> Alternative display for highlighting whose turn it is

src/components/ChallengeModal/ChallengeModal.tsx
... in the Challenge modal
Fixes a lockup Sofia found due to a previous bug.
IE she had found the way to get ranked and rengo checked, and this was saved in her challenge modal data.
Don't disable ranked or rengo if they are checked.
=> Bugfix: you should always be able to turn off rengo, and ranked

src/components/ChallengeModal/ChallengeModal.tsx
The alternative discussed in #1623
There is already some handling in the constructor of ChallengeModal for bogus configs.  This just adds the constraint "rengo must not be private or ranked."
=> Don't allow challenges to be rengo if they are ranked or private.

.github/workflows/stale-issues.yml
Adding an initial GitHub action for marking issues as stale. This is in "dry-run" mode right now (`debug-only: true`) so it won't actually modify issues yet (that way we can settle on what the best parameters would be beforehand).
Also, I think the `stale` label would need to already exist in order for this to work.
For reference: https://github.com/actions/stale
=> Add stale action

src/components/ACLModal/ACLModal.tsx
It seems some of these may have a simple fix of moving into the constructor according to https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html
xref: https://github.com/online-go/online-go.com/issues/1629
=> Remove UNSAFE_componentWillMount

.eslintrc.js, package.json, src/views/TournamentRecord/TournamentRecord.tsx, src/views/Tutorial/InstructionalGoban.tsx, src/views/Tutorial/Tutorial.tsx, yarn.lock
Setting up a rule to clean up some unused imports (in case there's interest in doing this) as well as removing a few. I didn't want to do too much to keep the diff small, but if we want it's easy to get rid of the rest.
Seems there's some overlap between this plugin and `@typescript-eslint/no-unused-vars` so the unused variable part can probably just be left off.
For reference: https://github.com/sweepline/eslint-plugin-unused-imports (for whatever reason it seems to work fine ignoring the part about React)
=> Set up unused import eslint rule

.eslintrc.js, .github/workflows/main.yml, package.json, prettier.config.js, src/components/LadderComponent/LadderComponent.tsx, src/lib/chat_manager.ts, src/lib/misc.ts, src/views/Ladder/Ladder.tsx
This PR should make it possible to run prettier globally when we have an open window.  To perform this global write, this command should work:
```
npm run prettier
```
- Remove unused and un-recommended rules from the Prettier config.
- Remove ESLint formatting rules (and fix the duplicate `extends` field)
- Disable eslint on lines that will trigger `id-denylist`
- Add prettier to `lint-staged` and a (commented out) step in the GitHub workflow
- Turn on the prettier check in GitHub workflow
- Run prettier --write (obviously 🙂)
- Added IDE specific configs
=> Prettier everything but write

.eslintrc.js, package.json, yarn.lock
@anoek I just realized that `@typescript-eslint/no-unused-vars` actually covers unused imports as well (hence why the number of errors from that plugin went down so much after cleaning those up) so actually I think we can remove `unused-imports/no-unused-imports`. :man_facepalming: 
(Adding an extra import and running with both turned on shows output below)
```
21:26  error  'api1ify' is defined but never used                     @typescript-eslint/no-unused-vars
21:26  error  'api1ify' is defined but never used                     unused-imports/no-unused-imports
```
=> Remove unused imports plugin

.eslintrc.js, package.json, src/main.tsx, yarn.lock
Having eslint run our prettier checks gets us some prettier output in
our gulp build loop window so we know when prettier is failing before a
commit.  The gulp-prettier plugin seemed to do the same but with less
information (no line numbers for instance, although I assume I just
didn't have it configured right), and overall it was slower, probably
because it had to run a full prettier check after a full eslint check,
and either eslint's caching is applied to the prettier checks when
eslint does it, or it's run in parallel, or both, I'm not sure - but
this seemed to be the better option, but I'm open to being corrected.
@benjaminpjones @dsaxton
=> Have eslint run our prettier checks

Dockerfile
It looks like the node version needs to be updated in order to build the image successfully:
```
error @typescript-eslint/eslint-plugin@5.10.0: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got "10.15.1"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn install' returned a non-zero code: 1
```
=> Fixup Dockerfile

src/components/NavBar/NavBar.tsx
Strict mode doesn't seem to like this: `Warning: A string ref, "omnisearch_input", has been found within a strict mode tree. String refs are a source of potential bugs and should be avoided.`
xref: https://github.com/online-go/online-go.com/issues/1629
=> Use createRef for omnisearch_input

src/components/TimeControl/TimeControlPicker.tsx
Fixes #1628
- Default the number of periods to 1 when it's falsy (0 or NaN)
Notice that parseInt returns NaN when the value is not a number.
Users using third party extensions will still be able to create invalid games.
=> TimeControlPicker.tsx: update_periods: avoid NaN parseInt

src/views/Game/GameInfoModal.styl, src/views/Game/GameInfoModal.tsx
Fixes the broken layout people are reporting, with large rengo teams overlapping the subsequent information in <920px screen height
~~Let the rengo-team-container scroll.~~
Remove that list.  They are on the Game page anyhow.  Instead, tell them the count of participants.
=> Remove rengo team list from Game Info Modal

src/components/ACLModal/ACLModal.tsx, src/components/AIReviewStream/AIReviewStream.tsx, src/components/PaginatedTable/PaginatedTable.tsx, src/components/PlayerAutocomplete/PlayerAutocomplete.tsx, src/lib/requests.ts, src/lib/types.ts, src/views/ChatView/ChatView.tsx, src/views/Game/Game.tsx, src/views/Group/Group.tsx, src/views/Joseki/Joseki.tsx, src/views/Ladder/Ladder.tsx, src/views/LearningHub/LearningHub.tsx, src/views/LibraryPlayer/LibraryPlayer.tsx, src/views/Puzzle/Puzzle.tsx, src/views/PuzzleCollection/PuzzleCollection.tsx, src/views/PuzzleCollection/PuzzleCollectionList.tsx, src/views/PuzzleCollection/SortablePuzzleList.tsx, src/views/Settings/Settings.tsx, src/views/Tournament/Tournament.tsx, src/views/TournamentList/TournamentList.tsx, src/views/TournamentRecord/TournamentRecord.tsx, src/views/Tutorial/Tutorial.tsx
Replace instances of:
```
interface SomeComponentProps {
match: {
params: {
id: string;
};
};
}
```
with:
```
type SomeComponentProps = RouteComponentProps<{ id: string }>
```
It's a little more succinct, but more importantly it becomes clear that the structure of props is dictated by React Router.
~A lot of `params` are treated as numbers even though they are strings.  It doesn't seem to matter, but TS complains, so I made those `any` with an explanatory comment.~
`IdType = string | number` has been introduced to deal with these numbery strings.
=> The rest of the RouteComponentProps types

src/lib/sockets.ts
Fixes ongoing web socket messages in the consle.
~~If we're pointing at localhost, use beta ai server.~~
If we have NODE_ENV=development, then go to the beta ai server
=> go to beta for ai in development environments

src/components/LadderComponent/LadderComponent.tsx, src/views/Group/Group.tsx, src/views/LadderList/LadderList.tsx
Despite all the removed code, this change should be a no-op.  There was a lot of code in there about a "Full View".  Must have been replaced by `Ladder.tsx` or something.
Tested: Compared beta and localhost, no discernable changes.
View on beta:
View on localhost:
=> Cleanup: remove unused parameters from LadderComponent

src/components/LadderComponent/LadderComponent.tsx, src/components/PaginatedTable/PaginatedTable.tsx, src/views/LadderList/LadderList.tsx
One of the main uses for the PaginatedTable ref seems to be to watch for UIPush notifications and update the table accordingly.  Since this is the case, rather than having the caller set up a ref and a UIPush and connecting everything, why not just tell PaginatedTable what event to watch for?
As a proof of concept, I tried out this new prop on LadderComponent, and finished up cleanup while I was in there.
- uiPushProps prop for PaginatedTable
- cleanup LadderComponent, and use the uiPushProps prop
Tested:
I opened two browsers at the ladders page, joined and unjoined.  It seems to work about as well as before, and, in fact, I seem to have found an existing bug: #1674
=> Add optional UIPush parameter to PaginatedTable, cleanup LadderComponent

src/views/Group/Group.tsx, src/views/Moderator/Moderator.tsx, src/views/User/User.tsx
Follow-up to #1675 
- Update any PaginatedTable + UIPush combos to just use uiPushProps
- remove refs where possible
Tested: players table on the Groups page
Given that everything else was mod stuff, I didn't test that, but the changes are pretty straight-forward so I don't think there's a whole lot that can go wrong.
=> Remove some more table refs in favor of uiPushProps

src/components/RengoTeamManagementPane/RengoTeamManagementPane.tsx, src/views/Play/Play.tsx
Fixes moderators being unable to start games that inadvertently got the same player on both teams, and being unable in general to assist with team makeup.
Make team management controls available to moderators.
=> Moderator rengo team management

src/components/ChallengeModal/ChallengeModal.tsx, src/components/Chat/ChatList.tsx, src/components/Chat/ChatLog.tsx, src/components/PrivateChat/PrivateChat.tsx, src/lib/cached.ts, src/lib/data.ts, src/lib/data_schema.ts, src/main.tsx, src/views/Overview/Overview.tsx
`data` seems to be responsible for a lot of the missing types in the code base.  #1564 was an attempt to fix this by inferring types from the provided default value.  There are three problems with this approach:
1) Types were widened in some cases when they shouldn't be:
```
const tc = data.get("time_control.system", "fischer" as TimeControlSystem);
// tc now has type string, not TimeControlSystem
```
This could be fixed by removing type widening, but then the behavior could also be confusing:
```
const tc = data.get("time_control.system", "fischer");
// tc now has type "fischer", not TimeControlSystem or string
```
2) Types are not checked for consistency across separate calls:
```
data.set("foo", "bar");
const foo: number = data.get("foo", 8); // not good, but legal
```
3) A default …
=> A little more type safety for data.ts

src/views/Game/Game.tsx
Quality of life improvement for in-game/after-game analysis: i.e., keyboard shortcuts
- Add "shift-X" shortcuts for some options in the Game view Dock and for starting/stopping Analyze mode
- These shortcuts are...
- "Zen mode" : Shift-z
- "Toggle coordinates" : Shift-c
- **"Enable/Disable AI review" : Shift-i**
- "Analyze game" : Shift-a
- "Review this game" : Shift-r
- "Estimate score" : Shift-e
- "Back to Game" : Shift-p
- I became a site supporter recently and am using the AI analysis a lot after my games.  I noticed I really wanted the ability to toggle it on and off easily: for each move I like to try to figure out what the correct move would have been, and then I reference AI each time.
- Navigating my mouse to the "Disable AI review" and "Enable AI review" button in the Dock takes …
=> Added "shift-X" keyboard shortcuts for analysis in Game view

src/lib/rank_utils.ts, src/models/games.d.ts, src/views/User/GameHistoryTable.tsx
Implements https://forums.online-go.com/t/rengo-status/40415/483
- Refactor game_history_groomer: this function was really long (120 lines!), so I broke out some logical functions.  It's still pretty long but now it's half the length and fits on one "page".
- Make the normal columns handle rengo games (sort of)
- Remove the rengo-specific table
- Add some types to the Game History table
I could use some API support:
- player lists or at least number of players for rengo matches
- ~~Fix the game result fields (black_lost, white_lost)~~ i hear a fix is in flight :)
- include the player whose page we are on in the `game.players` and `game.historical_ratings` (currently it just picks a player at random from each team?)
(screenshot from [Sophiam's page](https://beta.online-go.com/player/1775))
=> Game history rengo merge

src/components/ChallengeModal/ChallengeModal.tsx, src/lib/data_schema.ts
This PR is more of a question than anything else.. The AGA ranking stuff was hidden behind a flag (`aga_rankings_enabled`) that doesn't appear to be settable via the UI.  Is this used in a way that I am missing?
- Remove (hidden) AGA Ranked checkbox and associated code from the Challenge Modal.
=> Remove AGA ranking checkbox

package.json, src/components/Notifications/Notifications.tsx, src/lib/configure-goban.ts, src/views/Game/Game.tsx
Fixes random different ways of determining this 
Needs https://github.com/online-go/goban/pull/59
call engine.isParticipant() where appropriate
(surprisingly I found only two places to replace, not as bad as I was expecting)
=> use engine.isParticipant where possible

src/components/TimeControl/TimeControlPicker.tsx
Fixes #1628 
- Sanitize values of numeric input fields so that they match the min value if the stored value is falsy.
In fact the bug exists on both Canadian and byo-yomi rules. Hopefully the back-end blocks invalid Canadian challenges.
The point here is also starting a discussion on what is the best fix. 
Sanitizing all values in the localstorage before use seems to be a much better fix, but it is a much bigger change and we could also argue that its content is valid since we wrote it... (except when in this precise case).
=> TimeControlPicker.tsx: sanitize value of numeric inputs

src/components/PaginatedTable/PaginatedTable.tsx, src/views/User/GameHistoryTable.tsx
`forwardRef` kind of eats up template parameters (or rather turned them into `any`).  This casts the type of the modified component so that callers can benefit from type-checking. The type check goes like so: the return value of `groom` must be the same as the argument of `className()` and `render()`
- Add strong type to `PaginatedTable`
- Remove inferrable (and repetitive) type annotations in `GameHistory`
Now, the compiler knows what `X` is whether or not we annotate explicitly :)
=> Paginated table types

src/components/ChallengeModal/ChallengeModal.tsx, src/lib/data_schema.ts
I saw the request for this feature on the forums (https://forums.online-go.com/t/the-possibility-to-save-prefered-settings-for-games/41477). This is also a popular feature request on the iOS app, so I want to get this implemented on the web client first in order to share the data structure with the app later.
I'm a bit hesitant on putting everything on the modal though, since it is a bit too crowded, especially on mobile; but I don't have a better idea for that yet.
- Add options to save, manage, and apply preferred settings to the Challenge Modal (Custom game, direct challenge, computer).
- Preferred settings are stored in the generic data store with `Replication.REMOTE_OVERWRITES_LOCAL`.
=> Add options to save/manage/apply preferred settings for games.

src/components/TimeControl/util.ts
Rengo has awakened interest in more simple time settings (see forums: https://forums.online-go.com/t/rengo-status/40415/468).
- Allow simple correspondence to be as fast as 8hr per move.
=> Add faster simple correspondence timings.

src/views/Tournament/Tournament.tsx
Addresses #1713
I can see the tournament now, but not sure if this is the "right" fix.  The issue is that a couple of the players are no longer returned from the players/%%/players/all endpoint and therefore places that expect a player may get `undefined` instead.  The real question is why aren't these players populated?  They don't appear to be deleted players or anything...
`DavidHall` (id: 527014)  and `DQuad` (id: 371) are the missing players in the tournament from the bug: https://online-go.com/termination-api/tournament/85113/players
Sharing this patch in case it helps debug. (also better than showing nothing 😄)
- For round robin tournaments, filter out undefined values from the players array.
<details><summary>screenshot</summary>
</details>
=> Make sure sorted_players doesn't contain undefined values.

src/lib/data_schema.ts, src/models/overview.d.ts, src/views/Overview/Overview.tsx
This (hopefully) doesn't have any visible changes, but now Overview.tsx is compliant with TS strict mode.
- Remove some unused variables/code
- Add types
- Remove some `abort_requests_in_flight()` calls
- This may have a functional effect, but I don't think we should be unsubscribing from these fetches from the Overview components now that the fetches are initiated by cached.ts
=> Overview.tsx cleanups

src/components/RengoManagementPane/RengoManagementPane.tsx, src/lib/rengo_balancer.ts, src/views/Play/Play.tsx
1. Remove unnecessary props from RengoManagementPane
2. Show console logs from rengo team balancer
The rengo balancer [doesn't seem to be working correctly](https://forums.online-go.com/t/rengo-status/40415/828). It's hard to test on the beta site, because there's not a lot of players with stable ranks there. The console logs would make it easier to find the problem.
=> Show console logs from rengo team balancer

src/components/RengoManagementPane/RengoManagementPane.tsx, src/components/RengoTeamManagementPane/RengoTeamManagementPane.styl, src/components/RengoTeamManagementPane/RengoTeamManagementPane.tsx, src/lib/rengo_balancer.ts, src/views/Play/Play.tsx
Rengo challenge chat may cause the unassign/balance button to leave the viewport on mobile.
Move 'Balance teams' button from `RengoManagementPane` to `RengoTeamManagementPane` so it looks like this:
=> Move 'Balance teams' button from RengoManagementPane to RengoTeamManagementPane

src/components/TimeControl/TimeControl.ts, src/components/TimeControl/TimeControlPicker.tsx, src/components/TimeControl/util.ts
Fixes #1628
- `makeTimeControlParameters` & `onBlur`: check for boundaries and parsing errors
- define boundaries in `default_time_options` so that we do not need to hard code them in different places
- I am sure we can use some typescript trick to better define the type of `propertyName` parameter in `numericInputOnBlur`. Or mabe we should add some runtime checks with console.errors. What do you think?
=> TimeControl: deal with invalid numeric inputs

src/components/RengoTeamManagementPane/RengoTeamManagementPane.tsx, src/views/Play/Play.tsx
In my previous pull request (#1732), I forgot to hide the balance button from non-organizers. 
- Only show the button to owner of rengo challenge.
=> Hide rengo balance button from non-organisers

src/components/ChallengeModal/ChallengeModal.tsx
Fixes #1727 
In the end of the day the problem seems to be unrelated to https://github.com/online-go/online-go.com/pull/1721
It seems that there's a confusion on the `komi` property.
In `challenges.d.ts` it is defined as a `number` whereas we clearly send a string to the backend.
The constructor of `ChallengeModal` contains code to "fix dirty data", so I guess it's the right place to check if the `komi` is "valid". 
Maybe we could even parse it and check if it is a `float`. What do you think?
The only thing I don't understand (yet) is why the default komi is set to the empty string, as I had this value on my local environment already, even though I cannot see traces of it on the code.
- Replace `null` check by truthy check, so that the empty string is replaced by the valid default …
=> ChallengeModal.tsx: set komi to 5.5 if it is not defined

src/views/User/AvatarCard.tsx, src/views/User/User.tsx
Fixes #1742.  I'm not entirely sure what changed in #1730 that caused the breakage, but basically, we are calling `player_cache.update()` with `User.state.user` which has `user.icon` set to the outdated icon from the initial fetch.  Setting `user.icon` when modifying the icon seems to fix this.
Full disclosure: there is no good way to test the "updateIcon" codepath since I get a 500 error when saving a new icon from `localhost`.  However, the "clearIcon" path is basically the same and I was able to test that successfully.
- Fix a bug where the old icon got rendered when the user saves a new icon.
- Move editing state variable into props.
- Delete a couple of unused state properties in User.tsx.
=> Bugfix and cleanup: AvatarCard

src/views/Ladder/Ladder.tsx
Fixes #518
- Adds in a link to the group page from a ladder which is part of a group.
- Reuses the button from the group chat channels for familiarity, and code from ChatDetails.tsx, specifically copying the `goToGroup` function from there.
- Doesn't show for site ladders that aren't associated with a group.
The main use case I think will be if you are playing a game in group ladder, and click the tournament icon from the sidebar/dock and then would like to go to the group from that ladder page. If you navigate to the ladder from the group page itself, there's always the back button.
=> Add in a link to the group page from a group ladder

src/components/JosekiAdmin/JosekiAdmin.styl, src/components/JosekiAdmin/JosekiAdmin.tsx
Tweak the user and position audit filters in joseki admin to work with the new backend.
(New backend still doesn't support 'audit type' filter)
=> Reinstate position and user joseki admin filters 

src/lib/popover.ts, src/views/Game/Game.tsx
Fixes wondering who played a move, and squinting at the player cards
Popup a player card when told by Goban that a move with a played_by was clicked on.
Requires https://github.com/online-go/goban/pull/65
=> Popup a player card for who played a clicked rengo move in the tree

src/views/Joseki/Joseki.tsx
Fixes #1733
Went searching for server code to add validation on that end as well, but it doesn't look like that's open for contribution :)
- Checks for an empty string before submitting a comment in the Joseki explorer
- Adds type hint to `onCommentChange` function signature
=> Joseki Explorer - prevent empty comments

.eslintrc.js, src/components/ACLModal/ACLModal.tsx, src/components/GobanThemePicker/GobanThemePicker.tsx, src/components/ModNoteModal/ModNoteModal.tsx, src/components/Player/PlayerDetails.tsx, src/components/Report/Report.tsx, src/components/SeekGraph/SeekGraph.tsx, src/lib/sfx.ts, src/main.tsx, src/views/AppealsCenter/AppealsCenter.tsx, src/views/Game/AIReview.tsx, src/views/Game/Chat.tsx, src/views/Puzzle/Puzzle.tsx, src/views/Puzzle/PuzzleNavigation.ts, src/views/Supporter/Supporter.tsx, src/views/User/ModTools.tsx
Fixes #
- Enables no-empty-function eslint rule
- Removes empty componentWillUnmount lifecycle methods
- Changes promise `.then` chains to async/await when `then` was noop but catch was significant
- removed a no-op `catch` from `Supporter.tsx`
- `submitNote` in `ModNoteModal.tsx` changed: `close` event emitter moved to before promise is invoked via `await` - this preserves the ux of closing the modal while waiting for xhr to complete. Was a little worried about preserving a callback after a component had been unmounted, but it doesn't look like `errorAlerter` relies on `ModNoteModal` itself
- removed no-op `save` method on `<Report />`; commented out the `Save` button, since clicking it is a no-op. 
- autoformatter caught `.eslintrc.js` - I hope these superficial changes are okay to …
=> Enables no-empty-function eslint rule

src/lib/data_schema.ts, src/views/Joseki/Joseki.tsx
and  rename data-based selector so old… one is not used for anyone
Fixes anyone using the old one, which they aren't supposed to anymore.
Took backend toggle out of UI, and renamed the key in `data` so that any old user settings of that are no longer used.
=> Remove user switch for OJE backend

src/models/user.d.ts, src/views/User/AvatarCard.tsx, src/views/User/User.tsx, src/views/User/VersusCard.tsx
Improves the UX for slower-loading pages
- get user data from **api/v1/players/%%** and **termination-api/player/%%**.
- display the available data before the slower **api/v1/players/%%/full** fetch returns.
- Clean up/add some types in user.d.ts
Demo:
https://user-images.githubusercontent.com/25233703/162365605-2238d853-866a-47c0-8da2-d0262ff28417.mov
cc: @Sofia-mal
=> Load some parts of the profile page early.

src/views/Game/AIReview.tsx
The name of the engine at  `/api/v1/games/{id}/ai_reviews` recently changed from `katago` to `katago:fast` which stopped the Review table from populating automatically as it looked for `katago`. So
- check if the engine contains `katago` instead of `katago` exactly.
- added in new table rows to compute the median score loss of the players, and a function to compute the median score loss of a list of numbers (private to AIReview for the moment).
=> Table check engine and Median score loss

package.json, webpack.config.js
Fixes cache-loader dependency issues brought with webpack 5.0.
(Removing react-select types snuck in here too: this is deprecated because react-select apparently comes with types now)
Dump cache-loader.  
I _think_ that webpack 5 is doing what we want anyhow, though this definitely should be checked.
=> Remove cache-loader

src/components/JosekiStatsModal/JosekiStatsModal.tsx
Fixes labels not showing up in dark mode in the OJE stats chart
Pass the correct 'dark' parameter value to the chart
=> Oje react chart 3 dark mode

src/components/RengoTeamManagementPane/RengoTeamManagementPane.tsx
Fixes moderators finding it hard to deal with abandonned or otherwise un-admined rengo challenges
Simply make the buttons available - the back-end doesn't mind.   (It turns out the backend already assumed moderators would be allowed to do /team actions)
=> Give the balance buttons to moderators

src/components/RengoTeamManagementPane/RengoTeamManagementPane.styl, src/components/RengoTeamManagementPane/RengoTeamManagementPane.tsx, src/views/Play/Play.tsx
Fixes moderators needing a way to eject someone from all rengo challenges
GIve moderators a boot-someone-out-of-all-rengo-challenges button.
(Note: the positioning of the button doesn't make it entirely clear that it will eject the person from _all_ rengo challenges, but I couldn't think of a way to make that clear, and really moderators kind of know what they are doing, plus it's not the end of the world if someone is accidentally kicked from rengo challenges)
Requires https://github.com/online-go/ogs/pull/1734
=> Moderator rengo kick

Gulpfile.js, src/components/AutoTranslate/AutoTranslate.tsx, src/views/Joseki/Joseki.tsx
...  and defend Autotranslate against empty requests
* Use AutoTranslate on Joseki Descriptions
* Fix error message generation in Gulpfile
* Don't request translation of empty strings
=> Wrap joseki description in AutoTranslate

src/views/Joseki/Joseki.tsx
Fixes  AutoTranslate wrongly deciding the source language when the position description is short.
```
<AutoTranslate source={description} markdown />
<AutoTranslate source={description} source_language={"en"} markdown />
```
=> Be unambiguous that Joseki Descriptions are (currently) in English

src/components/JosekiTagSelector/JosekiTagSelector.tsx, src/components/JosekiVariationFilter/JosekiVariationFilter.tsx, src/views/Joseki/Joseki.tsx
From chat, as background:
I'm leaning in the direction of having the "Joseki: settled" filter active when you arrive at OJE
This will have the benefits of:
- Making people more aware that the whole filtering feature is there
- Not exposing everyone to every variation that isn't actually Joseki (in theory non-Joseki paths filtered out by this should be a very small subset of all the paths, because OJE is supposed to be "validated Joseki only")
TL:DR: set the Filter to "Joseki" Tag by default, when the Joseki page loads.
Involved:
- ripping the filter state out of the filter select components, to allow the initial value to be set
-  fixing various initialisation sequence issues that result
- converting them to Functional, because why not
- typing to suit
=> Oje turn on tag filter by default

src/views/docs/GoResources.tsx
The domain now points to a spam site.
=> Remove badukaires.com from GoResources.tsx

src/views/Game/Game.tsx
Fixes people complaining that undo doesn't work.
Detect rengo on the goban engine and turn off Undo button.
Things for reviewer attention:
A one line change, but is this a legit way of defending against goban and its ref not being ready?   And is there anywhere else that would care?
=> Turn off the "undo" button if it is a rengo game.

src/views/docs/GoResources.tsx
Since formatting for most entries is the same, the `Book` and `BasicResource` components handle formatting, and allow the caller to focus on content.
- Add `Book` and `BasicResource` components
- Search and replace
- output HTML is virtually identical, but a couple non-rendered spaces removed: https://www.diffchecker.com/8OBPOgk7
- tsconfig compliance (there was just one strictNullChecks error.)
=> GoResources: Replace common patterns with components.

src/lib/preferences.ts, src/views/User/GameHistoryTable.tsx, src/views/User/User.styl
Previous discussion about filtering games in the Game History can be found in this [forum thread](https://forums.online-go.com/t/feature-request-filter-game-history/38657/8). I decided to give this feature a go and add it in a way I found useful.
In the Game History table, I added two button sets for a board size filter and a ranked games filter. The top of the table looks like:
[ Player name search ] [ 9x9 | 13x13 | 19x19 ] [ Ranked | Unranked ]
For each filter, the filter is only active if a button is pressed, and only one button may be pressed at a time.
One peculiarity in this change is that annulled games are filtered out when either the Ranked or Unranked button is pressed. I don't know whether this is a good idea or not, but I found it to be more practical than adding another …
=> Add board size and ranked filters to game history

src/components/GobanThemePicker/GobanThemePicker.tsx, src/lib/preferences.ts, src/models/puzzles.d.ts, src/views/Puzzle/PuzzleEditing.ts, src/views/Settings/Settings.tsx
I noticed a common pattern is to create a state variable that is always in sync with preference variables.
```
const [value, setValue] = React.useState(
preferences.get("some-key")
);
... later ...
setValue(new_val);
preferences.set("some-key", new_val);
```
IMO this is hard to maintain because one always has to remember to set the preference as well as the state variable, and it's a bit verbose.
This PR introduces a custom react hook to wrap the two setters up in one:
```
const [value, setValue] = usePreference("some-key");
// sets both preference and state variable
setValue(new_val);
```
- Create the `usePreference` hook.
- Add stricter typing to preferences, and fix type errors.
- The Puzzle type was part of an investigation into how to approach type fixes.
- Use `usePreference` in …
=> Create usePreference hook

src/views/Game/PlayControls.tsx
https://forums.online-go.com/t/everything-is-a-tie/43102/3
- replace `engine` with `goban.engine` whenever it is accessed inside a callback.
- In #1825, I did not realize that the object held in `goban.engine` can change, so `engine` defined on [line 125](https://github.com/online-go/online-go.com/pull/1828/files#diff-8c321febed1222a8fef733e1ed63379b44297e4e21d68e46df6c0945522e50faR125) is referring to a different object than `goban.engine` at the time of the "load" event.
=> Fix "Everything is a tie?" bug

src/main.tsx
Page title is reset on every history event (as a fallback mechanism for pages which do not have a custom title, I guess?).
This breaks in such cases as:
1. click on “Home” in the navbar;
2. homepage opens and the title shows number of games where it's my move;
3. click “Home” again;
4. title is reset, i.e. it becomes just “OGS”.
- Reset page title if history event's action is not “Replace”.
=> Don't reset page title unnecessarily.

src/views/Game/Game.tsx
`portrait_tab` was always set to `"game"`, so the `portrait_tab === "chat"` and
`portrait_tab === "dock"` code paths were unreachable.
- Remove `[portrait_tab, set_portrait_tab]` state variables and all related conditional logic.
- Remove `togglePortraitTab()` callback
=> Remove portrait_tab state variable.

src/lib/data_schema.ts, src/views/Joseki/Joseki.tsx
Fixes irritatingly having to  set the filter each time you arrive at OJE.
Store the filter in `data`
=> Persist player OJE-variation-filter settings

.eslintrc.js, src/components/JosekiAdmin/JosekiAdmin.tsx, src/components/JosekiPermissionsPanel/JosekiPermissionsPanel.tsx, src/components/JosekiVariationFilter/JosekiVariationFilter.tsx, src/lib/requests.ts, src/views/Joseki/Joseki.tsx
Now that OJE is part of the Django API, it doesn't seem to need custom headers. Using the requests.ts functions seems to simplify the code quite a bit because we are no longer manually passing headers and pulling json from the response.
- JSDoc for requests.ts
- I considered adding tests too, but mocking `$.ajax` was tricky.  At some point I think we will want to switch to the `fetch` API there instead any way.
- Replace all `fetch` calls with the equivalent requests.ts function.
- Fix the `no-empty-pattern` error in `Joseki.tsx`
=> Joseki: replace fetch with requests functions

src/lib/rank_utils.test.ts, src/lib/translate.ts, src/main.tsx, src/views/User/UserByName.test.tsx
For some reason, the tests don't play nicely with Goban, especially when functions are called in a module.  One of the hacks I had in every test suite was this:
```
// workaround for setGobanTranslations not found error
// This can probably be fixed by removing sideeffects from translate.ts
jest.mock("goban", () => ({
setGobanTranslations: jest.fn(),
}));
```
By removing the side effects from translate.ts (and putting them in main.tsx), I was able to remove these mocks from the tests.
At some point, I need to figure out how to actually deal with goban code in tests, but this makes writing tests just a tiny bit easier.
- Call `setCurrentLanguage` in main.tsx, not translate.tsx.
- Remove goban mock from tests that didn't have anything to do with Goban.
=> Move side effects from translate.ts to main.tsx.

src/views/Game/Game.tsx, src/views/Game/PlayControls.tsx
In Goban, we want to add types for the score_estimate message.  There were minimal conflicts, but one issue was that score_estimate_amount could be assigned a string, and the type checker wasn't noticing it.
- Don't assign a `string` to `score_estimate_amount`, which is expected to be a `number`.
- Fix strictNullChecks type errors around `score_estimate` code.
=> Add/fix types involving score_estimate.

src/components/AutoTranslate/AutoTranslate.tsx
that does not got out to get translated, but behaves as if it did.
Fixes hitting external translation service with retries for "debug" language
Interept at the point we go to request the translation and supply a "debug" translation instead, if debug is the target.
=> Make target language "debug" a special case for autotranslate

src/components/AutoTranslate/AutoTranslate.styl, src/components/AutoTranslate/AutoTranslate.tsx
… with the original as the "FYI" afterwards.
Fixes?   Well, it's a proposal intended to fix the feeling of the translation being an afterthought, and move in the direction of the site feeling more "natural" for a non-English visitor.
If there's a translation, then display it in the primary formatting, with the original text as an FYI.
This commit also changes the way that the "Debug" language is displayed in translated form, so that it doesn't break Markdown.   If this isn't merged, I'll resubmit that bit :D
=> Made is so that the auto-translated text appears as the primary text

src/views/Game/Game.tsx, src/views/Game/GameChat.tsx, src/views/Game/GameDock.tsx, src/views/Game/GameHooks.ts, src/views/Game/PlayButtons.test.tsx, src/views/Game/PlayButtons.tsx, src/views/Game/PlayControls.test.tsx, src/views/Game/PlayControls.tsx, src/views/Game/PlayerCards.tsx
Following along with the strategy described in [Goban Centric Components](https://docs.google.com/document/d/1viy_xeQbEZ4_N6SOQll2R4vMRDjxhDz5-wMdG7GtnHI/preview), I have replaced most props for `PlayButtons` (and its subcomponent `CancelButton`) with custom hooks:
Before:
```
<PlayButtons
resign_text={resign_text}
show_undo_requested={show_undo_requested}
cur_move_number={cur_move_number}
player_to_move={player_to_move}
onCancel={onCancel}
goban={goban}
show_cancel={show_cancel}
view_mode={view_mode}
/>
```
After:
```
<PlayButtons goban={goban} show_cancel={show_cancel} />
```
- Add GameHooks.ts (a collection of hooks that subscribe to goban events).
- Reduce PlayButtons and CancelButton to 1.5 props each.
- Write tests.
=> PlayButtons: Shorten props list and derive state from goban

src/views/Game/Game.tsx
Should fix #1854
As per @benjaminpjones suggestion, which I agree with, I think this should fix the loading info from the wrong game issue we were having when flipping through games fast
=> Abort game load requests if we bail from the Game or Review page

src/views/Game/PlayControls.tsx
This checkbox has been hidden since before the open source release.
- Remove state variables `strict_seki_mode` and `rules`
- remove the Strict Scoring checkbox JSX
=> Remove strict seki mode.

src/views/Game/PlayerCards.tsx
Fixes [Forums: Negative Komi Indicator - @Lys](https://forums.online-go.com/t/negative-komi-indicator/43213/4).
Before:
After:
- Remove the plus sign when reverse komi.
=> Don't display a + sign for negative komi.

src/views/Game/GameHooks.ts, src/views/Game/PlayControls.tsx
Fixes #1855
- Create higher-order function `generateGobanHook` that takes care of a lot of the things that need to happen when handling Goban state (getting initial state, subscribing to events, canceling said subscriptions)
- Replace function implementations that seem to fit this pattern in GameHooks.
- Use`generateGobanHook` in review controls to fix the issue with initial values being unset.
https://github.com/online-go/online-go.com/pull/1856
=> generateGobanHook

src/views/Game/GameDock.tsx
Fixes #
This should fix the game icon to more correctly show which type of game it is.  See here for details:
https://forums.online-go.com/t/fix-icon-for-each-game-type/43223
=> changing the icon for a ladder game to the ladder icon

src/components/Announcements/Announcements.tsx
Fixes #1399.
You will now see a trophy indicator every time instead of with 50% probability depending on the direction of your device's clock skew.  Allowing up to 5 minutes of skew since I don't think there's any downside, but I have not tested this much.
=> announcements: show tournament announcement up to 35 minutes in advance, so clock skew does not hide it

src/views/Game/Game.styl
Fixes #1807.
When a scrollbar appears (in e.g. rengo games), it is visible instead of behind the right menu.
Before:
After:
=> right-col: use margin+padding instead of just padding

src/components/GobanContainer/GobanContainer.tsx, src/components/GobanContainer/index.ts, src/components/PersistentElement/PersistentElement.tsx, src/lib/preferences.ts, src/views/Game/Game.tsx, src/views/Joseki/Joseki.tsx, src/views/Puzzle/Puzzle.tsx
More for the [Goban Centric Components](https://docs.google.com/document/d/1viy_xeQbEZ4_N6SOQll2R4vMRDjxhDz5-wMdG7GtnHI/preview) refactor.
Goban, Joseki and Puzzles all contain similar logic that handles the resizing of the goban.  My hope is that this class can hide all this away, and make it easier to create Goban-centric views in the future.  While the resize logic was similar, they all differed slightly.  I tried to keep the implementation closest to the `Game` implementation as it seems to be the most mature (specifically it has some de-bounce logic to prevent unnecessary re-renders.)
- Create a component called `GobanContainer` that handles resize logic for the goban.
- Move all this logic out of `Game`, `Joseki` and `Puzzle` components.
- use the `setCoordinates` function to ensure …
=> Move resize logic into GobanContainer.

src/views/Game/Game.tsx, src/views/Game/GameHooks.ts, src/views/Game/PlayerCards.tsx
More for the [Goban Centric Components](https://docs.google.com/document/d/1viy_xeQbEZ4_N6SOQll2R4vMRDjxhDz5-wMdG7GtnHI/preview) refactor.
- Move `*_auto_resign_expiration`, `score`, `title`, and `show_title`, `game_id` and `review_id` into PlayerCard (no longer passed as props)
- Convert the score popups to React (these were still jquery)
=> Player cards

src/lib/popover.styl
Fixes #1604.  BUT mobile users will no longer get to see the green highlight in D. E. tournaments, which they could only see for a fraction of a second before getting redirected.
=> popover: remove max-height of 100vh, fixing click events on usernames in tournaments

src/components/GameAcceptModal/GameAcceptModal.tsx, src/components/Player/Player.tsx
Fixes confusion when reading a `challenge` being passed as a `user` to a `Player`
Create the correctly typed object for the props of `Player` and pass that in.
=> Make `GameAcceptModal` pass the right type `user` to `Player`

src/components/TimeControl/util.ts
Fixes inconsistent use of full stop in timing descriptions.
Put a full stop at the end of timing descriptions that have weekend pause
=> Put a full stop at the end of timing descriptions that have weekend pause

package.json, src/components/BanModal/BanModal.styl, src/components/BanModal/BanModal.tsx, src/components/ChallengeModal/ChallengeModal.tsx, src/components/ChallengeModal/ForkModal.tsx, src/components/Chat/ChatDetails.tsx, src/components/Chat/ChatIndicator.tsx, src/components/Chat/ChatList.tsx, src/components/Chat/ChatLog.tsx, src/components/Chat/state.ts, src/components/FriendList/FriendIndicator.tsx, src/components/FriendList/close_friend_list.ts, src/components/GobanContainer/GobanContainer.tsx, src/components/ModNoteModal/ModNoteModal.tsx, src/components/Notifications/NotificationManager.tsx, src/components/Notifications/Notifications.tsx, src/components/Player/Player.tsx, src/components/Player/PlayerDetails.tsx, src/components/PrivateChat/PrivateChat.tsx, src/components/SeekGraph/SeekGraph.tsx, src/lib/misc.ts, src/views/Game/GameDock.tsx, src/views/Moderator/Moderator.tsx, src/views/Moderator/ban_functions.tsx, src/views/Play/Play.tsx, src/views/Play/util.ts, webpack.config.js, yarn.lock
This PR adds a circular dependency detector to our webpack process and throws errors if we do things that would result in a circular dependency.
Circular dependencies sometimes work out just fine, but can result in hard to track down things-are-undefined errors as I ran into doing something unrelated, so this PR fixes most of the errors we had and adds a detector that yells at us if we accidentally add a circular dependency in the future.
Most of this is just refactor, however I did remove a `router={routes}` thing from the `<a>` link in `Player`. I have no recollection of why that was there, and I didn't see any reference to it anywhere in the code, so I am hoping it was just some really old react router thing I had to do once upon a time that's now obsolete, everything I've tested so …
=> Eliminate circular dependencies

src/views/Game/Game.tsx, src/views/Game/GameHooks.ts
Though there is no functional change, I think this makes it more clear why the hook is necessary: "cur_move" events trigger a rerender of `AIReview`, which depends on the value of `goban.engine.cur_move`.
Related: #1877
- Replace `useScore` with `useCurrentMove`
- Pass the result in as `props.move`
Note: I considered moving `move` from `AIReview.props` into `AIReview.state` because it can be derived from `goban`, but that ended up being way more verbose because we can't make use of the custom hook inside a class component. See https://github.com/online-go/online-go.com/commit/0200d664c601735aa7c162480499cafaed221b0b.
=> Game.tsx: Replace useScore with useCurrentMove

src/components/GobanContainer/GobanContainer.tsx
Fixes #1889 
- A resize should triggered on Goban "load" events
(previously odd-size boards were not centered on page load)
=> Trigger resize/recenter on goban "load" events.

package.json, src/views/PuzzleCollection/SortablePuzzleList.tsx, yarn.lock
Fixes #1845 
- Replace `react-sortable-hoc` with `dnd-kit`
It's a little unfortunate - `dnd-kit/sortable` is harder to use IMO, but I think the change is necessary since  `react-sortable-hoc` relies heavily on `findDOMNode` (deprecated).
=> Replace react-sortable-hoc with dnd-kit.

src/components/ChallengeModal/ChallengeModal.tsx, src/components/GobanContainer/GobanContainer.tsx, src/components/LadderComponent/LadderComponent.tsx, src/components/OgsResizeDetector/OgsResizeDetector.tsx, src/components/OgsResizeDetector/index.ts, src/components/RatingsChart/RatingsChart.tsx, src/components/RatingsChartByGame/RatingsChartByGame.tsx, src/views/Game/AIReviewChart.tsx, src/views/Play/Play.tsx
Fixes https://forums.online-go.com/t/website-crashing-on-all-of-my-games/43524
- Create a wrapper that replaces `ReactResizeDetector` with `React.Fragment` if `window.ResizeObserver` is undefined.
This is an imperfect solution, but makes the site usable for folks with older browsers.
- `ErrorBoundary`
- polyfills - this would actually support resizes, but also adds a dependency.
- react-resize-detector/build/withPolyfill removed in January
- [resize-observer-polyfill](https://www.npmjs.com/package/resize-observer-polyfill) last updated 4 years ago
- [@juggle/resize-observer](https://www.npmjs.com/package/@juggle/resize-observer) last updated 10 months ago
=> Add OgsResizeDetector, which does not throw on older browsers.

src/views/Game/GameLinkModal.tsx
Discourse doesn't respect certain iframe attributes such as style. Therefore,
style="width: ..; height: .." was replaced with width=".." and height="..".
Note: I also took width and height down to 345px as that is closer to the native elements on the [Observe Games](https://online-go.com/observe-games) page.
=> Modify iframe embed code to play nicely with Discourse

src/components/Announcements/Announcements.tsx, src/components/NavBar/NavBar.styl, src/views/GameEmbed/GameEmbed.tsx
Fixes
>Site notifications show up inside the embed :smile: 
https://forums.online-go.com/t/embed-live-game/42216/10
- Just tell OGS we are in zen mode in embed panes
- Remove NavBar hiding logic since it respects zen mode.
This feels like a bit of a hack since this isn't technically zen mode, but zen mode does so much, and embeds needs it all so why re-invent the wheel? :)
=> Hide Announcements (and PMs etc.) for embeds

src/lib/misc.ts
Fixes #1240 
-  Game outcome, when a number is passed, will be rounded to nearest half. 
Solution from: https://stackoverflow.com/questions/6137986/javascript-roundoff-number-to-nearest-0-5
Tested with custom komi of 0.1 and 0.4, which would normally produce a score like 4.999999999999. 
This is my first pull request, so I hope I did everything right
=> Fix for #1240

.eslintrc.js
Fixes wondering whether we have this ommitted on purpose or by ommission.
- Add the rule into the "off" section of eslintrc for now, because don't want the noise now, but we should investigate
=> Note in eslintrc that we should investigate our exhaustive-deps warnings

src/views/Play/Play.tsx
Fixes opportunities for abusing challenge links & guest accounts. and related hysteria.
Only show challenge links to the creator of the challenge - they can share it.
Plus some minor tidying/comments in Play.tsx.
=> Show the challenge link to creator of challenge only

src/lib/url_validation.ts
URL validator regex has a superfluous `*` character, which makes the regex engine go completely bananas for certain invalid inputs.
For example with `https://en.wikipedia.org/wiki/Colonoscopy@`:
```
$ time node test.js
node test.js  41.91s user 0.34s system 99% cpu 42.387 total
```
=> Fix URL validator regex

src/views/SignIn/SignIn.tsx
**Proposed changes**
Turn off autocapitalize on the username field. Chrome Android for example has it on by default.
=> Don't autocapitalize username SignIn field

src/views/Game/PlayControls.tsx
Sometimes "Sync" button is visible even when I'm in sync with the reviewer:
1. when I'm automatically following review. This happens because `GobanCore` emits `cur_move` event before updating `cur_review_move` ([code](https://github.com/online-go/goban/blob/c59e1d14303020cb9fddc515afd9cb9c8ffbfe98/src/GobanCore.ts#L1536-L1539))
2. when I'm out of sync and then reviewer navigates to my current move.
- Subscribe to `review.updated` event for `useReviewOutOfSync` hook.
=> Check if review is in sync when review is updated

src/views/Game/AIReviewChart.tsx
If I create a variation while waiting for AI analysis to process, the wiggly lines in `AIReviewChart` breaks a bit.
In a separate commit I also simplified min/max score calculation.
=> Ai review chart changes

package.json, yarn.lock
After updating to React 18 in #1779 I've often had issues with source maps, updating `source-map-loader` fixes it.
- Update to `source-map-loader-4.0.0`
=> Update source-map-loader to 4.0.0

src/views/User/GameHistoryTable.tsx
It was broken and the game history looked like this.
=> Fix capitalize function in GameHistoryTable.tsx

src/lib/SettingsCommon.tsx, src/views/Settings/AccountSettings.tsx, src/views/Settings/EmailPreferences.tsx, src/views/Settings/GeneralPreferences.tsx, src/views/Settings/LinkPreferences.tsx, src/views/Settings/ModeratorPreferences.tsx, src/views/Settings/Settings.tsx, src/views/Settings/VacationSettings.tsx
Fixes reader confusion about what the type `SettingsGroupProps` is for, and the variable `props` in the `<Settings>` component.
props -> child_props
SettingsGroupProps -> SettingsGroupPageProps
(allowing for later creation of the interface `SettingsGroupProps` for the `SettingsGroup` component, which may be needed to add ref forwarding into it)
=> Try to clarify which props are for what.

package.json, src/components/NavBar/EXV6NavBar.tsx, src/components/NavBar/NavBar.tsx, src/lib/data_schema.ts, src/lib/preferences.ts, src/main.tsx, src/ogs.styl, src/views/ChallengeLinkLanding/ChallengeLinkLanding.tsx, src/views/HelpFlows/GuestUserIntroEXV6.tsx, src/views/HelpFlows/GuestUserIntroOldNav.tsx, src/views/HelpFlows/HelpFlows.styl, src/views/HelpFlows/HelpFlows.tsx, src/views/Settings/HelpSettings.tsx, src/views/Settings/Settings.styl, src/views/Settings/Settings.tsx, yarn.lock
Fixes most feedback.
This is on top of PR #1951 .
As per package.json, this needs react-dynamic-help 1.0.2.
- There's a "Help Settings" settings page.
- Positioning appears to be mostly acceptable
- One snag is that in "mobile" layouts there is no popup on the Settings pages to say "click the dropdown and select Account"
- buy hey,  before there was no help at all :)
- this is because I haven't figured out how to have branching flows dependent on funky things like display:none
- Colors are themed and contrasted
- Drop shadow for popup didn't look that good, I think.
- The "totally reset help system state" button can be enabled with `data.set("debug-dynamic-help", true)`
- It might not be needed, because the  HelpSettings page lets you reset each flow.
- But if you have cruft from old …
=> Settings for help

src/components/NavBar/NavBar.tsx, src/views/ChallengeLinkLanding/ChallengeLinkLanding.tsx, src/views/HelpFlows/GuestUserIntroEXV6.tsx, src/views/HelpFlows/GuestUserIntroOldNav.tsx, src/views/HelpFlows/HelpFlows.tsx
This makes it so that the help flows are off by default, but get activated when a guest arrives on a challenge link.
Goes on top of #1950
Visuals and placement improved, but not quite right yet.
Settings page still coming.
=> Connect help to challenge link acceptance

package.json, src/main.tsx, src/views/HelpFlows/HelpFlows.styl, src/views/HelpFlows/HelpFlows.tsx, src/views/Settings/HelpSettings.tsx, yarn.lock
Fixes #1955, #1956
- Put "links" into the popup instead of 'x', as per #1955 
- Allow app to provide translations for the words, via props on HelpProvider
- Move to react-dynamic-help 1.1.2, to fix #1956
As a consequence of "turning off help" being an event that comes from an RDH popup, the settings page logic for displaying that is updated as well.   The previous implementation was a wrong direction, duplicating the preference in OGS preferences and RDH preference storage.  So that's fixed.
=> Use words instead of 'x' to dismiss popups

src/views/Group/Group.tsx, src/views/Tournament/Tournament.tsx
Previously, when inviting multiple players, it's hard to tell which player "Player invited" refers to.
- Show username of invited player in group and tournament invite result message.
=> Show username of invited player

package.json, yarn.lock
Fixes inability to customise dynamic help target highlighting
Added css classes instead of box shadow to rdh targets.
`rdh-target-highlight`
=> Move to rdh 1.2.0 for rdh-target-highlight class

src/components/InfoBall/InfoBall.styl, src/components/InfoBall/InfoBall.tsx, src/components/InfoBall/index.ts, src/components/NavBar/EXV6NavBar.styl, src/components/NavBar/EXV6NavBar.tsx, src/ogs.styl, src/views/Settings/AccountSettings.styl, src/views/Settings/AccountSettings.tsx
This patch finally adds the username, icon, country, website, name fields to the "Account Settings" page.
The fields are still editable on the profile pages as well, at least for the time being.
---
@GreenAsJade I removed a line
```
const { ref: profileLink } = registerTargetItem("profile-edit-link"); // cleared on Profile page
```
that was related to the help stuff you've been working on. I *think* this was not being used anymore, and would be obviated anyways, but I wanted to let you know in case I missed something.
=> Add profile fields to Account Settings page

src/views/Game/GameDock.tsx
Fixes [players messing things up by seeing what happens when you click the greyed out conditional moves button](https://forums.online-go.com/t/rengo-status/40415/1120?u=greenasjade)
Completely remove conditional moves button from Game Dock in rengo games.
(Note: previous implementation (probably by me) assumed that className `disabled` disables the link, but of course it doesn't.   In the nearby cases in the code, the greyed link gets clicked and something down stream checks and decides not to do it.  This is not practical in the case of conditional moves)
=> Get rid of the  conditional moves button in the dock in rengo games

src/components/PaginatedTable/PaginatedTable.tsx
Fixes #1717
- Resend request, but with `page = 1` after 404 error.
=> Re-try fetching pages after search/filter fails

src/components/PaginatedTable/PaginatedTable.styl, src/components/PaginatedTable/PaginatedTable.tsx
Previously, the page controls would move with the PaginatedTable when you scrolled.
Now, only the table entries move so the page controls are always visible.
I added a div around the table and applied the css there, because  `overflow-x: auto` didn't seem to have an effect on tables.
My workaround is based on this: https://stackoverflow.com/q/8706503
=> Keep page-controls visible at all times

src/views/Game/Game.styl
Fixes leaking css directive
Put `.submit-button` inside `.Game`
Note: I searched for `submit-button` and did find only the one inside Game.
=> Put `.submit-button` inside `.Game`

src/components/Chat/ChatDetails.styl, src/components/Chat/ChatDetails.tsx, src/components/Chat/ChatList.tsx, src/components/Chat/ChatLog.tsx, src/lib/popover.tsx
This PR adjusts the look of the chat notification settings. The original issue was brought to light in #1986, this PR revisits the look of the component entirely,
This PR makes the component look something like this:
=> Chat notification / highlight settings update to us checkmarks instead of buttons

src/components/Chat/ChatDetails.styl, src/components/Chat/ChatDetails.tsx, src/components/Chat/ChatList.tsx, src/components/Chat/ChatLog.tsx
This updates the chat notification settings once again to look more like how discord/slack present their settings. Also reverted the change of terminology from "highlight" to "notification", because we probably do want those to be actual notifications some day, so maybe it's best to just stick with that terminology.
New look:
@benjaminpjones
=> Chat notification settings take 3

src/views/Puzzle/Puzzle.tsx
Fixes #
.
- 張 栩 made puzzles of 4x4 board in https://www.amazon.co.jp/dp/B07CKY1VK5 . I want to solve it in the OGS puzzle.
=> Add "4x4" option in puzzle

src/components/Chat/ChatList.tsx
Links in the ChatList are slightly broken:
* clicking on icon doesn't work
* for tournaments clicking inside `div` padding takes me to wrong URL
* use `event.currentTarget` instead of `event.target`
* fix tournamets' `data-channel` attribute
=> Fix ChatList links

src/views/Overview/EXV6Overview.tsx, src/views/Overview/Overview.tsx, src/views/Play/Play.tsx
TBD I'm not totally sure this is better, but it _seems_ nicer to use the expicitly stated type of the context, rather than show that we know how surely it must have been created, and rely on that?
=> State the type of the context, matching what RDH says it is.

src/views/LibraryPlayer/LibraryPlayer.tsx
Game libraries are intermittently sorted in random order, and sometimes sorted correctly. See the below thread for some context and that other folks have noticed this.
https://forums.online-go.com/t/sgf-library-sort/42511/2
I'm not a typescript expert, but looking through the code this is the only area where localeCompare is used without specifying the compare string, here we're passing just the b object to be sorted. It seems possible that this is the source of the issue, and if not it will at least make the code consistent on this point.
I'm a first time contributor, so please let me know if I should be doing anything differently in this process!
=> potential fix for sort issue on game library page

src/components/ObserveGamesComponent/ObserveGamesComponent.tsx
Fixes limited discoverability of Malkovich function
Provide a "malkovich only" filter on the Watch page
** note: requires https://github.com/online-go/ogs-node/pull/20 in order to actually work.
=> Provide an ObserveGamesComponent filter for Malkovich games.

src/views/Ladder/Ladder.tsx
Fixes #1738
Fixes #2036 
Changes both instances of "rank" and corrects "player" referring to challenge target not self.
=> Ladder position error wording 2

src/components/PaginatedTable/PaginatedTable.tsx
Fixes #1996
`PaginatedTable`s weren't updating when `props.source` changes.  This wasn't a problem in most cases because `source` is often a single endpoint where only the query parameter changes.  But in this case, it was `groups/%%/members`.
=> PaginatedTable: Refresh on props.source change

src/models/user.d.ts, src/views/OnlineLeagueGame/OnlineLeagueGame.tsx, src/views/User/ActivityCard.tsx, src/views/User/User.tsx
Fixes not being able to tell what leagues someone is in, and whether their membership id is correct
Display people's OOL in their Profile, with the membership id visible if the backend sends it (which it only does if you're looking at your own profile, though we should add moderators  as well).
Needs https://github.com/online-go/ogs/pull/1757 to be able to show anything.
=> Show folk's OOLs on their profile

src/components/ChallengeDetailsReviewPane/ChallengeDetailsReviewPane.tsx, src/components/KBShortcut/KBShortcut.tsx, src/components/SeekGraph/SeekGraph.tsx, src/components/SeekGraph/SeekGraphLegend.styl, src/components/SeekGraph/SeekGraphLegend.tsx, src/components/SeekGraph/SeekGraphPalettes.tsx, src/components/SeekGraph/SeekGraphSymbols.tsx, src/lib/challenge_utils.tsx, src/lib/data_schema.ts, src/lib/preferences.ts, src/views/Play/Play.styl, src/views/Play/Play.tsx, src/views/Settings/GeneralPreferences.tsx
As proposed in #2050, this PR contains a number of improvements to the seek graph.
Notable changes:
- Improved resolution of seek graph
- Added shapes representing various challenge types (ranked, unranked, rengo)
- Moved challenge filters away from the bottom of the page, combining them with a legend explaining the symbols in the seek graph
- Made challenge filters affect the seek graph in addition to the challenge lists
- Added a challenge filter to hide/show rengo games
- Adjusted seek graph colors to match the current site theme
- Made the seek graph immediately respond to site theme changes
- Fixed a bug where the popover list would occasionally not show when mousing over a challenge in the bottom right of the seek graph
| Before  | After |
| ---------- | ---------- |
| <img …
=> Seek graph improvements

package.json, src/components/ChallengeModal/ChallengeModal.tsx, src/components/Notifications/Notifications.tsx, src/components/SeekGraph/SeekGraph.tsx, src/components/SeekGraph/SeekGraphPalettes.tsx, src/components/TimeControl/TimeControlPicker.tsx, src/components/TimeControl/util.ts, src/lib/misc.ts, src/views/Game/Game.tsx, src/views/Game/PlayButtons.tsx, src/views/Play/Play.tsx, src/views/Tournament/Tournament.tsx, src/views/TournamentList/TournamentList.tsx, yarn.lock
Average time-per-move calculations now consider the board size. The most important side-effect is that `isLiveGame` also considers the board size, which makes sense.
This PR also aligns the seek graph more closely with the site definitions of blitz, live, and correspondence games.
=> Migrate to use new computeAverageMoveTime function

src/views/OnlineLeagueLanding/OnlineLeagueLanding.tsx
Fixes  the player being left on the landing page with a spinner if they use a link to a cancelled game
Fixes  the player being left on the landing page with a spinner if any server error happens when they use a link to an OOL match
Navigate to the home page if the server 400's the OOL link PUT.
=> "Cancellation support" for OOLs

src/views/Settings/AccountSettings.test.tsx, src/views/Settings/AccountSettings.tsx
Fixes issue discussed at [OGS Forums: Account Verification](https://forums.online-go.com/t/account-verification/45360/6). The regression likely happened in 1722cd6fb33de4f46eb13754b6ef6215747227a9, although I didn't actually go back and run it.
The issue is that this message/button is missing:
- Fix Bug
- Write a test that would have caught said bug
=> Bug Fix: Resend validation email button missing.

src/views/Game/Game.tsx, src/views/Game/GameDock.test.tsx, src/views/Game/GameDock.tsx
Fixes issue from [OGS forums: Some reviews do not have "SGF with comments"](https://forums.online-go.com/t/some-reviews-do-not-have-sgf-with-comments/45362/3).  Regression likely occurred in https://github.com/online-go/online-go.com/pull/1865.
- Bug: "SGF with comments" button was missing from reviews.
- Root cause: `game_id` is present on reviews, because `game_id` is used to link to the original game.
- Remove `game_id` and `review_id` from `GameDockProps`, and get these values from the goban.
- Write a test that fails on the bug.
- Fix the bug.
=> Bug fix: Link to review SGFs if both game_id and review_id are present.

src/views/Game/Game.tsx
Fixes #50
This commit only adds a visual feedback and doesn't change anything else.
- Add an `alert` only on game file not found.
- refactor the `.then`/`.catch` with `try..catch`+`async`/`await`
The `async`/`await` is a syntactic sugar doesn't change any functionality (so we don't lose anything). Yet they offer SLIGHTLY more readability and improve debugging experience. With the current implementation, when debugging, we have to split the `.then()` to many `.then().catch().then().catch()`... and in comparison with `try..catch`, we just remove the outer `try{}` and we can see clearly where the error is thrown. But the change can be too so subtle for the work needed.
- improve error handling when web socket returns a 404 / 500: they should have consistent behaviour
Currently, the …
=> fix: add visual feedback for 500 error

src/views/Game/GameHooks.ts, src/views/Game/PlayControls.test.tsx, src/views/Game/PlayControls.tsx
Fixes memory leaks caused by subscribing to goban without cleaning up. In actual practice, this might happen when resizing the window.  Unlikely to have significant memory impact, but a leak nonetheless.
- Write a test to catch memory leak caused by `PlayControls` subscription.
- Add unsubscribes to the cleanup function.
Unit test relies on https://github.com/online-go/goban/pull/107
=> PlayControls: unsubscribe from goban events after unmount.

src/components/NavBar/NavBar.tsx
The old navigation bar had a keyboard shortcut to open the left pane and automatically focus the search input field.
Even though the new navigation bar has the search input always visible, I'd still like to have a keyboard shortcut for focusing it.
- Add keyboard shortcut for focusing search input.
=> Keyboard shortcut to focus the search input in the navigation bar.

src/components/ChallengeModal/ChallengeModal.tsx, src/components/TimeControl/TimeControlUpdates.ts, src/components/TimeControl/util.ts
Fixes #1628 (see https://forums.online-go.com/t/0-periods-byo-yomi/40409/ as well) and cleans up some unused code.
The two properties affected were "periods" on Byoyomi games and "stones_per_period" on Canadian games.
There were already some checks to ensure proper values, but it seems some users were (accidentally or otherwise) pressing "create challenge" before the value could be clamped to the allowable range. As with previous time control picker bugs, these malformed settings had the potential to be persisted in local storage and come back again and again.
Note that even after this fix, users can still create malformed challenge requests (not using the UI), so there should still be more validation on the backend. There may be validation already for "stones_per_period", but it appears …
=> Further prevent users from selecting time control values outside the allowable min/max range

src/views/User/UserByName.test.tsx
Fixes my OCD about commented code ;P
- Use a [MemoryRouter](https://reactrouter.com/en/6.7.0/router-components/memory-router) to set router params per this StackOverflow thread: https://stackoverflow.com/questions/58117890/how-to-test-components-using-new-react-router-hooks/58206121#58206121
- use react testing library's render method instead of React's deprecated render function.
=> Update UserByName tests to work with React Router 6

src/views/Game/Players.styl
Fixes #1625 
- Changed size from absolute (px) to relative (em)
- Increased font size for clock on portrait mode while keeping 0.8 ratio between main-time and byo-yomi / canadian.
=> Increased font size on portrait mode.

.github/uffizzi/docker-compose.uffizzi.yml, .github/workflows/uffizzi-build.yml, .github/workflows/uffizzi-preview.yml
This PR adds github workflows which will trigger uffizzi preview environments for PRs to this repo. A PoC has been created at https://github.com/waveywaves/online-go.com/pull/1. Once this PR is merged, you should see comments like https://github.com/waveywaves/online-go.com/pull/1#issuecomment-1406198574 pinned to all subsequent PRs to this repo. These comments are created after a preview env has been deployed for the PR.
To understand this PR better do check this article below on two stage workflows
https://www.uffizzi.com/preview-environments-guide/github-actions-two-stage-workflow
fixes https://github.com/online-go/online-go.com/issues/2124
=> create preview environments for every PR using Uffizzi

src/views/docs/GoResources.tsx
Original link is broken as the domain name lapsed. The new link points directly to YouTube Channel instead.
- Updates Go Commentary video link
=> Update Go Commentary video link

src/lib/preferences.ts, src/views/Game/PlayerCards.styl, src/views/Game/PlayerCards.tsx, src/views/Settings/ModeratorPreferences.tsx
For moderators to step through a person's games
arrow-buttons on PlayerCards, for moderators, which go to the player's next and prev games
moderator-option to hide these arrows, which default  on
**Needs https://github.com/online-go/ogs/pull/1780
**Improved by:  https://github.com/online-go/ogs/pull/1781  (sort by ended, started instead of id)
=> Adds "next game" arrows on PlayerCards

src/components/Player/Player.tsx
Fixes #2109, replaces #2141
Handle click event instead of mouse down in `Player`.
Previously, the game history table was being clicked instead of the player link because `Player` was handling mouse down events while the PaginatedTable row was handling mouse ups.
Also removes some code that's no longer needed.
=> Prevent click events in player popover from reaching game history table

src/views/Game/GameDock.tsx
I think this fixes #876.  
The conditional move planner would sometimes be visible to players on their turn even though it doesn't work.
- Don't show the conditional move planner when the player places a provisional stone on the board
=> Don't show conditional move planner on player's turn

.eslintignore, .github/workflows/main.yml
Fixes contributors having to wrestle with the linter (possibly without a proper dev environment).  Now a bot will push a commit fixing lints if necessary. Check out https://github.com/benjaminpjones/online-go.com/pull/4 to see this bot in action!
- Replace existing lint step with one involving [wearerequired/lint-action](https://github.com/marketplace/actions/lint-action)
- Sorry for the extra whitespace changes.  I tried to only change the necessary lines, but after a few iterations of making changes I stopped trying.  At any rate, no trailing space is probably a good thing...
- Add .eslintignore
- This is because the lint action doesn't specify src/ as the  directory to check by default
- Incidentally, this fixes my IDE's complaints every time I open a config file.
=> Use wearerequired/lint-action to autofix PRs

src/views/docs/legal.tsx
We lean on the "don't obstruct" wording quite heavily in Moderation.
Fixes moderators having to quote the long version awkwardly.
"Don't chat, obstruct, or harrass people"
=> Added the word "obstruct" into the Short Version.  

src/views/OnlineLeagueSpectatorLanding/OnlineLeagueSpectatorLanding.tsx
Fixes  late spectators being left on the landing page.
Send them straight to a game that started
=> OOL Spectators who arrive after the games starts want to go straight there

src/views/Game/PlayControls.tsx
The "copy branch to the conditional move planner" button was being shown in finished games. This PR fixes this.
=> Don't show analysis-conditional button in finished games

src/views/Overview/ChallengesList.styl, src/views/Overview/ChallengesList.tsx, src/views/Overview/InviteList.styl, src/views/Overview/InviteList.tsx
Fixes #2049 
- Clip the string and display an ellipsis 
- Show a tooltip on hover to see the full name
=> Fix display of game's name when it is too long

src/lib/preferences.ts, src/views/Game/Game.tsx, src/views/Settings/GamePreferences.tsx
Fixes #2150 Feature request: Zen Mode default option
This pull request introduces a new toggle in `Settings > Game Preferences` as the title suggests. 
This toggle works exactly the same as other toggles in the menu. I basically used them as examples. 
By "switching on" the Zen mode button, the user will enter every game in Zen mode. 
For example: I have these two test games: 
Clicking on any of them will take you to the game in Zen mode: 
Functionally, Zen mode works as normal. Pressing escape in the game above will take the user back to normal mode:
=> Issue #2150: Feature request: Zen Mode default option

src/components/Chat/ChatLog.tsx
Fixes needing to `data.set(user` as well as mock `useUser`, at least for `ChatLog`
use `useUser` instead of `data.get(user)`
=> use useUser in ChatLog (for tidier mocking)

src/components/AccountWarning/AccountWarning.styl
Fixes warning template with paragraphs getting smooshed up
format warnings with white-space: pre-line
=> Format warnings with white-space: pre-line to honour paragraphs

src/views/ReportsCenter/MessageTemplate.tsx
- Adds one new mod template for score cheating:
Our records show that you attempted to illegally change the score at the end of 
game #XXXXXXXX. This is a form of cheating and is prohibited by the 
OGS [Terms of Service](https://online-go.com/docs/terms-of-service). 
We ask that you end your games properly by accepting the correct score 
immediately after passing. Further instances of score cheating will result 
in a ban.
=> Add template for score cheating

src/components/Report/Report.tsx
Also typo in pggettext context.
Fixes potential confusion about what `user` is
- Use reported_user_id throughout
- Fix typo in pgettext context
=> Clarify which user we're talking about :D

src/views/Group/Group.styl, src/views/Group/Group.tsx, src/views/GroupCreate/GroupCreate.tsx
Fixes organisations being unable to prevent members creating tournaments
Use the `admin_only_tournaments` field to turn off create tournament buttons for users
** Needs https://github.com/online-go/ogs/pull/1802
=> Add support for creating groups with admin only tournaments

src/lib/moderation.ts, src/models/moderation.d.ts
Fixes two ways to do the same thing being used.
Do single-game annul using the /moderation endpoint.
*** Needs https://github.com/online-go/ogs/pull/1803
This also adds the API definition file for that new endpoint, hopefully coincides with @RubyMineshaft  definition
=> Do single game annulling using the /moderation endpoint

src/lib/moderation.ts, src/models/moderation.d.ts
Fixes needless and confusing reference to the word "mass" on the "annul" endpoint, in line with this backend change
** Needs https://github.com/online-go/ogs/pull/1805
=> Got rid of the word "mass" from the annul endpoint

src/lib/preferences.ts, src/views/Game/GameDock.tsx, src/views/Game/PlayerCards.styl, src/views/Game/PlayerCards.tsx, src/views/Settings/ModeratorPreferences.tsx
Fixes various annul confusions
- Rename annul flags in GameDock.tsx, for clarity
- Change "next-game-arrow" labels to "player-card-mod-controls"
- Hide the annul-with-blame hammer while the game is in progress
=> Clarify annul related naming, hide annul button on player cards of ongoing games

src/components/AnnulQueueModal/AnnulQueueModal.styl, src/components/AnnulQueueModal/AnnulQueueModal.tsx, src/views/User/GameHistoryTable.tsx
Currently, the annul queue modal is being rendered outside of the Router which causes the modal to crash if there is a review linked in the game chat. 
- Render annul queue modal from within the game history table instead of outside the Router
=> Annul queue modal bugfix 

src/lib/preferences.ts, src/views/Game/PlayerCards.test.tsx, src/views/Game/PlayerCards.tsx
Fixes people complaining about komi not appearing anymore 😝
Restore the code that displays komi in PlayerCards
Note that to make the test work, I had to change the import of React in PlayerCards.tsx.
Not sure what that's about, but it seems to work.
I also exported PlayerCard so the test could import it.  Not sure if that's "normal" 🤨  I suspect that in theory if something needs to be tested, it should be in it's own file, but meh 😝
=> Restored display of komi in player cards

src/views/User/ModTools.tsx
Fixes some uncertainty about account aliases
Display the new BID match info to moderators.
=> Add BID Alias column to aliases table

src/views/ReportsCenter/ReportsCenterHistory.styl
Fixes css warning "end value has mixed support, consider using flex-end instead"
use flex-end instead of end on history-options align-items
=> Use flex-end instead of end

src/views/ReportsCenter/MessageTemplate.tsx, src/views/ReportsCenter/ViewReport.tsx
Fixes doing all the stuff without remembering to claim
- Add selection callback to MessageTemplate, use it to claim the report
- Tidy up report claiming, so it happens the same way in all three cases
=> Selecting a template claims a report

src/components/RengoManagementPane/RengoManagementPane.styl, src/components/RengoManagementPane/RengoManagementPane.tsx, src/models/challenges.d.ts
Fixes wondering how long Rengo challenges have been hanging around.
- Add optional `created` field to seekgraph challenge payload definition
- Display the value in the RengoManagementPane
Needs https://github.com/online-go/ogs/pull/1809 in order to tell the truth.
=> Display "created" date in RengoManagementPane

src/lib/preferences.ts, src/views/Game/Game.tsx, src/views/Game/GameChat.tsx, src/views/Settings/GamePreferences.tsx
Fixes #2273 
Changes in GamePreference.tsx and preferences.tsx to select the default mode (defaults to "main")
Changes in Game.tsx and GameChat.tsx - anywhere where it was hardcoded to default to "main" for the chat mode it now uses the preference
Snuck in an unrelate change to th3 description of the Variation Move count to make the setting clearer.
-
-
-
=> Issue 2273 - Default chat mode

src/lib/moderation.tsx
Fixes alert dismissal getting in the way of moving on to the next one
- Change the ack from an `alert` to a `toast`
- Requires the file to be .tsx so we can pass the necesary `div` to the toast.
=> Changed annulment ack to a toast

src/lib/chat_manager.ts, src/views/Joseki/Joseki.tsx
Fixes comments going largely unnoticed
- Add a new dedicated global chat channel for OJE
- Relay comments on OJE positions into that channel
(note, if some other client ever started adding comments this would not help for them ... something to worry about later)
=> Relay OJE position comments to chat

src/lib/report_manager.ts, src/views/ReportsCenter/ViewReport.tsx
Fixes untyped state variable
Declare the type of `report` and extend the type to add the extra fields that come from the server.
=> Type use of Reports in ViewReport

src/views/ReportsCenter/MessageTemplate.tsx
… (and tweak gtp option name)
Fixes moderator message templates not updating when moving from report to report.
* Put all the props used in the text-setting `useEffect` into the sensitivity list
* Entitle the default template as "automod suggestion" (get rid of GPT since it can come from other places too)
=> Add missing sensitivities to text-update useEffect in MessageTemplate

src/views/Game/Game.tsx, src/views/Game/GameChat.tsx
Fixes this issue from the forums: [Bug: Variations Going to Chat when Malkovich is On](https://forums.online-go.com/t/bug-variations-going-to-chat-when-malkovich-is-on/48157)
- use the selected_chat_log from the top level Game component instead of a separate variable in the GameChat component.
- Note: if you navigate to a different game (say by clicking the TurnIndicator), this will change the chat back to the default mode.  I think this was the intent in #2274, tagging @andymarden for confirmation.
=> Use the same selected_chat_log for GameChat and PlayControls.

src/views/Game/PlayControls.tsx
Fixes #2303 
- Lower timeout on mobile to 1500ms (same as desktop)
- Only disable the button if the removed stones changed
=> Reduce time that the Accept Removed Stones button is disabled

src/views/ReportsCenter/MessageTemplate.tsx, src/views/ReportsCenter/ViewReport.tsx
Fixes moderators having to explicitly claim in the case where they don't select a template.
- Give MessageTemplate an onMessage callback, called when the template view is used to send a message
- Use MessageTemplate.onMessage to claim the report
=> Make it so that a report is claimed for a moderator if they simply send a message

src/components/Report/Report.tsx
Fixes complaints that its boring watching the moderator page looking for troll signs ;)
- Have a Troll type report that the system can generate when it sees whatever we decide we want to flag
- https://github.com/online-go/ogs/pull/1816 is needed for the server-side report generation
=> Add a type of report called "Troll" for ... tracking Troll incidents.

Gulpfile.js
Fixes 404s when trying to test firewall config features
- Add a backend proxy for `/firewall` to the dev server
=> Add a proxy for the firewall config backend routes

Gulpfile.js, src/views/Firewall/Firewall.tsx
Fixes moderators wanting to be able to generate reports from the firewall.
Have a firewall action type "REPORT" which the backend can use to generate reports for firewall configs.
Needs https://github.com/online-go/ogs/pull/1817 for backend support.
This is built on top of https://github.com/online-go/online-go.com/pull/2310 since I couldn't test it without that!
=> Firewall action: report

src/views/Firewall/Firewall.styl, src/views/Firewall/Firewall.tsx
Fixes not having a person to blame for this rule :)
- Make a new "header" row in firewall rule table
- Display the firewall rule owner, if it is supplied by the back end, in the header, along with the "notes:
- Layout tweaks associated
Needs https://github.com/online-go/ogs/pull/1819 to get the actual owner value
=> Display the owner of (the person responsible for) each firewall rule

src/views/Play/Play.tsx
Fixes confusing user experience if there's a delay in the round-loop update of the challenge list
(there can be a small delay for mass rengo)
* Close the challenge management pane when the person presses "Start"
=> Close the challenge management pane when the person presses "Start"

src/components/RengoManagementPane/RengoManagementPane.tsx
Fixes "created" not being displayed for games with auto-start
- Always display the "created", and statement about when it will start.
=> Make sure "created" for rengo challenges is always displayed.

src/models/challenges.d.ts, src/views/Overview/InviteList.tsx
Fixes wrong created date appearing in invite-only rengo challenge management pane
- Take the created date that we hope appears in the invite list response and use that in the challenge management pane
Needs https://github.com/online-go/ogs/pull/1823 to send the created date down this route.
=> Correctly display invite only rengo created date, if provided by server

src/views/Play/Play.tsx
(after eligible and user's own)
Improves:
- Users looking at older ones first, encouraging older ones to get going
- Moderators seeing old ones that need to be prodded.
Make the rengo challenge list sort by created after move-timing (while keeping eligible and other people's before ineligible and our own)
=> Change the second level sort for rengo to be by created

src/views/ReportsCenter/MessageTemplate.tsx, src/views/ReportsCenter/ViewReport.tsx
Fixes reporters wondering which report a moderator is responding to
Make `MessageTemplate` also take the reported person as a parameter, and provide template markup to substitute the reported person's name.
=> Make the reporter-templates include the reported player name

src/lib/rengo_utils.ts, src/views/Overview/InviteList.tsx, src/views/Play/Play.tsx
…so that rengo challenge cancel is confirmed, and normal challenge cancel is not.
Fixes [inappropriate confirm dialog](https://forums.online-go.com/t/rengo-status/40415/1256?u=greenasjade)
Completely separate cancel for rengo and normal challenges.
=> Use separate logic for cancelling rengo and normal challenges... 

src/views/Game/Game.tsx
Freshly created demo boards don't necessarily provide the historical ratings object. This can easily be observed by loading an appropriate demo board with Firebug open and "Pause on exceptions" active.
=> Improve handling reviews/demos without historical rating

src/views/ReportsCenter/MessageTemplate.tsx, src/views/ReportsCenter/ReportsCenter.styl, src/views/ReportsCenter/ViewReport.styl, src/views/ReportsCenter/ViewReport.tsx
Ensure that the close buttons end up sensibly-near to the messaging buttons always, stop the related reports from wrapping and taking up more vertical space (and also tweak a message template title so it fits in the space)
Fixes stuff going off the bottom of the page
Fix the layout after previous squishing up.
=> More ViewReport compaction tweaks

src/components/ModerateUser/ModerateUser.tsx, src/components/NavBar/NavBar.tsx, src/lib/misc.ts, src/lib/report_manager.ts, src/models/user.d.ts, src/views/Game/GameDock.test.tsx, src/views/Game/PlayButtons.test.tsx, src/views/Game/PlayControls.test.tsx, src/views/Game/PlayerCards.test.tsx, src/views/OnlineLeaguePlayerLanding/OnlineLeaguePlayerLanding.test.tsx, src/views/ReportsCenter/MessageTemplate.tsx, src/views/ReportsCenter/ReportedGame.tsx, src/views/ReportsCenter/ReportsCenter.styl, src/views/ReportsCenter/ReportsCenter.tsx, src/views/ReportsCenter/ViewReport.tsx, src/views/Settings/AccountSettings.test.tsx, src/views/User/User.tsx
Fixes too few people attending to score cheat reports.
Users can be given `MOD_POWER_ANNUL` as a `moderator_power`, via the edit user modal.
Users with `moderator_powers` can see score cheat reports, and claim them.   They can send warnings, system PMs.
Users with the `MOD_POWER_ANNUL` bit set can  annul games.
All community moderator messages, warnings are logged (forced, no choice)
Some sections of reports remain hidden (the anticipation is that these would be shown to users with `MOD_POWER_SEE_AI_TOOLS`).
Needs https://github.com/online-go/ogs/pull/1827 and https://github.com/online-go/ogs-node/pull/40
=> Community Moderator support: Moderator power: annul

src/lib/preferences.ts
- Changes default AI review to use score instead of win percentage
Maybe this is only at lower levels where this is a problem, but the win % just jumps between 99% black winning and 99% white winning, rarely anything in between. The score is much more useful because it's easier to compare how big your mistakes are and how narrow the margin of victory is expected to be. I assume that it's only very high level players where the win percentages don't jump so drastically. If that's the case, it seems like using the score is a better default, and high level players can change it to win % if they'd like.
=> Change default AI review to use score

src/lib/sockets.ts
Fixes not being able to test AI from a local back end
Use `OGS_BACKEND` to determine `ai_host`
=> Make localhost use localhost for ai

src/components/Report/Report.tsx
Just highlighting that the ReportTypes are an enumeration on the back end.
Matches https://github.com/online-go/ogs/pull/1829
=> Noted that report_types are a back-end enumeration

package.json, src/lib/misc.ts, src/views/Game/AntiGrief.styl, src/views/Game/AntiGrief.tsx, src/views/Game/PlayControls.tsx, yarn.lock
This patch includes two features to help thwart people being rude and unsportsmanlike.
The Anti-stalling code will appear if your opponent is not passing, the game is toward the end, and KataGo thinks there is a >99% chance that one of the players will be victorious. In that case, the players will be given a special control box under their play controls to end the game:
Similarly, the anti-escaping code will appear if a player has seemingly left a live game without finishing it. This box will show up after 30 seconds has passed and gives the opportunity to the remaining player to end the game immediately or continue waiting to see if their opponent returns.
The person who left the game will also be shown a `Toast` in the upper left informing them that this will happen, clicking the toast …
=> Anti griefing features

src/components/NetworkStatus/NetworkStatus.styl, src/components/NetworkStatus/NetworkStatus.tsx
Fixes "disconnect" showing when the socket goes down for legitimate reasons, like browsing away
* Notice if it went down for a legitimate reason, don't show an error.
Needs: https://github.com/online-go/goban/pull/133
Is on top of #2385
=> Handle went away

src/components/NetworkStatus/NetworkStatus.tsx, src/lib/sockets.ts
Fixes:
- Not warning someone if they are playing with latencies that don't match their game timing
- Flashing the warning every pong instead of leaving it there, while the problem persists
- Check if a person is playing live, and if so make sure that they have at least a reasonable latency based on time settings
- Don't take away the warning until the latency is reasonable again
=> Notice if a person is playing live with high latency and warn them

src/components/NetworkStatus/NetworkStatus.tsx, src/lib/sockets.ts
(also added engine validity check in sockets just in case)
Fixes seeing the distracting banned unless absolutely necessary
- Show banner only to participants on a live game page.
=> Show the networks status warning only to live game participants on the page

src/components/AnnulQueueModal/AnnulQueueModal.styl, src/components/AnnulQueueModal/AnnulQueueModal.tsx, src/lib/report_manager.tsx, src/views/ReportsCenter/ReportsCenterHistory.tsx, src/views/ReportsCenter/ViewReport.styl, src/views/ReportsCenter/ViewReport.tsx, src/views/User/GameHistoryTable.tsx
Depends on https://github.com/online-go/ogs/pull/1836
- Add "Inspect & Annul Games" button if detected ai games are included with report
- Add "Mark false positive" button annul queue modal if it's being used for detected ai use, which sends PUT request to `cheat_detection/false_positive` and removes game from annulment queue
- Attribute system generated incident reports to "System".
=> Handle system reports of detected cheating and false positives

src/components/Chat/ChatIndicator.styl
---
- Main content (including nav bar) shifts when toggling the ChatList.
https://github.com/online-go/online-go.com/assets/43846910/edf622c1-e95d-4a2e-b13f-717ea67a45ee
- Update the box-sizing property to `border-box` to account for border and padding in the width values.
https://github.com/online-go/online-go.com/assets/43846910/2f87aae6-419a-4f51-8e50-c40e49420b10
=> Update ChatList style to avoid content shifting

src/views/Settings/GamePreferences.tsx
Fixes inaccurate descriptive text :)
- Say "live games ..." instead of "games..."
=> Clarify that auto-zen applies to live games.

src/views/ReportsCenter/ViewReport.tsx
Bug fix for the "Inspect & Annul Games" button showing on all reports rather than only system generated AI detection reports
=> Only show 'Inspect & Annul' button on system generated reports

src/lib/image_resizer.ts, src/views/Group/Group.tsx, src/views/Settings/AccountSettings.tsx, src/views/User/AvatarCard.tsx
This is a workaround to fix #2406 where a chrome behavior (I say bug) causes a fetch error to occur if our resized files are larger than 64KiB. All resources I've found on the topic do not mention any such limit and it's unclear to me why this limit is being imposed, so it may be a temporary issue in Chrome or it may be something else that I'm not aware of. Regardless, the change to webp largely resolves the issue, and scaling images down if they are "large" is a fine solution too I think, so I think the resulting workaround is a desirable behavior regardless.
Fixes #2406
=> Updated image resizer code to use webp and have a file size limit

src/components/Clock/Clock.tsx, src/components/GobanLineSummary/GobanLineSummary.tsx
cae93c525 added the display of transmission problems to the game list. Perhaps inadvertently, this doubled the vertical space used for all games in the list.
Only use the vertical space when there is something to show.
Fixes #2418
=> Tighten up game list entries that aren't paused

src/lib/configure-goban.ts, src/views/Game/Game.tsx, src/views/Game/GameDock.tsx
Update the `isAnalysisDisabled` hook for the Goban engine to always return `false` when the game is finished.
This is a speculative fix for #2392. I can't test right now because beta.online-go.com isn't available. Posting anyway in case someone else gets a chance to test before I do.
=> Analysis is always enabled for finished games

src/components/Clock/Clock.tsx, src/components/GobanLineSummary/GobanLineSummary.tsx, src/views/User/GameHistoryTable.tsx
Show more of the relevant part of the game name in game lists before the text overflows, by replacing:
- the "Tournament Game:" prefix with the trophy icon and
- the "Ladder Challenge:" prefix with the ladder icon.
Without this change, the now-shortened prefix was the only visible text in such games.
This fixes both `GobanLineSummary` and `GameHistoryTable`.
Fixes #2424
=> Shorten names for tournament/ladder games in game lists

src/components/Clock/Clock.tsx
f2ebda37ecbe and b2f2565eeae8 already tightened up the display of line summaries for games that are NOT paused by removing the `<span>` for `transmitting`.
This follow-up also removes the span when the game IS paused. Otherwise, a blank line is added on really small screens (e.g., mobile), when the empty transmitting `<span>` and the word "Paused" don't fit on one line.
Fixes #2426
=> Skip empty transmitting in line summaries when paused

src/views/Game/AIDemoReview.tsx
This is a fix-up for new feature for AI reviews in demo and review boards. With this commit, the analysis rendering will respect the `ai-review-use-score`. Currently it's always a percentage. ~~(Let me know if you'd like me to file an issue first.)~~
Fixes #2433 _(see there for screenshots of the bug)_
=> Respect ai-review-use-score in AIDemoReview.renderAnalysis

src/components/GameList/GameList.tsx
Fixes the comparator when sorting by clock to follow strict-weak-ordering. Previously, the comparator had a fallback result of `0` (compares equal with everything). Now, there's fallback data for each game.
The effect is:
- Old: might find 99 <= THROWS <= 1.
- New: always finds 1 <= 99 <= THROWS.
If exceptions are ever thrown here, this will fix resulting sorting bugs. (Does NOT fix anything related to pause ordering though...)
=> Fix strict-weak-ordering in clock sort

src/components/IncidentReportTracker/IncidentReportTracker.tsx, src/lib/report_manager.tsx, src/views/ReportsCenter/ModerationActionSelector.tsx, src/views/ReportsCenter/ReportsCenter.styl, src/views/ReportsCenter/ViewReport.tsx
... , and let moderators see all reports for now.
Fixes:
- Reports eligible for community moderation languishing without anyone to look at them
- Errors on cornercases like "report was created before community moderation actions defined" and "moderator stole the report while community moderator looking at it"
- Detect "no actions" and always provide an "escalate" action, explaining to the community moderator in that case
- Put in hardwired constant to control if moderators see community eligible reports - and make them see them
- Make IncidentReportList only show eligible reports to the user
=> Corner case handling for community moderator actions

src/components/IncidentReportTracker/IncidentReportTracker.tsx, src/lib/report_manager.tsx
… (and stop them seeing moderator congratulation on a corner case).
Fixes users can't see their own reports
- Make `getAvailableReports` allow users to see their own reports
- Avoid showing users the "well done team" message when they happen to cancel the last outstanding report
- Slight refactor of "dont show community moderator report types to full moderators" logic, for readability.
=> Restore users' ability to see their own reports 

src/components/GameList/GameList.tsx
Using `JSON.stringify()`, I discovered that AdHocPauseControl is, in fact, in `GameType[]` from the server. Expose it in the GameType.json interface and use it for sorting, preferring the one in Goban.config when available.
Fixes #424
=> Sink paused games to the bottom of the game list

src/components/GameList/GameList.tsx
**Depends on #2442 — please merge that first.** (Does GitHub have a way to do stacked pull requests? The only commit in this PR *should be* fe286a71f49707f76f02411cdb50cb4ddbe338d4.)
Expose the `JGOFTimeControl` field in `GameType.json`, and use that to sort
clocks that aren't going to expire by computing the time remaining. This
includes:
- Sorting by the clock of the player whose turn it is NOT.
- Sorting by either clock in a paused game.
Note: 7ac13061552abd57827802f19bdde54c098a8308 fixed paused games to not be
intermingled with un-paused games, but was still sorting by an ill-defined
expiration time. This computes the time left on the clock and sorts by that
instead.
=> Sort clocks that will not expire

src/components/GameList/GameList.tsx, src/components/GobanLineSummary/GobanLineSummary.tsx
Change GameList over to sorting based on the JGOFClock instead of AdHocClock. Computing remaining time is simpler and easier to get right, especially for paused games.
The downside is that we don't initially have a JGOFClock available.  Here's how that's handled:
- New callback to `GobanLineSummary`, called the first time a `JGOFClock` is available.
- New field `force_render` in `GameList`'s state, which gets bumped by the callback.  When `render()` gets called again, the sort will be reevaluated.
Note: `force_render` is named generically because there might be other (non-clock) reasons to force `GameList.render()` to be called in the future.
Fixes #2451
=> Switch GameList to sort based on JGOFClock

src/components/GameList/GameList.tsx, src/components/GobanLineSummary/GobanLineSummary.tsx
Unify the logic between LineSummaryTable and MiniGobanList to fix sorting of MiniGobanList.
- Set `game.goban` so that `applyCurrentSort` can find the clock.
- Per 85a08f237e905d240b5c42917b47dc81d27983b2, force rendering once we have clocks for the gobans.
Before 85a08f237e905d240b5c42917b47dc81d27983b2, the initial sort for MiniGobanList was correct but wouldn't have updated over time. But that commit started depending on the link to `game.goban`, which `MiniGobanList` never set, and so it broke sorting entirely.
A couple of notes:
- Renamed `onFirstClock()` to `forceRender()` to better descript what it does.
- Moved onFirstClock logic from `LineSummaryTable.initializer()` to new method, `GameList.onGobanCreated()`, which can be reused. - Also added the setting of `game.goban` to the …
=> Unify sorting of MiniGobanList with LineSummaryTable

src/components/GameList/GameList.tsx
85a08f237e905d240b5c42917b47dc81d27983b2 switched to sorting using JGOFClock, which is more accurate, especially for paused games. This brings back sorting based on the AdHocClock until a JGOFClock is available.
[As reported on the forums](https://forums.online-go.com/t/new-better-sorting-for-active-games/50061/4), waiting until a JGOFClock is available made the mini-gobans (or line summaries) jump around a lot as things settled. If we seed the sort with AdHocClock, then only the parts it gets wrong will have to update.
Note that we can't use `AdHocClock.expiration` because we have nothing to compare it against on the `JGOFClock` side.
=> Bring back AdHocClock to seed sorting of GameList

src/components/JosekiVariationFilter/JosekiVariationFilter.tsx, src/views/HelpFlows/HelpFlows.tsx, src/views/HelpFlows/OJEIntro.tsx
Fixes users not realising that there are more "non Joseki" variations available
- Add RDH for the filter
=> Let OJE users know that the default filter is turned on

src/views/HelpFlows/HelpFlows.styl
Fixes RDH popups getting squished and not being readable on small phone layouts
- Put RDH popups at the bottom of the screen on phones.
=> Put RDH popups at the bottom of the screen on phones

src/routes.tsx, src/views/FakeGameLog.tsx, src/views/Game/GameLogModal.tsx, src/views/ReportsCenter/ScoringEventThumbnail.tsx
The coordinate lists are hard to grep.  Mods have way to mark the coordinates in the Game view (https://github.com/online-go/online-go.com/pull/1759), but [that hasn't made its way into the reports center](https://github.com/online-go/online-go.com/blob/790c053581845556f04ce88cdae299b4f3d98e62/src/views/ReportsCenter/ReportedGame.tsx#L273).  By adding these thumbnails, (community) mods will be able to view the game as the players see it.
This PR depends on some updates to what gets logged.  Namely, I would like two additional fields in the logs:
- `move_number`
- Reasoning: if the game enters scoring phase, and later resumes, we need to jump back in the move tree before displaying the board.
- Alternative considered: theoretically, one could hackily match timestamps to move numbers, but …
=> [Report Center] Use a thumbnail instead of coordinate list

src/views/ReportsCenter/ViewReport.tsx
The selection should be refreshed on each new report, but right now, the previous report's decision will remain populated.
Use the `key` prop to force a remount of the voting options when the report id changes.
Before:
https://github.com/online-go/online-go.com/assets/25233703/8494e314-765c-4cb6-ac28-d79f0b793676
After:
https://github.com/online-go/online-go.com/assets/25233703/16d5046d-3cee-4d09-8574-368f467b14a7
=> Clear vote on different reports.

src/components/AccountWarning/CannedMessages.ts, src/views/ReportsCenter/ModerationActionSelector.tsx
(and fix a canned message)
Fixes  Community Moderators not being able to act on in-progress games.
(and a canned message assuming that a report was raised by a player)
- Add prompts to support the back-end "vote actions" for deciding a game
(Needs https://github.com/online-go/ogs/pull/1868 to actually do anything)
=> Provide ACTION_PROMPTS for community moderator "call game" vote actions

src/views/ReportsCenter/ViewReport.styl
I'm finding the options have a tendency to run together on mobile.  I think we can fill the space horizontally, and add some vertical space to improve the situation.
- Add space between each option
- Fill horizontal space on mobile
=> Improve spacing for voting buttons

src/components/NavBar/NavBar.tsx
Fixes #
For the Play there is a bigger gap than for the other menu items.
Before
After
=> Fix whitespace between menu item icon and text for Play

src/views/Game/GameTimings.styl, src/views/Game/GameTimings.tsx, src/views/ReportsCenter/ReportedGame.tsx
Fixes Community Moderators not being able to sensibly judge escapes
- Make the GameTiming table with move timing actuals available in ViewReport for CMS
=> Make the game timing table available to community moderators

src/lib/report_manager.tsx, src/views/ReportsCenter/ReportedGame.tsx, src/views/ReportsCenter/ViewReport.tsx
...  if the server provide…
Fixes CMs being unsure when escaping/stalling was reported
- show `reported_game_move` if it is suppled
Needs https://github.com/online-go/ogs/pull/1902 to actually display anything
=> Display the `reported_game_move` in ViewReport

src/views/ReportsCenter/ReportedGame.tsx
Fixes case where report was made on turn `0`, and lack of translation of game presentation.
- Fix logic with null coalesce
- Translate stuff.
=> Add translation and fix "no info about `reported_at`" logic

src/views/Game/PlayerCards.tsx
Adapt to Goban change in https://github.com/online-go/goban/pull/146 and show the actual handicap stones for black separately from the handicap bonus.
To make it clear that this handicap field is not part of the score:
- Use a `<hr/>` to separate it
- Add `+` in front of scores that are supposed to sum together.
Also move white's handicap bonus to the end, after komi.
- This means that there's always a `+` in front of it, even at the beginning of the game, so it's implicitly clear that there's a bonus.
- I considered changing the text to `Handicap Bonus` but that wrapped.
Relates to #1469
=> Show handicap separately from handicap bonus

src/views/ReportsCenter/ReportedGame.tsx
Conrad mentioned there are more frozen reports in the reports center.  And indeed here is an example: [R814](https://online-go.com/reports-center/all/134814).  The event log is a whopping 5000 entries!  IIUC, rendering is still the bottleneck, so this is a quick and dirty fix to truncate the rendered list until the user opts in to showing the full thing.
- Truncate event log to 25 events before rendering
- Add "Show all" button
In a perfect world, we would do proper paging, but I think that is overkill for the mod log - returns diminish greatly after the first few entries.  That said, I'm guessing 5000 is also an artificial limit set on the backend.  It might be reasonable to lower that cap as well since we don't expect mods to look at thousands of entries.
=> [ReportCenter] truncate the game log

src/views/Game/GameDock.tsx, src/views/Game/GameInfoModal.tsx
In the "Game Information" modal, show the handicap rank difference if it's different from the handicap.
Depends on https://github.com/online-go/goban/pull/147, https://github.com/online-go/ogs-node/pull/58, and https://github.com/online-go/ogs/pull/1903.
=> Show the handicap rank difference in Game Information

src/components/ChallengeModal/ChallengeModal.tsx
This PR:
- Makes the "Create Demo" modal remember/reuse whatever settings you had the last time. Before this patch, settings were not saved for demos.
- EDIT: Makes the demo and game challenge settings independent, so that they don't clobber each other when settings are saved.
- Previously, some were independent, while some were not.
- Most game state accessors/modifiers now use a helper to consistently select between `challenge.game` and `demo`.
- Rendering code can still be shared (in fact, it's easier to do correctly now).
- See the commit message of 5635a19 for more details.
~~I'm not sure if this should be merged as-is— because of asymmetric reuse of fields saved/restored from `data`, the demo board and custom challenge pane:~~
- ~~share the board-size setting~~
- ~~do NOT share the …
=> Save settings for demo boards

src/components/ChallengeModal/ChallengeModal.tsx
Ranked games are no longer restricted to +/-9 rank difference.  Allow any rank to be specified for "Minimum Rank" and "Maximum Rank".
Fixes #2511.
=> Remove rank restriction for ranked games from open challenges

src/components/JosekiAdmin/JosekiAdmin.tsx
… (data payload on PUT), actually check the result.
Fixes lockdown button not actually doing anything.
Call the API properly.
=> Call the DB lock API in the way that the backend is expecting

src/components/ChallengeModal/ChallengeModal.tsx
Refactor some of the challenge settings:
- Move handicap and komi settings into functions so that they can be reused in demos.
- Also split up `additionalSettings()` so it's easier to understand the layout, for when demo boards add komi.
No functionality change intended.
Relates to #2501.
=> Refactor challenge settings, NFC

src/components/GobanThemePicker/GobanThemePicker.styl, src/components/GobanThemePicker/GobanThemePicker.tsx, src/lib/configure-goban.ts, src/lib/data_schema.ts, src/lib/preferences.ts
Fixes #2481
- Add the ability to supply a URL when the Goban stone theme "Custom" is selected.
Needs: https://github.com/online-go/goban/pull/145  , which adds this theme for stones.
=> Allow users to supply a URL for custom stone images

src/components/GobanThemePicker/GobanThemePicker.tsx
So that the users get to see what the stone looks like on the background they've chosen.
It also is intended to help be clear what background is in fact selected - this can be a little unobvious especially when it's the custom background.
- Render the active background styles into the stone theme selectors.
=> Make stone theme selectors show the active board styles

src/components/AccountWarning/CannedMessages.ts, src/components/ModerateUser/ModerateUser.tsx, src/components/ModerationOffer/ModerationOffer.tsx, src/components/ModerationOffer/ModerationOfferModal.tsx, src/components/Notifications/Notifications.tsx, src/components/Report/Report.tsx, src/lib/misc.ts, src/lib/report_manager.tsx, src/models/warning.d.ts, src/views/Overview/EXV6Overview.tsx, src/views/ReportsCenter/ModerationActionSelector.tsx
... plus improved "offer/accept" and notification handling.
Fixes offer notifications not getting deleted when accepted.
- Provide option to offer Game Stalling reports to CMs
- Improve offer/accept flow - CMs get told what new thing they're getting
- Reload the page to see the new tools/reports  _after_ clearing the notification after accepting an offer
Needs https://github.com/online-go/ogs/pull/1919 - moderator/CM experience might be glitchy if they try to use the new stuff without the back end in place.
=> Community moderation updates - Game Stalling handling

src/components/ChallengeModal/ChallengeModal.tsx, src/lib/data_schema.ts
Add ability to specify a custom komi for demo games.
Depends on #2513 (refactor) and <https://github.com/online-go/ogs/pull/1912> (backend fix).
Fixes #2501.
=> Add custom komi to demo games

src/components/ChallengeModal/ChallengeModal.tsx
If komi switches from "automatic" to "custom", initialize the custom komi to the default for the current ruleset.  This is a reasonable starting value for modification and still a predictable behaviour for users.
=> Initialize custom komi to the default for the rules

src/components/ChallengeModal/ChallengeModal.tsx
The `komi` field is inaccurate (and ignored) when `komi_auto !== "custom"`.  It might be nice to show the automatic komi, but right now that would be hard to do so consistently, since for small boards it depends on handicap tables that are server side.
For now, just stop showing komi at all unless `komi_auto === "custom"`.
Fixes #2527.
=> Only show custom komi in challenge descriptions

src/components/ChallengeModal/ChallengeModal.tsx
When a challenge's challenger is looking at their challenge, show their own perspective.  Continue showing the (prospective) opponent's perspective for anyone else that looks.
The code here was already trying to have this effect, but it was subtly wrong because it would flip colours if either `challenge.challenger` or `challenge.user` (presumably an old spelling of `challenge.challenger`, but maybe still set in some circumstances?) did not match the current user's `id`. Since `challenge.user` is (almost?) never set, this condition would erroneously be true for all challenges.
Specifically, this fixes the challenge text for:
- Preferred settings
- Challenger's view of challenge list that's waiting for a response
- Challenger's view of open invitations
It does not change:
- Challenger's …
=> Show challenger colour from own perspective

src/lib/misc.ts
Fixes CMs getting the wrong message about what power they are offered
- Correct the name-strings
=> Fix cut&paste of moderator power names.

src/lib/preferences.ts, src/views/Game/Game.tsx, src/views/Settings/GamePreferences.tsx
Fixes wrong terminology, confusing number in "variation stone opacity" setting
- say opacity instead of transparency
Full disclosure: this will cause people who changed this setting to have to change it again, they will lose their old value.
I wouldn't have worried about this, except I'm planning to add "Last Move Opacity"... seems like it should be consistent.
=> Use "opacity" instead of "transparency" to refer to the opacity setting for variation stones

src/components/GobanContainer/GobanContainer.tsx, src/components/MiniGoban/MiniGoban.tsx, src/lib/preferences.ts, src/views/Settings/GamePreferences.tsx
Fixes folk having a big circle messing up their custom stone images.
We've also been requested to do this in the past for folk who think it's cheating or distracting to know which stone was played last.
- Add a "game" preference for last move opacity
- Pass this into goban
- In Minigoban, it goes in with the config of the  goban
- In GobanContainer it gets set when we draw the goban by calling setLastMoveOpacity
-  That's because it seemed to complicated and "all over the place" to try to set it via config for GobanContainer applications
Needs:  https://github.com/online-go/goban/pull/150
=> Provide a preference to control the "last move opacity".

src/components/ModerateUser/ModerateUser.tsx, src/components/Notifications/NotificationManager.tsx, src/components/Notifications/Notifications.tsx
...rather than offering, when they already have some.
- Send mod power updates as direct-update when the person already has some
- Support "moderationAddition" notification to tell them about it
=> Give CMs new powers directly

src/global_styl/global.styl, src/ogs.styl, src/views/Tournament/Tournament.styl, src/views/Tournament/Tournament.tsx
Drawn games are recorded as "B+0.5,W+0.5", and were incorrectly being displayed as wins for black.
- Check the full string of match results instead of just the first character.
- Fix the elimination graph drawing to allow for both players to continue.
- Choose colours for "tie" so it looks different from a loss.
- For accessibility, use a previously-unused colour from the accessibility table that is dark (since light text will be put on top of it).
Fixes #2536
=> Fix tournament result colours and elimination graph for draws

src/views/Tournament/Tournament.tsx
Fix a copy/paste bug introduced by 0d496f86840cb25b3411013438ba2d976c17296a, which caused half of the tournament grid to show the results backwards.
|    |   P1  |   P2  |   P3  |
|----|-------|-------|-------|
| P1 |       | wrong | wrong |
| P2 | right |       | wrong |
| P3 | right | right |       |
Fixes #2539
=> Fix copy/paste bug in tournament grids

src/views/Game/PlayerCards.tsx, src/views/Game/Players.styl, src/views/docs/RulesMatrix.tsx
Now, the ruleset and handicap are directly shown in the black player card (except in Zen mode), in the same spot where the white player card has komi.
- The ruleset uses the two-letter country code for any rules named after a country, and "Ing" and "AGA" for the Ing and AGA rules.
- The rules matrix document now includes the the short code in parentheses.
- The handicap uses the unicode for a circled number up to 50. After that, it uses parentheses (such as "(51)"), which is the old way to circle numbers on a typewriter.  I think this won't come up in practice.
Things considered and not implemented (but could be tried again in the future).
- Link to the rules matrix.  I tried this out, but I was worried someone might accidentally abandon a game when trying to pop out the scoring panel.
- …
=> Show the ruleset and handicap stones in the black player card

src/views/LadderList/LadderList.tsx
The board size is included in every ladder name.  Stop including it redundantly in the link from the ladder list.
=> Remove redundant board size from ladder list

src/views/ReportsCenter/ReportedGame.tsx
Fixes minor annoyance where the "Show all" button showed up on reports with short game logs
https://github.com/online-go/online-go.com/assets/25233703/4ae94466-0e10-44de-a117-66485bfa8718
=> Don't show the "show all" button if the log is small

src/views/Tournament/Tournament.tsx
When there's an if-game in a double-elimination tournament, both players have lost a game and are notionally in the "second bracket".  Update the drawing code to do something reasonable for that case.
- Always draw finals "in the middle" if either player came from the second bracket.
- Always connect lines back to the source.
This handles any backend change to support this forum proposal: https://forums.online-go.com/t/update-to-double-elimination-tournament/50521
=> Fix double-elimination graph for if-games

src/views/Game/GameLogModal.tsx, src/views/ReportsCenter/ReportsCenter.styl
There is feedback in the forums that the game logs are still hard to parse. @pdg137 provided good, specific suggestions in this post: https://forums.online-go.com/t/feedback-on-the-new-game-log/50372/2.  Additionally, here are more threads with some general confusion: https://forums.online-go.com/t/bug-log-shows-no-scoring-phase-images/50631, https://forums.online-go.com/t/questions-about-the-report-center-and-community-moderation/50645.
- Always show the board for "stones" events, even when it's `stones: ""`
- Don't display `strict_seki_mode` - it doesn't provide signal to mods when the feature is turned off.
- Layout adjustments
- More space between log entries
- Align cells to the top of the row
- Put each field on its own line - abutting elements and wraparound is a little confusing.
=> [Reports Center] Some display improvements to the game log

src/components/Clock/Clock.tsx, src/components/GameList/GameList.tsx
Borrow from the syntax for Canadian time to call out absolute time.
- Canadian time says "3 Days/10" when there are 10 moves to make in 3 days.
- With this, absoluate time says "3 Days/*".
Addresses this forum thread asking for an indication in the game list of which games are using absolute time:
https://forums.online-go.com/t/suggestion-sort-games-with-absolute-time-settings-to-appear-at-the-top-of-ones-list-of-games-when-sorting-by-time-remaining/50649
EDIT: also improved sorting; details at https://github.com/online-go/online-go.com/pull/2557#issuecomment-1925863507.
=> Indicate absolute time using '/*' and improve clock sorting

src/components/Chat/ChatLog.tsx, src/components/PrivateChat/PrivateChat.tsx, src/views/Game/GameChat.tsx
Invert pgettext and interpolate calls for the three instances of:
"Message {{who}}"
... so that "message" can be translated in the suggested text in chats.
From the forums: https://forums.online-go.com/t/no-sgf-from-just-part-of-my-games-why/50453/17
FWIW, I manually tested that I still get the expected prompts in English in the three places in the interface.
=> Fix order of pgettext and interpolate for "Message {{who}}"

src/views/Group/Group.tsx, src/views/Ladder/Ladder.tsx, src/views/Tournament/Tournament.tsx
Add frontend support for handicaps in group ladders:
- Enable configuration on the group page.
- Show the setting on the ladder page.
- Turn on handicaps by default when creating new tournaments.
One slightly awkward thing is that the group page canonicalizes the type as a `number` (0 or -1) and tournament page uses a `string` ("0" or "-1"), depending on what the backend expects.  If you'd rather have consistency here, I can change the backend to expect a string for the group page and convert to a number in the backend.
Fixes #2553
Depends on https://github.com/online-go/ogs/pull/1933
=> Allow groups to turn on handicaps for their ladders

src/lib/misc.ts, src/views/Game/Game.styl, src/views/Game/Game.tsx, src/views/Game/PlayerCards.tsx
In the black player card, the rules codes can be mistaken for initials of the black player.  Move them out, just below the player cards, into an area for condensed game information with small font.
- Rules, aligned right.
- Ranked games, "Ranked", aligned left.
This is an option for addressing [feedback from the forums](https://forums.online-go.com/t/the-ruleset-of-the-game-should-be-easier-to-see/39165).
Draft for discussion. I'll post screenshots in a moment.
=> Move rules out of the black player card

src/components/Clock/Clock.tsx
Encourage CSS layout to keep the `/*` absolute time indication with the main time by putting it in the same `<span>`.  When the main time has a line break, this prevents creating an extra one just for the `/*`.
I.e., instead of:
6 Days 23
Hours
/*
We get:
6 Days 23
Hours/*
EDIT: after feedback in the forums, seems `+0` is more intuitive:
6 Days 23
Hours+0
=> Keep absolute time indication with main time

src/views/Tournament/Tournament.tsx
If the tournament director clicks "Save Tournament" after making edits, when they're accepted by the server, the server will send a PUSH notification on the tournament channel asking all clients to reload before sending back "success".
Delay this reloading action until we have a response from the "Save" request. Previously, the reload was aborting the about-to-succeed request, kicking the client back into edit mode.
Fixes #2571
=> Delay reloading tournament when saving edits

src/views/Tournament/Tournament.tsx
Refactor `updateEliminationTrees` to tease apart:
- planning the graph from
- rendering the graph
... to make it easier to reason about where there's computation and where there's rendering.
No functionality change intended.
With this in place, it'll hopefully be easier to:
- Analyze and fix the graph update rendering bugs in #1416
- Untangle the `useRef` vs. `useState` issues making #2573 hard to implement correctly
=> Refactor updateEliminationTrees into pieces, NFC

src/views/Tournament/Tournament.tsx
This series of commits:
- Splits the elimination graph out as a separate component
- Also splits outs a number of its elements for convenience
- Converts it to use JSX for everything but the SVG rather than manipulate the DOM directly
- Memoizes the computations with dependencies
- Clears the SVG before drawing new lines
This makes it so that elimination graphs are drawn correctly when navigating between two tournaments (or when they update live).
Fixes #1416
=> Fix elimination graph to update on changes

src/views/Tournament/Tournament.tsx
In the Tournament component, convert from a ref:
const tournament_ref = useRef<TournamentInterface>(...);
to a state:
const tournament = useState<TournamentInterface>(...);
This enabled the following additional changes:
- Remove `refresh()`.
- Removing redundant state, switching to `useMemo` for `sorted_players` and
`raw_rounds` and local variables for others.
- Reset non-tournament state when `tournament_id` changes.
Depends on #2575 (builds on top of it). The diff here will be hard to read until that lands.
=> Convert tournament from useRef to useState

src/components/Report/Report.styl, src/components/Report/Report.tsx
Fixes, or at least hopefully lessens, occurrence of "wrong report type chosen"
- Make report category description more readable (layout)
- Clarify some report category wording
- Don't have 'stalling' first, because people chose it when they mean 'escaping'.
=> Clarify presentation of "report types"

src/views/ReportsCenter/ViewReport.tsx
Fixes one case at least where CMs might thing they are being asked to vote again
- Tell them that the report is already  handled if it is escalated
=> Disable mod action selector if report is escalated

src/components/ChallengeModal/ChallengeModal.tsx
Addresses #2569
In the challenge dialog, adds a link to a selected AI Opponent's profile page, using the PlayerIcon (if present) and username of the bot.
=> Add link to selected AI Player profile page in Challenge dialog.

src/views/Tournament/Tournament.tsx
Fix [sentry issues](https://github.com/online-go/online-go.com/pull/2577#issuecomment-1940383513) by delaying computation of rounds until everything is loaded.
=> Avoid computing rounds until everything is loaded

src/views/Game/Game.styl
The margins were uneven (left: 0, right: .5rem).  It was introduced in https://github.com/online-go/online-go.com/pull/2355 to address display jitter on desktop, but I don't believe the change should have been applied to portrait layout as well.  The wider margin and un-centered board recently drew criticism in [the forums](https://forums.online-go.com/t/give-max-size-to-the-board/50375/6)
Taken in Firefox's Responsive Design tool (device: Samsung S20, display width: 360px)
=> Center the board on mobile.

src/lib/report_manager.tsx, src/views/ReportsCenter/ViewReport.tsx
Fixes staying on the last report after voting on it (should say "All Done")
Also might fix the "reappearing report" bug 🫣  🐞
- Don't call "next" until the processing of the voted report is handled
- Disallow "escalated" reports available in the CM's `reports` list
=> vote handling sequence bugfix

src/views/Game/Game.styl
I did this before I noticed @benjaminpjones's https://github.com/online-go/online-go.com/pull/2582. My main goal was to fix mobile, but still I think we can get rid of the 8px margin under all circumstances.  The right-col already has its own left margin so I don't see why we should also have a right margin on center-col.
Before:
After:
Without the highlighting, so you can see it's not ridiculous:
A larger window size showing the closest the board ever gets to the stuff on the right:
=> Game.styl: remove unnecessary 8px right margin on "center-col", so board can get larger

src/components/IncidentReportTracker/IncidentReportTracker.tsx, src/lib/preferences.ts, src/lib/report_manager.tsx, src/views/ReportsCenter/ReportsCenter.tsx, src/views/Settings/ModeratorPreferences.tsx, src/views/Settings/Settings.tsx
Fixes folk complaining if they can, or if they cannot, see how many reports are remaining.
- Make the `DAILY_REPORTS` a preference, controlled on Moderator Settings
- Let CMs use this setting
- Fix up "available reports" logic so that you don't see any if you have done your quota
=> Moderator pref to control report quota

src/components/Player/Player.tsx, src/views/Tournament/Tournament.tsx
After reviewing some of the Tournament PRs, I realized the lack of types on core objects such as `rounds` and `sorted_players` hurts readability.  This PR reduces the number of `any`s in this file from 85 to 74.
- Add `Round` type, and use it where possible
- Fix some other types where possible
- I believe all of these changes are types only, so this should be pretty safe.
=> (some) Tournament.tsx typing

src/views/Settings/Settings.tsx
Fixes uninitiated folk overlooking that you have to change this in two places 😅
- Comment about the fact that mobile has a different component for the Settings menu
=> comment - different component on mobile

src/components/Report/Report.tsx
to try to reduce people reporting escaping as stalling.
This is a significant problem, because it presents CMs with a difficult choice of warning an escaper for stalling - a poor message - or escalating ... which increases the chances of the report falling through to full moderators.
=> Change "Game Stalling" to "Playing Stalling Moves" 

src/lib/preferences.ts, src/lib/report_manager.tsx, src/views/Settings/ModeratorPreferences.tsx
Fixes  mods not being able to chose to help with reports that CMs are eligible for
- Give mods a preference that lets them see all CM reports, escalated or not.
=> Give mods a pref to see unescalated reports

src/components/TabCompleteInput/TabCompleteInput.styl, src/components/TabCompleteInput/TabCompleteInput.tsx
to try to ensure that phone browsers give users an enter button
Fixes ... hopefully... https://forums.online-go.com/t/unable-to-reply-to-group-chat/49861?u=greenasjade
- Wrap the `input` in a non-submit `form` to provide a hint to phone browsers that this input needs an enter button
=> Wrap the <input> in chat boxes in a form and provide hint

src/components/TabCompleteInput/TabCompleteInput.tsx
The minimal change suggested to fix https://forums.online-go.com/t/unable-to-reply-to-group-chat/49861?u=greenasjade
- add an `enterKeyHint` to the   `input` of `TabCompleteInput`
This doesn't break group chat or game chat for me, at various screen widths, but I can't easily test whether it fixes group chat as requested (since installing an android simulator doesn't count as "easy" 😝 )
=> add an enter key hint to TabCompleteInput

src/views/Tournament/Tournament.tsx
After f0a617aa009781d1fcbb7074df04e0ac7b68edb2, tournament is immutable state (new copy on changes), not a mutable ref, so the renderExtraPlayerActions callback wasn't being kept up-to-date when the tournament changed.  Split it out to its own `useEffect` that updates when the relevant tournament fields do.
Tested:
- Director of started tournament (disqualify and adjust points)
- Director of not-started tournament (kick)
- Non-director (no actions)
- Switching between them via the search box, which reuses the same component
Fixes #2606
=> Update setExtraActionCallback whenever the tournament changes

src/views/Tournament/Tournament.tsx
Follow-up to #2607. I missed the cleanup function before. Couldn't find anything broken without it, but it should probably be there.
=> Add missing cleanup function from 9a3f6fec611f965a531939e38241adaeace2284a

src/components/Player/Player.tsx
Fixes #2343
This shortens a deleted username's display to be `deleted-xyz...`
=> Fix #2343, shorten deleted username display

src/components/IncidentReportTracker/IncidentReportTracker.tsx, src/lib/report_manager.tsx, src/lib/report_util.ts, src/views/ReportsCenter/ViewReport.tsx
Fixes CMs not having good insight into duplicate reports
- Show the 'related reports" list to CMs (filtered by "can they see that type")
=> Show CMs a list of related reports that they are allowed to see

src/views/ReportsCenter/ReportedGame.tsx, src/views/ReportsCenter/ReportsCenter.styl
Fixes  extra scrolling by mods and CMs
- Put "created by" alongside "Game heading"
- Put "reported on turn" into game info, which is less tall than the goban so has space for it
** This PR is on top of #2616.   It doesn't _have to be_, but they operate on the same code, so it's easier to manage if it is.
=> Optimize vertical space in view report

src/views/ReportsCenter/ReportedGame.tsx, src/views/ReportsCenter/ReportsCenter.styl
(and slight layout tweak: MiniGoban at top of column)
Fixes wondering what the time settings for the reported game were
- Put `shortTimeControl` text in the GameInfo section
- lay out reported game container's Manitoban with justify-content: flex-start
=> Add the game time control into ViewReport 

src/components/Report/Report.tsx
and require an explanation for "stalling"
... here's a novel idea:  let's make the title for "my opponent stopped playing" say "stopped playing" 
Fixes ongoing stream of escaping reported as stalling (which is a hassle for CM's, because they can only vote for stalling outcomes in this case).
- Change wording of "escaping" to "Stopped Playing"
- Require a description for stalling (so folk have to be more sure that this is what they want to report, and they hopefully tell us where to look)
=> Change escaping title to "Stopped Playing", 

src/components/AccountWarning/CannedMessages.ts, src/views/ReportsCenter/MessageTemplate.tsx
Fixes challenges for CMs in responding to "wrong report type"
- Change the wording so it says "we don't see what you reported" rather than "we don't see anything wrong"
=> Tweak the message that CMs vote for about "we don't see the problem"

package.json, yarn.lock
Fixes # console warnings upon instantiating a Line chart
- Lock version to 0.84 until they fix https://github.com/plouc/nivo/issues/2539
=> Lock nivo version because their most recent update has warnings

src/views/ReportsCenter/ReportsCenter.tsx, src/views/ReportsCenter/ReportsCenterCMInfo.styl, src/views/ReportsCenter/ReportsCenterCMInfo.tsx
Fixes wondering how the voting is going
- Plot the aggregate votes by day in graphs on a new "CM Info" section in ReportsCenter
* Needs: https://github.com/online-go/ogs/pull/1950
*
=> Show some CM overall usage graphs in report center

src/views/HelpFlows/CommunityModeratorIntro.tsx
Fixes potential confusion (and hence non-consensus) 
- Make the help say what we currently want, not what we're aiming for in the future.
=> Make the dynamic help for escalate option consistent with the guide.

src/views/Game/GameTimings.styl, src/views/Game/GameTimings.tsx
Fixes  scrolling down to see if it was a grievous escape
- cssed the last row (final action) of game timing up to the top to reduce scrolling to find it
(somewhat less elegant layout, but more useful)
=> "Final action" to the top of game timings

src/components/PaginatedTable/PaginatedTable.tsx
Headers that couldn't be used for sorting got dropped in 4e677869059e414c3c7c368d4f2997f2ac7c7f92. Put them back.
=> Show headers even if they can't be used for sorting

src/components/Clock/Clock.test.tsx, src/components/Clock/Clock.tsx
This is an attempt to prevent wraparound in narrow contexts, which can cause layout issues in the player cards on the Game page. See discussion/poll at [OGF: Should time control show days without hours?](https://forums.online-go.com/t/should-time-control-show-days-without-hours/51213)
To summarize, the "6d 3h" format the overwhelming preference (93%) in the multiple choice poll.  One user cited precision as a reason for choosing this over an option like "6 Days" that keeps long-form units, but drops hours.  Another user pointed out that the Sente Android app uses this format.
I've broken this into four commits:
- One basic component test (~66% coverage of the file)
- In depth test of `prettyTime()` (100% coverage of the function)
- Clean up `prettyTime()` a bit (no functional changes)
- …
=> Shorter clock strings: "6 Days 3 Hours" -> "6d 3h"

src/components/AccountWarning/AccountWarning.tsx, src/components/AccountWarning/CannedMessages.ts, src/components/Report/Report.tsx, src/lib/moderation.tsx, src/lib/report_util.ts, src/models/warning.d.ts, src/views/ReportsCenter/ReportTypeSelector.tsx, src/views/ReportsCenter/ViewReport.styl, src/views/ReportsCenter/ViewReport.tsx, src/views/User/ActivityCard.tsx, src/views/User/UserVoteActionSummary.tsx
Fixes CM escalating because the report is of the wrong type so they don't have suitable voting options
- Make the `Report Type` selectable on ViewReport, send a `retype` POST if they decide to change it
-- Disable this if the report has already been retyped
- Provide info message to reporter for use when this happens.
Needs https://github.com/online-go/ogs/pull/1951 - otherwise "retype" will 404.
=> Implement ability to change report type.

src/views/Puzzle/Puzzle.tsx
Related to #1031 
Also requested in
https://forums.online-go.com/t/resource-for-making-custom-puzzles-with-randomised-order/50994?u=shinuito
- Add a yellow (resuing danger colour) "Random" button beside the next puzzle button, to jump to a random other puzzle in the same collection.
- Doesn't show up if there's only one puzzle in the collection.
- If the random puzzle id chosen is the current id, then go to either the puzzle preceding this one if available or the next one in case of it being the first puzzle. (Less likely when there's more puzzles in the collection anyway).
=> Button for Random Next Puzzle

src/views/Game/GameChat.tsx
Fixes issue reported in the forums:
https://forums.online-go.com/t/clickable-move-numbers-in-chat/51503
> But with the normal game moves (red arrow), that doesn’t seem to work. It would be very handy if that would work the same way.
> 
> Thanks.
> 
> Example: [FMfirst vs. Holon 4](https://online-go.com/review/1254540)
> ![8be3627e2e3946c1b8945368558dcad19fdc86b4](https://github.com/online-go/online-go.com/assets/1334620/bf4db4be-b47b-42ee-a6d2-2fc77aa2a72a)
=> Fix move number links in review/demo boards

src/views/Game/GameChat.tsx
Delete code related to analysis being disabled from the review/demo code path.  Since 72f9c2b70a56a55a5e056f06908a5f2564baf122, finished games have always had analysis enabled.
Interestingly, this code looks like it was backwards, turning on analysis only when disabled???, but turning on analysis in reviews is probably meaningless anyway.
Noticed after moving it in 3dddbb68d3a43126a69a892a835000f165c32993.
Was about to tack this onto https://github.com/online-go/online-go.com/pull/2659 but you merged too quickly :).
=> Delete some dead code

src/routes.tsx, src/views/Game/Game.tsx
Per this forum suggestion: <https://forums.online-go.com/t/clickable-move-numbers-in-chat/51503/5>
> Somewhat related, appending the move number to the url of a review doesn’t work to navigate there like it does in a game. Having to type that isn’t as convenient, but being a real url the plus is it is shareable externally.
Tested with <https://online-go.com/review/1254540/3> (well, via http://localhost:8080).
=> Make move number URLs work for reviews and demos

src/views/ReportsCenter/ReportTypeSelector.tsx
Fixes blank appearing in selector for Other reports
- Add "other" to supported selection types
=> Add "other" to the report types that `ReportTypeSelector` knows about.

src/components/AccountWarning/CannedMessages.ts, src/models/warning.d.ts
- Support (implement)  the `bot_owner_notified` canned message
=> Notification message for bot reports

src/routes.tsx, src/views/Register/Register.tsx, src/views/SignIn/SignIn.tsx
Before this commit: when social logins succeed after Register or SignIn views, they currently show the content from the ObserveGames view instead of from the Overview view. This is because `config.user.anonymous` is true when the Default component is loaded.
Username/password signins don't have this problem because they force a reload by explicitly setting `window.location.pathname`.
This is a speculative fix (I can't test the OAuth stuff), adding a `/reload` route that uses the same trick for social logins.
=> Add `/reload` route to fix the default view for social logins

src/routes.tsx
Rather than directly manipulating window.location.pathname in WaitForUser, switch to useNavigate to avoid leaving `/wait-for-user` on the history stack.
Fixes a corner case in #2672.
=> Replace '/wait-for-user' in history

src/components/SocialLoginButtons/SocialLoginButtons.tsx
Should fix #2673
Not sure if this broke somewhere along the way or if it never worked. Either way, been broken for awhile - just goes to show just how not popular login with apple is though..
=> Fix apple id login url

src/views/Register/Register.tsx
I just found an embarrassingly unsaved buffer... the Register view has been going to the now defunct `/reload` instead of `/wait-for-user`.
=> Add missing change from d60dc056ff0efb7a0f1f133224610f12e5d11e72

src/components/AccountWarning/CannedMessages.ts, src/models/warning.d.ts, src/views/ReportsCenter/ModerationActionSelector.tsx
Fixes CMs not being able to explain that cancel is OK
- Add a "not escaping, they cancelled" vote option
=> Added support for "not escaping, cancelled" CM vote option

src/components/AccountWarning/AccountWarning.styl, src/components/AccountWarning/AccountWarning.tsx, src/components/AccountWarning/CannedMessages.ts, src/models/warning.d.ts, src/views/ReportsCenter/ModerationActionSelector.tsx
Fixes canned messages collapsing into one blob of text
- Format canned messages with `white-space: pre-line`, and adjust the input text to suit.
Note: this is on top of/inclusive of https://github.com/online-go/online-go.com/pull/2689  so that the new message in that PR gets this treatment as well.
=> Better canned message format

src/views/Tournament/Tournament.tsx
Once a Swiss tournament starts, it has a fixed number of rounds.  Show them. This addresses one of the [forum complaints][1] about Swiss tournaments.
[1]: https://forums.online-go.com/t/how-many-rounds-should-a-swiss-tournament-have/51168
=> Show number of rounds in Swiss tournament

src/components/AccountWarning/CannedMessages.ts
Fixes {{reporter}} appearing in warning messages
- Do the interpolation properly, with braces
=> Fix warning message interpolations

src/components/AccountWarning/AccountWarning.tsx, src/lib/hooks.ts
Fixes players having to wait the dismiss-delay during a live game.
- Have AccountWarning check if they're on the Game page, and if so then wait till a live game is not in progress to show the warning, by polling `gobal_goban`.
=> Defer warning till end of live game

src/components/Notifications/NotificationManager.tsx
Fixes #
- Change the format of the notification when it's your move in correspondence games to remove the game id and instead include the username of the opponent.
I feel that the game id does not have any use in the notification, whereas I think the opponents name would be more useful.
I am new to this codebase so any advice would be useful, specifically if there's an established method for finding the name of the opponent.
=> Include opponent's name in turn notification

src/views/Game/Game.tsx, src/views/Game/GameDock.tsx
Fixes #2618 
- When the tournament is hovered over, it displays the name of the tournament instead of a generic phrase
- This is done by getting the tournament info when the game loads
Potentially this could be also done with ladder games.
It would also be nice to cache the tournament info to avoid the request, but I'm not familiar enough with potential solutions.
=> Trophy icon tooltip to include tournament name

src/views/User/GameHistoryTable.tsx, src/views/User/User.styl
Fixes #2708
- Add a new column with the header "Hd" with each row containing the number of stones.
=> Add handicap to game history table

src/components/NetworkStatus/NetworkStatus.styl, src/components/NetworkStatus/NetworkStatus.tsx
Fixes: [“Bad connection” notification banner obscures players’ time](https://forums.online-go.com/t/bad-connection-notification-banner-obscures-players-time/51970)
- Added a close button the the network status pop-up which relegates it back to the little icon above the profile
- Until reloading, on multiple disconnects, the pop-up would only show the first time
=> Add close button to network status pop-up

src/views/Game/ConditionalMoveTreeDisplay.tsx, src/views/Game/Game.styl, src/views/Game/PlayControls.tsx
Fixes #251 
- Add pass to the conditional move planner
Is there a nicer way to localise the pass message than the check I used? I considered having the prettyCoord function return undefined when given invalid moves instead of the string `pass`.
I'd also like some feedback on the UI here:
=> Add pass to conditional planner

src/components/AccountWarning/CannedMessages.ts
Fixes the urge to ask reporters "why are you reporting stalling when you didn't pass"
- Tell no_stalling reporters that they needed to pass
=> Clarify "no stalling" message with note about "you have to pass"

src/components/Report/Report.tsx
Fixes a stream of annoying escaping reports when the person resigned.
- Check if the accused resigned, and if so don't accept an escaping report
=> No escaping reports for resignations

src/views/User/GameHistoryTable.tsx, src/views/User/User.styl
Fixes distracting column of '0', higgly piggly numbers.
- Right justify handicap number, show '-' for none handicap in GameHistoryTable.
-
-
=> Tweak handicap render in GameHistoryTable

src/views/GoTV/GoTV.tsx
Fixes bug where autoplay setting works for api hit, but not UIPush
=> Fix bug with GoTV autoplay setting

src/views/Moderator/Moderator.tsx
-  Display "System" instead of a link to [NULL USER] for system generated actions in mod log
=> Display 'System' instead of NULL USER in mod log

src/views/GoTV/GoTV.tsx
Fixes bug introduced in most recent GoTV update where fetching an empty array of streams causes the loading message to display forever
=> bugfix: don't set isLoading to true after fetching empty array of streams

src/components/AccountWarning/CannedMessages.ts, src/models/warning.d.ts, src/views/ReportsCenter/ModerationActionSelector.tsx
Fixes CMs not being able to sensibly respond to duplicate reports
- Give CMs an option to ask reporters not to do that
- The same message that moderators have available
(Won't actually do anything till https://github.com/online-go/ogs/pull/1972 is in, which will send them this option)
=> Add messages and type for "duplicate report" handling for CMs

src/components/IncidentReportTracker/IncidentReportTracker.tsx
Fixes the daunting number being even higher than effectively it is
- Don't show system generated reports (which most moderators won't look at) in the report count
=> Filter system reports out of the "outstanding report count".

package.json, src/views/ReportsCenter/ReportsCenterCMInfo.tsx, yarn.lock
Fixes  old (irrelevant) data, messed up axis
-  Show only 120 days of data (calculated properly) 
- Prep for making it zoomable if we feel like it (back end supports it now)
=> Display only 120 days of CM voting graph

src/views/Group/Group.tsx
Fixes dubious layout, and not being able to clean up "tournament records"
- Put Active Tournaments at the top of the Card
- Allow moderators and admins to delete tournament records
- Put non-render functions above the render routine, so that "render is last" in the file.
=> Better group tournament presentation

src/views/ReportsCenter/ViewReport.tsx
Fixes crashed report centre from goban exception
- Put error boundary around the details of the report, so the header still functions
=> Add error boundary around goban in ViewReport

src/components/AutoTranslate/AutoTranslate.styl, src/components/AutoTranslate/AutoTranslate.tsx, src/components/IncidentReportTracker/IncidentReportCard.tsx, src/components/IncidentReportTracker/IncidentReportTracker.styl, src/components/IncidentReportTracker/IncidentReportTracker.tsx, src/components/Report/Report.tsx, src/lib/data_schema.ts, src/lib/report_manager.tsx
Fixes CMs having hassles knowing how to vote to give sensible messages about duplicate reports
- Instead of opening the Report form, open the IncidentList, if the user already has opened a report on that game
* : built on top of #2752, because it doesn't really make sense to do this if they can't edit their reports.
=> Prevent report dupes

src/components/Report/Report.tsx
Fixes error on opening report dialog with `already_reported` not having a value yet.
-  Default it to empty.
=> Fix uninitialised `already_reported`

.vscode/cspell.json, src/views/Game/GameLogModal.tsx
Fixes confusion about what game log is saying
- Get rid of "color" field display in stone_removal_stone_set - not needed, can be confusing (color of what?)
- Get rid of needs_sealing display
- Use words that say what the "removed" flag means
- Don't show stone_removal_stone_set events with no stones (unclear what these are)
- Dont set log state till we're mounted
=> Made game log easier to understand (and fixed set-state-before-mounted).

src/views/Game/GameLogModal.tsx
Clarified entries from auto-score events (and put in player colour more tidily)
Fixes wondering what mysterious events are (or not showing them at all)
- Say "auto-scorer update" when we see `needs_sealing` provided (even if its empty)
- put ( colour ) next to player name
=> Clarify auto-score in game log

src/views/ReportsCenter/UserHistory.tsx, src/views/User/ModLog.tsx
Fixes CMs having to squint at a huge list, looking for warnings
- filter to "only warnings" in `UserHistory` for CMs
(Note, this could be done in the backend, it already filters some stuff, but since this is not "they must not see" but rather "they prefer not to see", I've put it in the front end)
=> Filter the `UserHistory` table for warnings only for CMs 

src/views/Game/GameLogModal.tsx
Fixes missing thumbnails of cleanly scored boards
- Don't skip thumbnails just because `stones` is empty.
=> We need to show thumbnails even if `stones` is empty, if it exists.

src/views/ReportsCenter/ReportsCenter.tsx, src/views/ReportsCenter/ReportsCenterCMHistory.tsx
Fixes not being able to look back and compare our votes to others
- Make the Report Centre "History" page show CMs their voting history
* "prototype" implementation, will be easier to refine it when I can see real data in it :)
** needs https://github.com/online-go/ogs/pull/1982
=> First pass at "my own voting history table"

src/components/IncidentReportTracker/IncidentReportTracker.tsx, src/components/Report/Report.tsx
Fixes IncidentReportList getting stuck open, and confusing experience for CMs who submit dupe reports.
- Reset "show list" on mount
- Don't prevent CMs from submitting duplicate reports.
=> Let CMs submit dupe reports, and defend against list getting stuck open

src/components/Steps/Steps.styl
It's rare, but sometimes when you have a long tournament [like this one](https://online-go.com/tournament/95975) with many rounds, the page gets too wide from all of the rounds:
This fixes that, and wraps the steps after they hit the container width:
=> Wrap tournament steps when there are too many

src/views/User/ModLog.styl, src/views/User/ModLog.tsx
Attempt to be clearer in the mod log that "acknowledgement" means "we thanked this person for their report and they acked this".
Fixes moderators thinking that a person has been warned a lot, when in fact they have been thanked a lot.
- Change the styling of "acknowledgement" entries
Note: ideally the backend should not call these "warnings" either ... that word comes from the backend and is displayed confusingly.
=> Clarify "acknowledgement" severity warnings

src/views/ReportsCenter/ReportsCenterCMInfo.tsx, src/views/ReportsCenter/ReportsCenterHistory.styl
Fixes graph breakage that will be happen when https://github.com/online-go/ogs/pull/1991 goes in :)
-  Use the new route names.  
-- I put backward compatible routes into 1991, but we also need:
-  Tweak data decode to match updated structure
=> Update to match refactored/renamed CM outcome graphs

src/views/Game/PlayControls.tsx
Fixes users feeling like they can't accept the score
- "need to be" -> "may need to be"
=> Be less certain about whether the game can be scored or not in sealing warning

src/views/ReportsCenter/ReportsCenterCMDashboard.tsx
Fixes the titles/names not matching what the backend does (will do).
(Which in turn fixes the graphs not really warning us if a CM is going off reservation)
- Don't refer to "Voting Outcome" where we mean "Vote Category"
A companion to https://github.com/online-go/ogs/pull/1996 , which does the actual work.
=> Aesthetic change corresponding to backend reporting change

src/views/ReportsCenter/ReportedGame.styl, src/views/ReportsCenter/ReportedGame.tsx, src/views/ReportsCenter/ReportsCenter.styl, src/views/ReportsCenter/ViewReport.styl
Fixes GameLog thumbnails conflicting with chat box
-  Let the ReportGame pane get as wide as it wants
This is not the solution I really want - which is to redo `ReportedGame` using Grid, or some other solution, to enfore the pieces where we want to see them.
But ... after I did this I thought "gee, actually I like ReportedGame being wider"... and it solves the immediate problem.
=> Redo reported game layout

src/components/Player/Player.styl, src/components/Player/Player.tsx, src/global_styl/font-awesome-hacks.styl, src/views/ReportsCenter/ReportedGame.tsx, src/views/ReportsCenter/ViewReport.tsx
Fixes Moderators losing track of who is who
- Have  `Player` provide a context that it can be rendered in to enable it to annotate participants in a report.
- Have `ViewReport` use that context.
=> Annotate `Players` in ViewReport

src/components/OgsHelpProvider/OgsHelpProvider.tsx, src/lib/hooks.ts
Fixes likely (now) and certain (upcoming) layout issues when RDH fires in mobile phone layout
- Use `window.watchMedia` to see if we are wider than 850px for isDesktop hook
- Use `isDesktop` hook to disable RDH if we're not on a desktop (by telling it that we're not ready)
I recently discovered an RDH popup-positioning bug that's ugly on mobile phone layout.
I'm working on the fix for that, likely "quick fix" ... once I can remember how to rebuild RDH 🥴
(The bug occurs when the target element is off the bottom of the screen ... not something that actually happens for the original flows, since RDH was mostly used for top right menu stuff initially)
=> Provide `isDesktop` hook, use it to turn of RDH on not-desktop

src/components/PaginatedTable/PaginatedTable.tsx, src/views/User/GameHistoryTable.tsx
Fixes #
- As a moderator, holding shift will select a list of rows for the annul queue
- Skips rows that are already annulled
- Can select top to bottom and bottom to top
- Also, removed ability to click already annulled game 
https://github.com/user-attachments/assets/4090732e-188c-4550-bd2d-9c4c8d5c59b7
=> Shift key to select rows for annul queue

package.json, yarn.lock
Fixes # yarn complaining about incorrect peer dependency
- Remove from package.json
=> Remove react-number-format dependency... we don't seem to use it.

src/views/Game/GameLog.tsx
Fixes GameLog modal not working on Game page
- detect when registerTargetItem isn't available, which is the case in an OGS Modal
=> Defend against GameLog being used in a context without help

src/components/PaginatedTable/PaginatedTable.styl, src/components/PaginatedTable/PaginatedTable.tsx
Fix pagination numbering on PaginatedTable component when user has played 0 games.
Before my change:
Pagination would display "1 / 0"
After my change:
Pagination displays "1 / 1"
This change also fixes the misaligned page numbering.
=> Fix PaginatedTable numbering

src/components/GobanThemePicker/GobanThemePicker.tsx
Fixes a stream of PersistentElement warnings
- Don't instantiate PersistentElement with null target in GoThemePicker.
FWIW ChatGPT thinks that PersistentElement should `throw` in that case, since it feels the caller is clearly in error.  I wasn't sure enough about it to do that :)
=> Guard GoThemePicker against trying to persist null elements.

src/views/Game/PlayControls.tsx
Fixes confusing game logs, possible side effects.
- Base the state of the `Accept` button on the state of the player's acceptance.
=> Base the disable of the accept score button on the state of accepted

package.json, src/components/OgsHelpProvider/OgsHelpProvider.tsx, src/views/HelpFlows/HelpFlows.styl, yarn.lock
Fixes having dynamic help on phones
- Leave RDH popups at the correct place vertically, just push them on the screen for phones, where the narrow width otherwise has them fall off the edge.
=> Restore dynamic help for mobile (with layout fix)

src/index.html
`<meta name="apple-mobile-web-app-capable" content="yes">` is deprecated.
The meta tag we should use is:
`<meta name="mobile-web-app-capable" content="yes">`
This updates the meta tag to keep OGS up to date with the latest web standards!
=> Update "mobile-web-app-capable" meta tag

src/components/AccountWarning/CannedMessages.ts, src/components/ModerateUser/ModerateUser.tsx, src/lib/moderation.tsx, src/lib/report_manager.tsx, src/lib/report_util.ts, src/models/warning.d.ts, src/views/ReportsCenter/ModerationActionSelector.tsx, src/views/ReportsCenter/ViewReport.tsx, src/views/Settings/ModeratorPreferences.tsx
Fixes Community Moderation being reliant on full moderators to process escalated reports that need user-suspension action.
- CMs can get vote-to-suspend power
- CMs with vote-to-suspend can  vote to suspend users when the report about the user is escalated
- Full moderators no longer get "CM-class" reports in their queues
- if they want to see a CM-class report they need to access it via History or URL (likely from Mod Log)
Needs:  https://github.com/online-go/ogs-node/pull/66
Needs: https://github.com/online-go/ogs/pull/2003
=> Support for CMs voting for suspend

src/components/AccountWarning/CannedMessages.ts, src/models/warning.d.ts, src/views/ReportsCenter/ModerationActionSelector.tsx
... and reorder code for consistent ordering of CM report types etc in code (escape, stall then score-cheat).
* Also moves CannedMessages to llm_pgettext
Fixes CM's not able to give people a final warning before suspending them
- Add support for voting for the new final warnings in https://github.com/online-go/ogs/pull/2005
- Reorder lists of these things for consistency
- Move all `CannedMessage` s to llm_pgettext
- Remove `\` from `CannedMessage` s
=> Add support for CM new actions: final warnings for current CM report types

src/components/ChallengeModal/ChallengeModal.tsx
This PR breaks apart the ChallengeModal into a thin Modal container and a body component to allow inlining of the challenge creation stuff into other views and components.
Hopefully minimally conflicts with #2845 but will likely result in some minor changes needed in that work.
=> Break apart ChallengeModal

src/views/ReportsCenter/ModerationActionSelector.tsx, src/views/ReportsCenter/ViewReport.tsx
and make sure CMs can see what's going on with the reason in escalated reports
Fixes mysteries about what were we thinking.
- Always show the escalation note
- Don't allow an escalation without an escalation note
=> Require CMs to give an escalation reason, 

src/lib/report_manager.tsx, src/lib/report_util.ts, src/views/ReportsCenter/ModerationActionSelector.tsx, src/views/ReportsCenter/ViewReport.tsx
Matches changes in backend as part of fixing escalation note handling
- Change the field name to the less confusing name now used in the back end
** Requires https://github.com/online-go/ogs/pull/2008 to go in at the same time.
=> Escalation note fieldname update

src/lib/report_manager.tsx, src/views/ReportsCenter/ViewReport.tsx
Fixes silent fail for CMs if posting their vote errors.
- Raise an alert with the error message.
=> Tell CMs if their vote errors on the back end

src/components/GobanContainer/GobanContainer.tsx, src/lib/preferences.ts, src/views/Game/Game.tsx, src/views/Settings/GamePreferences.tsx
Fixes #
https://github.com/online-go/online-go.com/issues/2075
- Add the ability to navigate the game by scrolling the mouse wheel behind a preference that is off by default
I am normally a backend engineer, so very open to feedback on my React 😄
I tested this on the local environment on a demo board and in puzzles, but was not sure if this could potentially break any other views.
=> add scroll to navigate functionality

src/components/SeekGraph/SeekGraphLegend.tsx, src/components/SeekGraph/SeekGraphPalettes.tsx, src/lib/challenge_utils.tsx, src/lib/preferences.ts, src/views/Play/Play.tsx
Fixes #2358
- Added Handicap filter, see #2358
Apologies for the very late PR
=> Added handicap filter

src/components/AccountWarning/CannedMessages.ts, src/models/warning.d.ts, src/views/ReportsCenter/ModerationActionSelector.tsx
Fixes not being able to vote to annul when no-one actually did anything wrong.
- Support https://github.com/online-go/ogs/pull/2012 with appropriate messages.
=> Support for the option for CMs to vote to annul without issuing warnings

src/lib/report_manager.tsx, src/lib/report_util.ts, src/views/ReportsCenter/ModerationActionSelector.styl, src/views/ReportsCenter/ModerationActionSelector.tsx, src/views/ReportsCenter/ViewReport.styl, src/views/ReportsCenter/ViewReport.tsx
Fixes urge for CMs to escalate when really they just want to clarify.
- Prompt the CM for an explanatory note if they select a dissenting vote.
- Display dissenter notes in ViewReport
NEEDS https://github.com/online-go/ogs/pull/2016
=> Dissenter note

src/views/ReportsCenter/ReportsCenterCMDashboard.tsx
Fixes  CM Group Outcome graphs having nothing much to show
- Graph escalations and unanimity or otherwise of outcomes.
NEEDS: https://github.com/online-go/ogs/pull/2018
=> Redo the group graphs to match the new data relating to the new voting policies

src/lib/preferences.ts, src/views/Play/CustomGames.styl, src/views/Play/CustomGames.tsx
Fixes seek graph taking up unwelcome space on Custom Games page
- Provide a toggle to turn it on for people who want to see it.
Note: some shenanigans are required to keep seek graph rendered, so we don't loose the ref to it.
=> Provide a toggle to turn on display of seek graph

src/views/ReportsCenter/ReportsCenterCMDashboard.tsx, src/views/ReportsCenter/ReportsCenterCMHistory.tsx, src/views/User/CMPieCharts.tsx
Fixes out of date / bugged stats appearing
- Tweak chart parameters so we don't see old data in places where it's no longer meaningful
- Tweak charts to understand that 'escalated' is not an outcome.
NEEDS https://github.com/online-go/ogs/pull/2021
=> Update CM stats graphs in line with changes in back end 

src/ogs.styl
Fixes https://github.com/online-go/online-go.com/issues/2566
-Slightly lightens all of the buttons using dark.default-button for better visibility against the dark background
Before:
After:
=> Update dark mode button to have better contrast

src/components/NavBar/NavBar.styl
I noticed the mobile menu items left padding currently doesn't match that of the hamburger and it was bothering me a bit, hope this is welcome!
=> Improve mobile menu left padding to match hamburger

src/components/AccountWarning/CannedMessages.ts, src/views/ReportsCenter/ModerationActionSelector.tsx
- Say "the other player" instead of "your opponent"
- Use a proposed context in one canned message to see if it helps
=> Reduce use of word `opponent`, trial more context in a canned message

.vscode/cspell.json, src/components/ChallengeModal/ChallengeModal.styl, src/components/ChallengeModal/ChallengeModal.tsx, src/lib/bots.ts, src/views/Play/CustomGames.styl, src/views/Play/CustomGames.tsx, src/views/Play/QuickMatch.styl, src/views/Play/QuickMatch.tsx
This branch switches away from first having to select if you want to play a human or a computer, and instead replaces those with two buttons, one to challenge a computer, one to challenge a human. This patch (will) also updates the computer challenge modal to be more streamlined with the quick settings on the play page.
=> Switch to computer/human buttons on the Play page

src/views/ReportsCenter/ReportsCenterCMDashboard.tsx
Fixes seeing a week with missing stats in graphs
(in conjunction with https://github.com/online-go/ogs/pull/2024 )
=> Use library start of week, and set it the same as we're using in graphs

src/components/Notifications/NotificationManager.tsx
`time_to_move` does not exist on the boards in notification manager.  Yay TypeScript :partying_face:
---
In case you don't believe typescript, one can also verify in the console:
```
> Object.values(notification_manager.active_boards)[0].time_per_move
88449
> Object.values(notification_manager.active_boards)[0].time_to_move
undefined 
```
=> buxfix: "urgent" game notification handling

src/components/Notifications/NotificationManager.tsx, src/views/Play/CustomGames.tsx, src/views/Play/QuickMatch.tsx
This patch makes it so if a player is actively searching for an automatch and a live game starts, either by accepting an open challenge, or accepting a direct challenge, or someone accepting their direct challenge, the automatch search is canceled.
Requires https://github.com/online-go/ogs/pull/2028
=> Cancel live automatche searches when any live game starts

src/components/NavBar/NavBar.tsx
Fixes it being fairly well hidden
- Put "Contribute To Translation" as a link under "Tools"
=> Add a menu like to translation under tools

src/views/ReportsCenter/ModerationActionSelector.tsx
Fixes AI thinking that "escape" means "escape punishment"
- Add a definition of the jargon `escape`
=> Tweak CM prompt context to explain `escape`

src/views/ReportsCenter/UserHistory.tsx, src/views/User/ModLog.styl, src/views/User/ModLog.tsx
… and remove dead filtering code (backend does this now)
Fixes potential confusion about what really happened
- Clarify somewhat that the vote was an action, but it doesn't mean more than that.
- Get rid of mod log filtering to "not acks" because the backend already does that now
- Prettier changed `@extends` to `@extend`  🤷‍♀️
=> Add clarifying text to CM mod log

src/views/User/ModLog.tsx
Fixes `-` appearing where it should be the `reporter` in ModLog
- Use the renamed `actor` field in that position of the ModLog
Needs: https://github.com/online-go/ogs/pull/2031
(won't totally break without it, but won't show any names in that column until the backend is in)
=> Show CMs the mod log actor

.vscode/settings.json, src/ogs.styl, src/views/Play/QuickMatch.tsx
Fixes uncertainty about whether + means stronger or weaker rank.
- Put a header at the top of each open dropdown.
https://forums.online-go.com/t/enemy-strength-selection-in-play-menu-somewhat-unintuitive/55181/14?u=greenasjade
=> Put Weaker/Stronger headers on the QuickMatch rank range selectors

src/lib/preferences.ts, src/models/moderation.d.ts, src/views/ReportsCenter/UserHistory.tsx, src/views/User/ModLog.tsx
Fixes lots of scrolling instead of seeing at a glance the important voteable things.
- Make it so that CMs can collapse the ModLog completely, or filter it to show only CM voted warnings
=> Make CMs able to squish or close ModLog.

.gitignore, vite.config.ts
Fixes hair pulling head banging streams of tears trying to locally link dev rdh repo into dev build
- Tell vite not to optimize rdh.
*** This is draft because I did what ChatGPT told me to do and it worked BUT I am not sure of side effects.  Please check :)
=> Changes needed to make yalc work to link in rdh

eslint.config.mjs, src/ogs.styl, vite.config.ts
and update rdh version and get styles from the right place
Fixes thow errors on running vite
- Get rid of unnecessary references to node_modules/goban (under instructions from ChatGPT)
- Refer to RDH submodule css source from ogs.styl
^^^ needs a look to confirm this will work in prod
Also brings in updates to RDH to fix types
=> Fix vite config to understand goban is not in node_modules

src/components/Report/Report.tsx
Fixes [Mr Tal feeling we're not doing enough](https://forums.online-go.com/t/ai-use-not-allowed-message/55291/45?u=greenasjade).
- Make it say "please be sure that it was AI if you're going to report it"
=> Change the AI report description to be more insistent that the report  is substantiated.

.vscode/settings.json, jest.config.ts, package.json, src/components/ChallengeModal/ChallengeModal.test.tsx, src/components/ChallengeModal/ChallengeModal.tsx, src/components/ChallengeModal/ForkModal.tsx, src/components/LanguagePicker/LanguagePicker.tsx, src/components/Modal/Modal.tsx, src/components/Modal/ModalContext.tsx, src/components/Modal/ModalProvider.tsx, src/components/Modal/ModalRegistry.ts, src/main.tsx, src/views/Game/GameDock.tsx, src/views/HelpFlows/HelpFlows.tsx, src/views/HelpFlows/ModalHelp.tsx, src/views/Play/Play.tsx
Fixes #
https://github.com/user-attachments/assets/611d3cdc-0b2a-4419-a74b-1ac3d95eccf6
- We had been unable to add tooltips on modals because modals were never a nested component under the main tree containing the DynamicHelp provider.
- Feel free to try this out by following the video!
- Infrastructure: add the modal provider as a component under the OGSHelpProvider to consumer tooltip information.
- ActivateTooltip - React component to make it easy to trigger tooltips anywhere. Happy to update if I'm not handling all cases.
- Modal Context
- Modal Provider - A context for modals to be rendered at the top of the tree, right under the DynamicHelp functionality. CURRENTLY used only for creating a computer challenge
- Modal Registry - This will include the list of modals that will use this …
=> POC - Add tooltip to modal, Modal provider (for computer challenge, language picker, game fork)

src/components/AccountWarning/CannedMessages.ts, src/components/ModerateUser/ModerateUser.tsx, src/lib/moderation.tsx, src/lib/report_manager.tsx, src/lib/report_util.ts, src/models/warning.d.ts, src/views/ReportsCenter/ModerationActionSelector.tsx
Fixes: the situation of "nothing we can do" about backlog of AI reports.
- Have an ASSESS_AI_REPORTS power for CMs
- Show AI reports initially to these CMs, and not full moderators
- If the CMs vote that there certainly is AI, then escalate the report to full moderators (for warn/suspend and annull games)
- If the CMs vote that there might be AI, then escalate to full moderators for full tool analysis and follow up
- If the CMs vote that theres no sign of it, then close it and tell the reporter.
Needs https://github.com/online-go/ogs/pull/2034 and its dependency in node.
Will break (by submitting votes that don't work) without the backend changes.
=> Supports ASSESS_AI_REPORT power for CMs

src/lib/report_manager.tsx, src/views/ReportsCenter/ModerationActionSelector.tsx, src/views/ReportsCenter/ReportTypeSelector.tsx
and be clearer if mods have claimed but not resolved reports.
Fixes mods not being able to help in the case of CM AI report bugs, and CMs wondering what happened to the report.
- Put unescalated AI reports back into full mod queue
- Give a different message if a mod has claimed but not resolved a report
=> Let mods see unescalated AI reports

src/views/ReportsCenter/ViewReport.tsx
Fixes # CM actions disappearing
- Don't call setAvailableActions if the incoming report doesn't have them
** This is a workaround, because the incoming report should always have them :(
Something odd going on in backend.
=> Don't blow away CM actions when we receive null from term server

src/components/Player/Player.tsx, src/contexts/ReportContext.tsx, src/views/Game/AIReview.tsx, src/views/ReportsCenter/ViewReport.tsx
... for CMs doing AI assessment (only).
Fixes CMs with ASSESS_AI_REPORTS power not really having all the information they could do with.
- Make the AI stats table visible in the Report context for such CMs.
-- Refactored the "ReportContext" to be more generic, so it handles this and the "player annotation".
Rationale: we're not showing them anything they can't get computed for themselves, no particular secret sauce in this information.
=> Make the AI stats table show up in Reports view 

src/views/ReportsCenter/ViewReport.tsx
Fixes ugly green button that would do nothing, when escalated AI reports come in to CM queue
- Disable "ModeratorActionSelector" for escalated AI reports
-- Because these are not handled by CMs, but they want to view them.
Can go in first.
=> Disable vote button if its an escalated AI report

src/components/AccountWarning/CannedMessages.ts, src/models/warning.d.ts, src/views/ReportsCenter/ModerationActionSelector.tsx
Fixes CM AI Assessors having no way of pushing back on silly AI reports
- Add a voting option that lets them send an "educate reporter" Canned message.
Needs to go in with https://github.com/online-go/ogs/pull/2041 due to different message interpolation content 
(reported game instead of reported user)
=> Support `no_ai_use_bad_report` CM vote action

src/components/AccountWarning/CannedMessages.ts, src/components/IncidentReportTracker/IncidentReportCard.tsx, src/components/IncidentReportTracker/IncidentReportList.tsx, src/lib/report_manager.tsx, src/lib/report_util.ts, src/models/moderation.d.ts, src/views/ReportsCenter/ModerationActionSelector.tsx, src/views/ReportsCenter/ReportsCenter.styl, src/views/ReportsCenter/ReportsCenter.tsx, src/views/ReportsCenter/ReportsViewer.styl, src/views/ReportsCenter/ReportsViewer.tsx, src/views/ReportsCenter/ViewReport.styl, src/views/ReportsCenter/ViewReport.tsx
Fixes fragile report handling/presentation
UI updates to match cleaner separation of report data coming over websocket and HTTP. 
Ensure object types reflect where they came from.
Make ModNote real time editting a bit cleaner.
Built on top of #2976 ... propose: work with this one instead.
Needs https://github.com/online-go/ogs/pull/2042
Brings (needs <- is that the right word?)  https://github.com/online-go/goban/pull/184
=> Incident report data delivery refactor

src/views/ReportsCenter/ReportsCenter.tsx, src/views/ReportsCenter/ReportsViewer.tsx
…  and lets CMs vote on their own CM reports
Fixes #  "Access Denied" for CMs who have submitted non CM reports
- Improve clarify in ReportsCenter about what kind of report is what.
- Pass only "moderateable" reports to ModerationReportsViewer
* * * I'm not sure why this is showing a goban update.   When I made this commit, my goban submodule was on main.
=> Fixes bug where ReportsViewer was getting nonCM reports

src/components/IncidentReportTracker/IncidentReportIndicator.tsx, src/lib/preferences.ts, src/lib/report_manager.tsx, src/views/ReportsCenter/ReportsCenter.tsx, src/views/Settings/ModeratorPreferences.tsx
…and its interaction with `ReportManager`
Fixes flakey or confusing behaviour 
- Make ReportManager properly responsible for sorting out who sees what.
-- Put all quota and "the already voted" stuff in ReportManager
- Have ReportManager eat its own dogfood for counting reports, so it always gives the same answer in all situations
- Be clear about what IncidentReportIndicatior is going to show:
-- Moderators and CMs: the count of things we want them to act on
-- Non-mod: the count of reports they submitted
- Show the count of "My Report" in Reports Center (so moderators have a way to see this)
- Provide full moderators with the option to have the old "Report Queue Dropdown" aka `IncidentReportList`
-- CMs can't have this because voting options don't fit into an `IncidentReportCard`
** …
=> Overhaul `IncidentReportIndicator` 

src/components/ModerateUser/ModerateUser.tsx, src/lib/moderation.tsx, src/models/moderation.d.ts, src/views/ReportsCenter/ViewReport.styl, src/views/ReportsCenter/ViewReport.tsx
... if the back end sends it, and a power for CMs to see it.
Fixes CMs raising alerts when in fact the person is already dealt with
- Add a CM power to let them see this
- Show it in ViewReport when the back end sends it
(Obviously needs the back end update to do anything, but is OK without it
https://github.com/online-go/ogs/pull/2046
).
=> Support showing mods the reported user's suspend status 

vite.config.ts
- Add DOCKER as a webserver back end choice: lets docker-compose set this to point to it's frontend instance in e2e test config.
- This points things direct at loadbalancer ... seems to work :o
=> Add a web server back end choice: DOCKER.

src/index.html
That's a first PR of a series a changes I'll propose to improve accessibility of OGS for visually impaired users. 
I'll keep each PR minimal to make it easy to review and move forward with individual pieces of work.
- Add a class `.sr-only` (screen-reader only), that will hide content from screen but make it available for screen readers. Added directly in the html to make it available from the very beginning as it's used for the loading message.
- Add a "loading" message for screen readers, using `.sr-only`.
- Add aria- properties [`role status` + `aria-live polite`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Roles/status_role) to make it a low priority information
- mark the svg loader as hidden for screen readers
Note: I don't think there is a good way to …
=> Add screen reader support for initial loading indicator

src/components/NavBar/NavBar.tsx
follow up of #2992
- remove `<li>` nested in `<li>`
=> remove nested <li> in navbar > settings > more settings

src/components/NavBar/NavBar.tsx
in #2992 I haven't used `external` for the link to the translation (in tools dropdown) 
- Fix link to translation
=> Fix navbar link to translations

vite.config.ts
(and get rid of the docker backend option, since we're not doing that)
Fixes new Devs not knowing about Slack
- use a funky plugin to pop up the banner
- get rid of OGS_BACKEND=DOCKER option
-
=> Put back the Invite Devs To Slack banner

src/components/ModerateUser/ModerateUser.tsx, src/lib/moderation.tsx, src/views/Game/GameTimings.tsx
Fixes those CMs not being able to see the info they need.
- Add a CM ability for AI detection
- Show ai detection info to empowered CMs, if the backend sends it
Needs https://github.com/online-go/ogs-node/pull/80 to actually do anything.
=> Add support for CMs involved in ai detection work

e2e-tests/cm/cm-auto-warn-first-turn-escaper.ts, e2e-tests/cm/cm-dont-notify-escalated-ai.ts, e2e-tests/cm/cm-vote-on-own-report.ts, e2e-tests/helpers/user-utils.ts, e2e-tests/smoke/smoke-register-operations.ts, playwright.config.ts
Fixes potential to get confused and flakey with seeded data.
- Each test that needs seeded data gets its own seeded data
- Consistent naming of seeded data artefacts and their connection to test names
Needs https://github.com/online-go/ogs/pull/2053  to be run on e2e target.
=> Rationalise naming and seed data use

e2e-tests/cm/cm-auto-warn-first-turn-disconnector.ts, e2e-tests/cm/cm-dont-notify-escalated-ai.ts, e2e-tests/cm/cm-show-only-post-escalation-votes.ts, e2e-tests/cm/cm-vote-on-own-report.ts, e2e-tests/cm/cm.spec.ts, e2e-tests/helpers/report-utils.ts, playwright.config.ts
Also added serialisation of tests using IncidentReportIndicator, so remainder can run in parallel.
Fixes not having a test to prove this works, and not being able to run tests in parallel
- Test that first turn disconnection triggers the warning
- Make tests using IncidentReportIndicator get a lock to do that.
=> Added e2e test for OGS PR2057: auto warn disconnecters.

e2e-tests/cm/cm-show-only-post-escalation-votes.ts, e2e-tests/cm/cm-vote-on-own-report.ts, e2e-tests/cm/cm.spec.ts, e2e-tests/helpers/user-utils.ts, e2e-tests/moderation/mod-auto-warn-first-turn-disconnector.ts, e2e-tests/moderation/mod-auto-warn-first-turn-escaper.ts, e2e-tests/moderation/mod-block-early-escape-report.ts, e2e-tests/moderation/mod-block-early-stall-report.ts, e2e-tests/moderation/mod-dont-auto-warn-first-turn-blitz.ts, e2e-tests/moderation/moderation.spec.ts, playwright.config.ts, src/components/Report/Report.tsx
Also refactor e2e to put this in with other "Moderation" reports in a Moderation group.
Fixes impatient people still reporting first turn escapes even though we told them we did it for them.
- Use `ReportDescription.check_applicability` to disallow first turn reporting of escape and stall
- Add and update e2e accordinly (use score cheat for early report tests instead :) )
( E2E needs updated init_e2e  https://github.com/online-go/ogs/pull/2061 )
=> Add "report on first turn not allowed" to `appropriate-check` for escape and stall reports.

src/components/RatingsChartDistribution/RatingsChartDistribution.styl, src/components/RatingsChartDistribution/RatingsChartDistribution.tsx, src/views/User/User.tsx
- Syncs hide_ranks preference and temporary_show_ratings with showDistributionChart toggle in https://github.com/online-go/online-go.com/commit/352950d9df5330264b1286660dc6f2626f48b85c
- adds text overflow eclipse (truncates string) to player names plotted on chart
=> hide ranks to show dist & text overflow

src/lib/preferences.ts, src/views/ReportsCenter/ReportsViewer.tsx
Fixes hard to work on component.
-  Break up the header into separate components.
*: Note, this is somewhat tested by CM E2E tests, and that's all we can do, because we don't do Moderator E2E at the moment.
=> Decompose `ModerationReportsViewer` into easier to read components.

e2e-tests/challenges/ch-handicap-prefs.ts, e2e-tests/challenges/ch-preferred-rank.ts, e2e-tests/challenges/ch.spec.ts, e2e-tests/helpers/challenge-utils.ts, src/components/ChallengeModal/ChallengeModal.tsx
Fixes not detecting that a current no-restrict-ranks setting matches an old saved one
- Detect rank restriction during match consistently with the way it is loaded
=> fix detected of saved restrict rank prefs

src/views/Play/QuickMatch.styl, src/views/Play/QuickMatch.tsx
... for better tidiness on the Play page.
Fixes  words about please sign in kind of floating in a jumble on the page.
- Make the `anonymous-container` in QuickMatch be a Card, with suitable margins.
=> Put the "sign in to play" message in a visual frame (Card)

src/ogs.styl, src/views/Play/QuickMatch.styl
Gave the `play-buttons` their own z-index, made sure handicap menu is on top.
Fixes handicap menu being obscured by play buttons in mobile view.
- Give play buttons their own z-index, and put menu above it.
=> Fix clipped handicap menu

e2e-tests/challenge-modal/ch-private-invite.ts, src/components/NavBar/NavBar.tsx, src/models/games.d.ts, src/routes.tsx, src/views/AIDetection/AIDetection.styl, src/views/AIDetection/AIDetection.tsx, src/views/AIDetection/index.ts, src/views/Game/AIReview.tsx
Fixes AI detection enthusiasts complaining that they don't have data to work with
- Add a "Tools" page that lists recent games' AI detection results summary
This is a "very first pass" to see what might be useful and how to present it.
Needs https://github.com/online-go/ogs/pull/2064
(Just shows nothing without it).
=> AI Detection Results page

e2e-tests/cm/cm-vote-warn-not-ai.ts, e2e-tests/cm/cm.spec.ts
Fixes not having a specific test to about "warnings get issued from voting"
- Add a test that makes sure a warning is successfully voted.
( TBD: a separate E2E test, or extend this one, to check the warning is issued to the player )
Needs: https://github.com/online-go/ogs/pull/2068 for seed data before it can be run in beta.
Is not part of smoke test e2e.
=> Add a test for cm voting to warn about bad AI reports

src/components/ModerateUser/ModerateUser.tsx, src/components/ModerationOfferControl/ModerationOfferControl.styl
(Some relayout of "moderator actions" modal)
Fixes moderators not being able to do anything about players who somehow get stuck with the warning flag on.
- Add a "Clear warnings" button to moderator actions modal
- Relayout moderator actions modal to suit
Needs https://github.com/online-go/ogs/pull/2070  , button just doesn't work without this.
=> Adds a button for moderators to clear a player's warning flag.

e2e-tests/smoke/smoketests.spec.ts-snapshots/profile-page-chromium-linux.png, src/views/User/ActivityCard.tsx
Fixes confusing language about what is an "acknowledgement"
- Use "Report System Messages" as the title of the thing that contains warnings and acks, rather than "Warning System Messages"
=> Say "Report System Messages" for the section that contains these.

.vscode/cspell.json, e2e-tests/cm/cm-ack-ack.ts, e2e-tests/cm/cm-ack-warning.ts, e2e-tests/cm/cm.spec.ts, e2e-tests/moderation/moderation.spec.ts, src/components/AccountWarning/AccountWarning.tsx, src/models/user.d.ts
Fixes dubious logic that was blocking users from playing games if they have an outstanding ack message.
Theoretically should have been OK, but better not to have that logic.
- Use the new `has_pending_warning_system_message` flag to display acks and warnings
- Use the rescoped has_active_warnings to block the "play a game" buttons (no change)
- Adds e2e test to make sure the buttons are blocked for warnings and not for acks.
** Needs https://github.com/online-go/ogs/pull/2073  (breaking).
Note that this is transparent to mobile apps: they use the existing has_active_warnings flag, and that will continue to work.
The only change for mobile aps would be that mobile apps that don't update to use the new flag will not display "acks".   I doubt if any do that anyhow, and since acks now are not …
=> Make only warning block games

src/views/AIDetection/AIDetection.styl, src/views/AIDetection/AIDetection.tsx
Fixes # inability to see an overall view of a player's ai analysis profile
- Add a PlayerSearch thingo and ask the backend to filter by player
Needs https://github.com/online-go/ogs/pull/2075
=> Filter ai detection by player

src/models/games.d.ts, src/views/AIDetection/AIDetection.tsx
and tweak ai detection table layout for better interpretation.
Fixes # Not knowing which algorithm generated the data.
- Show analyzer version
- Hide data from pre-new-AILR versions
- Hide APL and timing for now, because they still seem suss
- Use query param to turn those on for debug
- Get game length from bot_detection_results, because that's where it is now.
Needs https://github.com/online-go/ogs/pull/2077
=> Use analyzer_version to hide old data, 

src/components/JosekiTagSelector/JosekiTagSelector.tsx, src/components/JosekiVariationFilter/JosekiVariationFilter.tsx, src/views/Joseki/Joseki.styl, src/views/Joseki/Joseki.tsx
Fixes people complaining that they don't notice that it's filtered.
- Background-highlight active filter selectors
- Add a * to the Filter tab label when there's a filter active but not shown on the current extra info tab
=> Change the background of filter selectors when they have an active selection

src/components/SeekGraph/SeekGraph.tsx
- append seek graph modals to seek graph container to ensure correct text color
- currently text color in **dark** _and_ **accessible** mode is black but should be white for readability
- could just add styling, but appending to the seek graph container seems like the correct approach so that it inherits existing `body.dark #main-content` and `body.accessible #main-content` text styling
- This implementation currently falls back to the existing implementation of appending the modal to the body for robustness if for whatever reason the seek graph container is unavailable. Now that I'm thinking about it, it's probably better to add `SeekGraphConfig.modalContainer` to specify the container element to add the modal to, and use the implemented defaults if the config is not set. May submit a …
=> fix: append seek graph modal to container to ensure correct text color

src/views/Game/Game.tsx
Fixes Issue #3087 
Brings Portrait-view `CancelButton` implementation in-line with `PlayControls` func/interfaces (as in wide/desktop view)
#TODO (future feature request?): 
If we want to modify `PlayControls` to include "outright resign" btn during "Stone Removal" phase ->  that should be a very quick fix -> just put `goban.resign()` somewhere between:
https://github.com/online-go/online-go.com/blob/d9dcae91f165583cc24b54b36d583eceaf650727/src/views/Game/PlayControls.tsx#L318-L323
and modify div `stone-removal-controls`: 
https://github.com/online-go/online-go.com/blob/d9dcae91f165583cc24b54b36d583eceaf650727/src/views/Game/PlayControls.tsx#L525-L535
=> Fixes cancel/resign on mobile during AI Review, stone removal phase #3087

src/views/Puzzle/Puzzle.tsx
- Fixed a bug where the hint button state would stay set to true after navigating to a new puzzle
- Original bug replication steps:
1. Go to a puzzle, like this one: https://online-go.com/puzzle/2629
2. Click the hint button
3. Swap puzzles by clicking the dropdown to the right of "Puzzle", and selecting a different puzzle
4. Notice how the hint state is still set to true, meaning the user has to click the button TWICE to see the new hint
TODO: Noticed another bug, if we click the hint button, then click something like the fullscreen button, or the reverse color button, the hint is removed from the board, but the hint state is still set to true, meaning the user has to click the hint button twice to see the hint again. 
Proposed solution:
- Simply set the hint button state to false …
=> Hint button bug fix

src/views/AIDetection/AIDetection.tsx
Fixes going to look at games that have already been handled.
- Mark games that are annulled in the AID table.
Needs https://github.com/online-go/ogs/pull/2086 to work (just doesn't mark them without it)
=> Mark annulled games in AID table

.vscode/settings.json, e2e-tests/e2e-utils/e2e-utils.spec.ts, e2e-tests/e2e-utils/run-game.ts, e2e-tests/games/bot-detect.ts, e2e-tests/helpers/game-utils.ts
…rather than really trying to test stuff.
-  Adds the e2e-utils group of tests, with run-game in it.
To use: edit the sequence of moves in run-game.ts, then run that specific test.
I find the UI the most convenient:
`yarn test:e2e:ui`
=> Added a "utillity test", which is there to let us run games 

jest.config.cjs, teardown-jest.cjs
Fixes #  "A worker process has failed to exit gracefully and has been force exited."
- jest teardown
=> Add teardown, to get rid of "failed to exit" warning

src/views/Game/AIDemoReview.tsx, src/views/Game/AIReview.tsx, src/views/Game/Game.tsx
Fixes #2874
When AI analysis is enabled, the old board annotations are saved, and when AI analysis is disabled, the old board annotations are reloaded.
Requires: online-go/goban#193
=> Keep track of which annotations were created by AI (issue #2874)

.github/workflows/e2e_test.yml, .github/workflows/unit_test.yml
Fixes confusion about which test failed, and waiting for one when you're intersted in the other :)
- Split unit and e2e tests into separate jobs
=> Separate test.yml into two

e2e-tests/games/conditional-moves-arrow.ts, e2e-tests/games/games.spec.ts
Fixes having to click to make this happen each time :)
- Add a test for  https://forums.online-go.com/t/analysis-mode-triggered-too-aggressively-during-conditional-moves/57453/4?u=greenasjade
=> A test to check that arrow key doesn't exit conditional moves

src/views/Game/AIReview.tsx, src/views/Game/GameDock.tsx
and bot detection results
Fixes AI detectors having to report a suspect game in order to see the needful.
- Let them see it on the game page.
=> Let AI detectors see all data in the timing table

src/lib/preferences.ts, src/views/Settings/ThemePreferences.tsx
Adds a drop down to our theme settings to support different shadow styles:
Low: (what we used to have a few days ago)
Mid: 
High: 
And of course custom because we love options here:
=> Shadow theme selection support

e2e-tests/smoke/joseki_screenshot_mask.css, e2e-tests/smoke/smoke-css-sanity.ts, e2e-tests/smoke/smoketests.spec.ts-snapshots/groups-page-chromium-linux.png, e2e-tests/smoke/smoketests.spec.ts-snapshots/joseki-page-chromium-linux.png
Fixes not having something that makes sure Joseki page is kinda live.
- Add a basic screenshot comparison
(get rid of unused old png)
=> Add a smoke test for joseki page basic render.

README.md
It's currently got a link to socket.io docs.  https://docs.online-go.com appears to host the latest on interacting with the RT API.
=> README: link to the newer Real Time API docs

src/views/Game/fragments.tsx
Fixes the issue of wrong game rules getting displayed on the Demo Board.
I've mentioned about this issue in #3190
Here's a link to the forum proving that this issue is also faced by Users. https://forums.online-go.com/t/demo-board-with-chinese-rules-shows-japanese-rules-instead/57801
1. Create a Demo Board with rule anything other than Japanese.
2. Observe that the rules displayed on top-right is "Japanese"
I noticed that the rules were getting displayed correctly, when I resized the window. Or when I go in-out of Zen mode. Which prompted me to think that resizing is causing a re-render of the element that displays the rule.
- Update for fragment's `GameInformation` to actively listen to Game rule, so that it renders correct rule the first time, and everytime the Demo Board's rules are …
=> Update gameInformation to listen to game rule change

src/models/challenges.d.ts, src/views/Overview/InviteList.tsx
~~Fixes~~ supports fix for  #2436
- Match API for receiving `private` field from seekGraph
* Needs: https://github.com/online-go/ogs/pull/2129    (`private` will be wrong if that's not in)
=> add `private` to challenge dto in seekGraph flow

src/views/ReportsCenter/ViewReport.tsx
Fixes AI Detectors not being able to describe the situation
- Let them access "moderator notes" for AI reports
Needs https://github.com/online-go/ogs/pull/2134 or will just error on submission.
=> Give AI detectors access to moderator note on AI reports

src/views/ReportsCenter/ReportsCenter.tsx
Fixes: not knowing which tabs are open on the reports center
=> Show the title on the reports centre page

src/views/ReportsCenter/ReportsCenterCMHistory.tsx, src/views/ReportsCenter/ViewReport.tsx
Fixes AI Detectors not being able to see what is going on and make sure they are aligned
- Display AI detection votes (only, not Dan CM votes) to AI detectors
-- Dan CM votes aren't displayed because currently Dan CMs get to be anonymous
-- We're not using Dan CMs much at all at the moment anyhow
=> Show AI Detectors all AI reports in "Report History"

src/views/ReportsCenter/MessageTemplate.tsx
Fixes # URL getting next word tacked on to it in mod template
And typing more characters every time
-  Add a space on the end of the line with the URL
- Add message about annulled
(Note, we might want to find the regex that isn't working for URLs on the end of a line, but... lazy, expeditious?)
Ref:  
https://online-go.com/reports-center/score_cheating/170561
=> Fix URL recognition, add annulled messages

e2e-tests/cm/cm-ack-ack.ts, e2e-tests/cm/cm-ack-warning.ts, e2e-tests/cm/cm-ai-assess-dismiss.ts, e2e-tests/cm/cm-dont-notify-escalated-ai.ts, e2e-tests/cm/cm-show-only-post-escalation-votes.ts, e2e-tests/cm/cm-vote-on-own-report.ts, e2e-tests/cm/cm-vote-warn-not-ai.ts, e2e-tests/games/bot-detect.ts, e2e-tests/games/games.spec.ts, e2e-tests/games/simul-detection.ts, e2e-tests/helpers/game-utils.ts, e2e-tests/helpers/user-utils.ts
Fixes not having a test for new simul code
- Test "contained game" scenario, as a "useful start"
Note: Needs https://github.com/online-go/ogs/pull/2144 and init_e2e run on beta for anyone to be able to run this against beta (but hardly anyone will).
=> Simul detect test, util function rename

.vscode/cspell.json, e2e-tests/AGENTS.md, e2e-tests/CLAUDE.md, e2e-tests/README.md, e2e-tests/cm/cm-vote-suspend-user.ts, e2e-tests/cm/cm.spec.ts, e2e-tests/global-teardown.ts, e2e-tests/helpers/report-utils.ts, e2e-tests/helpers/user-utils.ts, playwright.config.ts
Fixes not having a test for suspension->appeal path
- Add a test for CM suspension->appeal.
Needs https://github.com/online-go/ogs/pull/2145 for increased username length support and 
init_e2e  rerun on beta for front end devs to run this test against beta.
=> E2e cms can suspend

e2e-tests/AGENTS.md, e2e-tests/helpers/user-utils.ts, e2e-tests/users/suspended-user-profile-updates.ts, e2e-tests/users/users.spec.ts, src/components/BanModal/BanModal.tsx, src/components/Player/PlayerDetails.tsx
AND terminology fixes in Mod UI "ban"->"suspend" to match User UI from way back
Fixes not having a test to make sure the backend change worked.
- Add e2e test for username change
-- Testing av changed proved tricky, providing an image from PW
- ALSO change Mod interface to say "Suspend" in affected areas
Needs https://github.com/online-go/ogs/pull/2146
=> e2e test for "can't change profile while suspended"

src/lib/preferences.ts, src/views/Game/Game.styl, src/views/Game/PlayButtons.tsx, src/views/Settings/GamePreferences.tsx
When playing on my notebook with just the touch pad, I find moving the mouse to the submit button and back to the board the whole (live) game quite cumbersome.
That's why this pull request
- adds a setting to automatically focus the submit move button,
- adds a symbol to the submit move button when focused (if the setting is turned on), to show that it can be activated by pressing the enter key.
---
There's a small issue though:
- If the setting is turned on and the button loses focus (e.g. by focusing the chat before submitting), once the button is clicked it gets focused (by the browser) and briefly shows the symbol too, before the whole button disappears.
I'm not happy about that, but I don't know how to prevent it neatly.
=> Automatically focus submit move button
